### ISSUE TITLE
Offer option to easily delete contacts

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1170] opened 2017-12-16 22:00 UTC
Currently it is a bit misleading as you can either only delete conversations with contacts still being archived or blocking a contact which assumes that there is a block list where contacts are still stored. I think it is important to offer an option to easily delete contacts without any of the linguistic obfuscation.

**Comment by gregor** [comment] 2018-06-01 10:21
Thanks for the feedback. We have no current plans to change the design of the feature. With the nature of of this being a request to change a feature and not a bug I am going to close the issue.

**Closed by gregor** 2018-06-01 10:21 UTC
Labels: Feature Request

**Comment by baimafeima** [comment] 2018-09-03 21:17
@gregor To me it rather sounds like a bug than a feature. I'm also unsure why you would close this issue regardless whether it's handled as a bug or feature. My suggestions to improve user interface design are usually well-paid and I'm giving my suggestions here for free.

**Comment by baimafeima** [comment] 2018-10-04 17:31
@ffflorian You've added the enhancement label some time ago. Would you mind looking at this issue again? I think it's definitely a usability issue which is bothering for a lot of users and I've asked around among those who use Wire. I also believe it wouldn't be too hard to actually improve this situation.

**Comment by Aikatsui** [comment] 2021-05-31 09:37
https://github.com/wireapp/wire-webapp/issues/11198 https://github.com/wireapp/wire/issues/206
