### ISSUE TITLE
Wire uses excessive amount of CPU while idle.

### ISSUE THREAD

**Issue by YellowOnion** [wireapp/wire-desktop#3338] opened 2019-12-09 02:31 UTC
Version 3.11.3259
Wire for Web Version 2019.11.26.1327
Windows 10
Which antivirus software do you have installed: None

What steps will reproduce the problem?
Open app
Do not minimize to tray

What is the expected result?
Low CPU usage like every other app doing nothing.

What is the actual result?

Excessive CPU usage of 3%

Please provide any additional information below. Attach a screenshot if possible.

![image](https://user-images.githubusercontent.com/364160/70402244-a0e57e80-1a97-11ea-8bc9-e28054bdd65d.png)

Another electron app Discord uses only 0.3% CPU and has far more features, and things going on in it's UI but doesn't eat so much CPU while idle.

The excessive CPU usage disappears when you minimize to tray.

And before anyone says it's only ~3%, Windows and Intel have phased out C3 states for "always online" style power savings, denying the CPU C1 and C2 state will drain batteries a lot quicker on highly portable devices.

**Comment by ffflorian** [comment] 2019-12-09 09:14
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/2507.

**Closed by ffflorian** 2019-12-09 09:14 UTC
