### ISSUE TITLE
Ubuntu 17.04: tray icon disappears

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire-desktop#575] opened 2017-04-14 11:29 UTC
After updating Ubuntu to 17.04 (on 2 PCs) there is no longer the wire tray icon available.

This was a problem earlier. See #22.

`libappindicator1` is installed.

**Comment by ConorIA** [comment] 2017-04-15 14:28
Dupe of #574.

**Closed** 2017-04-18 13:00 UTC
