### ISSUE TITLE
Certutils verification failed for app.wire.com

### ISSUE THREAD

**Issue by jensome101** [wireapp/wire-desktop#881] opened 2017-08-15 18:48 UTC
Wire Version: 2.15.2751
OS: Linux, Debian 9 (Jessie)
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Start Wire from a terminal
2. Look at terminal messages

What is the expected result?
Wire should connect to app.wire.com after successful verification of certificates.

What happens instead?

Wire displays the message: ¨YOUR CONNECTION IS NOT PRIVATE. LEARN MORE¨

Pressing on ¨Learn more will open a browser without displaying anything¨

When started from a terminal the following error message appears (twice):

Certutils verification failed for app.wire.com: false is false
Certutils verification failed for app.wire.com: false is false

**Comment by jphebus** [comment] 2017-08-15 18:55
This may be a duplicate of #851, but I am not sure; it may be a separate issue. I will also post my results here, as well.

I am experiencing the same problem on Debian 9.1 with all updates running wire-desktop version 2.15.2751 from the https://wire-app.wire.com/linux/debian stable main repository. The error: "Certutils verification failed for app.wire.com: false is false" is echoed to the console twice and the "YOUR CONNECTION IS NOT PRIVATE. LEARN MORE" message is displayed in the application.

I thought maybe it was a TLS certificate issue on app.wire.com, but I tried reading from https://app.wire.com/ using wget, curl, and Google Chrome to be absolutely sure, and there were not certificate errors reported. All applications connected and pulled data from https://app.wire.com/ successfully.

So, this appears to be a problem specific to the wire-desktop application or that application's interoperability with Wire server(s).

**Comment by justinnichols** [comment] 2017-08-15 19:25
I don't think it's the same issue.  I had the issue in #851 and a uninstall, wipe of the ~/.config/wire folder, and a reinstall fixed it.  This issue just happened today out of the blue while my wire-desktop app was running (both Linux and Windows, on separate Internet connections).

**Comment by Termuellinator** [comment] 2017-08-15 19:30
glad anybody else has this problem - been trying to figure it out for 2 hours now.
For me too, out of the blue, wire desktop went to the "YOUR CONNECTION IS NOT PRIVATE" Page.
I'm on Manjaro and got Wire installed via AUR.

**Comment by PortableStick** [comment] 2017-08-15 19:36
Same problem here, latest macOS.  Can anyone tell me where the configuration files are?  I don't have `~/.config/wire`.

**Comment by teller** [comment] 2017-08-15 20:24
Hi all, we had an issue with a misconfigured server which was causing the error message. Got fixed around 40 minutes ago.

Sincere apologies from the team for the interruption.

**Closed** 2017-08-15 20:25 UTC

**Comment by leonelwilliams** [comment] 2017-08-15 20:37
Out of curiosity, what was the misconfiguration?

**Comment by raphaelrobert** [comment] 2017-08-16 08:04
Wire uses strict certificate pinning on the client-side. There was a certificate change yesterday. While the new certificate was fine as such, it was unknown to the clients and lead to the error message you saw.
