### ISSUE TITLE
[Regression] Mac: Dark mode preference is no longer preserved.

### ISSUE THREAD

**Issue by toonn** [wireapp/wire-desktop#5008] opened 2021-05-13 08:04 UTC
Wire version: 3.25.4095 
Wire for web version: 2021.05.10.14.51
Operating system: macOS 10.13.6
Which antivirus software do you have installed: None.

What steps will reproduce the problem?

1.  Enable dark mode in preferences->options.
2.  Quit the app.
3. Open the app.

What is the expected result?

Dark mode option is still on.

What is the actual result?

When the app is opened again the theme is light and the dark mode setting is toggled off.

Please provide any additional information below. Attach a screenshot if possible.

This used to work fine in 3.24.4059 so I was a little puzzled the changelog for 3.25.4095 mentioned fixing it and seemingly actually breaking it.

**Comment by ffflorian** [comment] 2021-05-17 13:21
Duplicate of https://github.com/wireapp/wire-desktop/issues/5006.

**Closed by ffflorian** 2021-05-17 13:21 UTC
