### ISSUE TITLE
Cannot login to WireDesktop.

### ISSUE THREAD

**Issue by andysalay** [wireapp/wire-desktop#2968] opened 2019-08-21 18:03 UTC
Wire version: 3.10.3138
Wire for web version: 2019.08.21.1333
Operating system: Linux Mint 19.2
Which antivirus software do you have installed: none

What steps will reproduce the problem?

    Update from previous Wire version
    Restart Wire

What is the expected result?
 Login normally.

What is the actual result?

If I try to log in the progress bar shows fetching something, fetching events,
for a moment.
Then login screen with empty input boxes appears again.

**Comment by yellowtapemeasure** [comment] 2019-08-21 18:33
Version 3.10.3138
Wire for Web Version 2019.08.21.1333
OS: Windoze 10
Which antivirus software do you have installed: Sophos Endpoint Security and Control 11.0.15 UTM
What steps will reproduce the problem? 
Update from previous Wire version
Restart Wire
What is the expected result?
Login normally.

What is the actual result?

If I try to log in the progress bar shows fetching something, fetching events,
for a moment.
Then login screen with empty input boxes appears again.

**Comment by ffflorian** [comment] 2019-08-22 06:08
Duplicate of #2967. Let's continue there.

**Closed by ffflorian** 2019-08-22 06:08 UTC
