### ISSUE TITLE
Got logged out for no reason v3.9.2928

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#2457] opened 2019-04-07 17:15 UTC
Completely out of nowhere, no crash, no updates. ![image](https://user-images.githubusercontent.com/388716/55687094-ecf38880-5936-11e9-9552-6294e85e9cc9.png)

I logged in again and history loaded fine.

**Comment by ffflorian** [comment] 2019-04-08 08:06
Duplicate of https://github.com/wireapp/wire-desktop/issues/2100

**Closed by ffflorian** 2019-04-08 08:06 UTC
