### ISSUE TITLE
Name devices

### ISSUE THREAD

**Issue by Post-Scriptum06** [wireapp/wire-desktop#374] opened 2017-01-28 17:33 UTC
Hello,
Is it possible to add the ability to add a personal name of the active devices?
(For example I have Wire install on two W10 PC, one on Surface and one on desktop, on the menu the both call (Wire for Windows))

Thanks :)

**Comment by ffflorian** [comment] 2017-01-28 20:38
Duplicate of https://github.com/wireapp/wire-webapp/issues/313.

**Closed** 2017-01-29 14:36 UTC
Labels: Feature Request
