### ISSUE TITLE
High CPU on W10

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire-desktop#3393] opened 2019-12-25 10:17 UTC
Wire version: 3.11.3259
Wire for web version: 2019.11.26.1327
Operating system: Windows 10 1909
Which antivirus software do you have installed: Default W10

What steps will reproduce the problem?

1.  I have a relatively high CPU usage ~25%, even on battery. I believe this should be lower, especially if there is no communication ongoing. 
2. Also, shouldn't be the process already 64bit?

What is the expected result?

Optimized CPU usage, when needed.

![image](https://user-images.githubusercontent.com/10846169/71442814-d3ce7a00-2707-11ea-9f41-a82ebb7744d6.png)

**Comment by ffflorian** [comment] 2020-01-02 09:37
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/2507

**Closed by ffflorian** 2020-01-02 09:37 UTC
