### ISSUE TITLE
Add support for a SOCKS5 proxy from the really beginning start of application (using TOR or other)

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-desktop#660] opened 2017-06-02 17:30 UTC
Please add a support for a SOCKS5 proxy from the really beginning start of the application. This can be used for a common SOCKS-proxy and to configure to use secure TOR connection as a SOCKS5 proxy.

It is actual not only on Windows platform, but Linux and others, i.e. on all desktop clients. This maybe configured in any advanced way, if required (if you do not want to make UI difficult), like start with arguments of command line or something. Just for advanced users. The most important thing: it must use SOCKS5 proxy for all connections, from really start (any DNS requests, all other).

**Comment by mythsunwind** [comment] 2017-06-06 10:04
Closing this as duplicate of #85

**Closed by mythsunwind** 2017-06-06 10:04 UTC

**Comment by ConorIA** [comment] 2017-06-07 00:52
Do the default electron flags not work for this? I never tested them, but my comment on never got a reply.

**Comment by mythsunwind** [comment] 2017-11-22 09:49
We recently added the instructions on how to connect through a proxy server on Wire desktop:
https://support.wire.com/hc/en-us/articles/115005697189-How-I-can-connect-through-a-proxy-server-on-desktop-
