### ISSUE TITLE
Ressource usage

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3169] opened 2019-10-29 23:57 UTC
![image](https://user-images.githubusercontent.com/388716/67818090-54655700-fa86-11e9-9435-c384436c52ed.png)

High CPU, High ram

**Comment by ffflorian** [comment] 2019-10-30 10:37
Duplicate of https://github.com/wireapp/wire-desktop/issues/2993

**Closed by ffflorian** 2019-10-30 10:37 UTC
