### ISSUE TITLE
Did the latest update for the Linux desktop app break it?

### ISSUE THREAD

**Issue by ArmitageShanks** [wireapp/wire-desktop#2055] opened 2019-01-02 22:07 UTC
Wire version: Wire for Linux Desktop, latest version. Cant check which version that is since that is the issue... 
system: Ubuntu Mate 18.04 LTS 
Which antivirus software do you have installed: No antivirus

What steps will reproduce the problem?

1.  Start Wire

What is the expected result?
A functional window with conversations and contacts.

What is the actual result?
A blank Wire window where only the menu bar is visible yet not functional.

**Comment by mi-gri** [comment] 2019-01-02 22:39
Confirmed. Same problem here (Linux Mint 19).

**Comment by unequalized** [comment] 2019-01-02 23:18
Same problem with MacOS 10.13.6. Blank screen except for sidebar, but it is non-functional and drop down menus on the Finder don't work either.

**Comment by scmorrison** [comment] 2019-01-03 02:35
Same problem on Debian sid

**Comment by owlbrudder** [comment] 2019-01-03 05:47
I have a Wire window with the usual bar down the left side, but none of my contacts appear there. The menus across the top work OK.
Fedora 29, Gnome 3.30.2, wire-3.5.2881-x86_64.AppImage

**Comment by owlbrudder** [comment] 2019-01-03 05:59
Reverting to wire-3.3.2872-x86_64.AppImage did not solve my problems, which are the same as the others.

**Comment by dceonline** [comment] 2019-01-03 07:15
Same here, Ubuntu 14.04, Wire 2.17.2813
Got a message for update, after updating only a white window appears.

**Comment by dceonline** [comment] 2019-01-03 08:02
well, seems i found a way to fix it.
First i tried reinstalling wire, but that didn' t work.
So i closed wire, cleaned the ~/.cache directory in my home-dir and restarted the app. that work for me, wire came back with all windows.

you may also try to only delete ~/.cache/fontconfig and/or ~/.cache/mozilla.

**Comment by owlbrudder** [comment] 2019-01-03 08:08
Interesting, dceonline. Why would fontconfig and/or mozilla affect the Desktop application? Weird. I had already reverted to the previous version, so restored ~/.config/Wire from backup and everything came back to life.

**Comment by ffflorian** [comment] 2019-01-03 09:10
@dceonline 
> Got a message for update, after updating only a white window appears.

Which kind of message did you get? A banner at the top?

> Wire 2.17.2813

Are you still using this version? It is over a year old and likely not working correctly anymore.

**Comment by mi-gri** [comment] 2019-01-03 09:35
> So i closed wire, cleaned the ~/.cache directory in my home-dir and restarted the app. that work for me, wire came back with all windows.
> 
> you may also try to only delete ~/.cache/fontconfig and/or ~/.cache/mozilla.

Neither worked for me.

**Comment by ffflorian** [comment] 2019-01-03 09:36
To all affected: Please update to the latest version of Wire Desktop and delete the `~/.cache` directory.
Seems like our browser detection failed to recognize your old browser version and thus just a white page appears.

**Comment by ffflorian** [comment] 2019-01-03 09:36
@mi-gri 
Which version of Wire Desktop are you using?

**Comment by mi-gri** [comment] 2019-01-03 09:52
> @mi-gri
> Which version of Wire Desktop are you using?

> Confirmed. Same problem here (Linux Mint 19, Wire-Desktop 3.2.2840).

**Comment by owlbrudder** [comment] 2019-01-03 22:56
ffflorian, which contents of ~/.cache need to be deleted? I have a long list of content in my `/.cache - see attached. I'm uncomfortable about zapping the lot as you may imagine!   "8-)
[cachelist.txt](https://github.com/wireapp/wire-desktop/files/2725542/cachelist.txt)

**Comment by owlbrudder** [comment] 2019-01-04 01:04
My solution which works for me:

- Restore .config/Wire from backup
- cp -r .config.Wire .config/Wire_good
- Start wire-3.5.2881-x86_64.AppImage, which comes up empty.
- Close wire-3.5.2881-x86_64.AppImage
- cp -rf .config/Wire_good .config/Wire
- Start wire-3.5.2881-x86_64.AppImage - everything works again!

YMMV

**Comment by multiflexi** [comment] 2019-01-04 08:17
I had same issue and I noticed the version reported is quite old, around 3.2. So I installed new .deb version from here but that did run at all, did not show anything, the AppImage is the same. Tried remove --purge and reinstall, no luck.

**Comment by ArmitageShanks** [comment] 2019-01-04 20:30
> To all affected: Please update to the latest version of Wire Desktop and delete the `~/.cache` directory.
> Seems like our browser detection failed to recognize your old browser version and thus just a white page appears.

What happens if I delete the `~/.cache` directory? I will not lose data for Wire or other apps?

**Comment by verbal007** [comment] 2019-01-05 18:07
Confirmed this issue on Manjaro 18.0.2.

Deleted .cache did not fix the issue.

Attempted to un-install and re-install but seems the AUR build for wire-desktop is now broken.  :\

Anyone else out there on Manjaro who is reading and hasn't yet updated, DON'T UPGRADE YET.

**Comment by Abnaxos** [comment] 2019-01-07 09:53
Same here, OpenSUSE 15.0.

Deleting both ~/.cache and ~/.config/Wire didn't help, blank window persists.

**Comment by bytefray** [comment] 2019-01-07 23:36
Same here. Gentoo.

Deleting both directories didn't help, still have a blank window.

**Comment by owlbrudder** [comment] 2019-01-07 23:57
If on Linux, close Wire, restore a recently-working version of
.config/Wire (a directory) from backup, the re-open Wire. It should be
working - it does for me. YMMV.

**Comment by next-mad-hatter** [comment] 2019-01-08 12:20
Same with wire-desktop 3.0.2816 (on Slackware).  Purging ~/.cache and moving ~/.config/Wire had no effect.

**Comment by ebym** [comment] 2019-01-09 17:31
Same with Mint 17.3, wire-desktop 3.0.2816, 32bit. I get a white screen, menus don't do much except "Quit" and "About". Tried deleting .config/Wire and restored from Backup. Not working.

**Comment by fermulator** [comment] 2019-01-22 03:32
I had same issue, a full re-install via AppImage download did the trick ;/ (which is annoying); see #2114

**Comment by verbal007** [comment] 2019-01-27 17:43
Reporting in for Manjaro 18.  The current `wire-desktop` AUR is still undergoing some fixes, but the `wire-desktop-git` AUR built just fine, and resolved this blank window issue for me. My problem is <SOLVED>

**Comment by ffflorian** [comment] 2019-05-15 09:16
This should be fixed by now. If not, feel free to comment and I'll reopen.

**Closed by ffflorian** 2019-05-15 09:16 UTC
Labels: platform: Linux, platform: macOS, type: fix 🛠

**Comment by ArmitageShanks** [comment] 2019-05-15 20:51
Just a question, how do I update without losing my data/chats?
I can't update through the app since the window isn't functional?
