### ISSUE TITLE
[Feature Request] Share desktop Control

### ISSUE THREAD

**Issue by Sethox** [wireapp/wire-desktop#2552] opened 2019-04-28 12:10 UTC
If you have more than one desktops active (not virtual desktops, actual panels/screens desktops active) you share it all.

Obviously that's okey, but it would be nice to control it per desktop or all (by default or what not).
The reason could be for a person that uses more screens, than 3 screens or more, it might be hard to share that (for the observer to see what's being shared).

**Comment by ffflorian** [comment] 2019-04-29 08:10
Duplicate of https://github.com/wireapp/wire-desktop/issues/228 and duplicate of https://github.com/wireapp/wire-desktop/issues/676

**Closed by ffflorian** 2019-04-29 08:10 UTC
Labels: comp: screen-sharing, type: feature-request ✨

**Comment by mitquinn** [comment] 2019-06-03 20:10
The last ticket #676 was from 2017?

Is there any hope of revisiting for this functionality?

**Comment by ffflorian** [comment] 2020-05-19 13:03
Fixed in https://github.com/wireapp/wire-webapp/pull/8848
