### ISSUE TITLE
Wire no longer starts up

### ISSUE THREAD

**Issue by Aranad** [wireapp/wire-desktop#2051] opened 2019-01-01 13:56 UTC
Wire 3.5.2881 64bit deb or AppImage was working perfectly but has stopped working without any upgrade or anything having occurred.

Now it doesn't start up, I just get the empty progress bar as shown in the attached screen shot. If I delete the Wire dir to start from scratch, it does the same thing but without any avatar icon showing. Some menu items such as help and quit work.

I've tried running some of the older AppImages instead but all are giving the same result. It seems as if something must have changed on the server.

![screenshot from 2019-01-01 11-48-10](https://user-images.githubusercontent.com/1755922/50573491-1642cc80-0dbc-11e9-95e9-0e18463ff40c.png)

**Comment by Aranad** [comment] 2019-01-01 15:07
I worked out a way to get it going! The add account button works, you can remove your account, add a new one and sign in again when this happens.

**Comment by ffflorian** [comment] 2019-01-02 16:53
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/1961, since @Aranad commented there, too :slightly_smiling_face:

**Closed by ffflorian** 2019-01-02 16:53 UTC
Labels: platform: Linux
