### ISSUE TITLE
Connection without microphone to enable screen share

### ISSUE THREAD

**Issue by nowayoutPL** [wireapp/wire-desktop#3709] opened 2020-03-23 10:19 UTC
Wire version: 3.15.3551
Wire for web version: 2020.03.03.1405
Operating system: Windows 10

I tried to use the **screen sharing** feature on my desktop PC and found a bug. When I click on the **handset** icon to initiate the connection and have access to the screen share icon, nothing happened.
The chat window only showed message: You connected. There was no waiting call window or message - the connection was not established. When I tried to make the same connection from the laptop (the same people and computers were involved in the connection) I could make a connection normally. I didn't know what was going on until I connected the microphone to the desktop computer and could make a connection with it. 

✕ Desktop (no mic) --- > Laptop (mic)
✓ Laptop   (mic)       --- > Desktop (no mic)

It turns out that if the computer making the connection does not have a microphone installed trying to establish the connection causes an error without any message. Connection from the other side is normally possible.
**Suggestion:** 
enable connection without a microphone - this would be preferred if someone wants to use desktop sharing and communicate via chat
The second option is at least to inform the user that the connection requires the presence of a microphone - not all computers have microphones.

**Comment by mythsunwind** [comment] 2020-03-25 09:47
We are aware of this issue and have several other users asking for being able to make calls without a microphone. We are looking into solutions for this.

**Comment by Archive5** [comment] 2020-04-26 04:25
https://github.com/wireapp/wire-webapp/issues/7018

**Comment by ffflorian** [comment] 2020-08-18 12:16
Closing as duplicate of https://github.com/wireapp/wire-webapp/issues/7018.

**Closed by ffflorian** 2020-08-18 12:16 UTC
Labels: comp: calling, type: bug / fix 🐞
