### ISSUE TITLE
High CPU usage. 

### ISSUE THREAD

**Issue by chmol** [wireapp/wire-desktop#135] opened 2016-11-01 12:40 UTC
Hi,

I started using the app yesterday and noticed a really high cpu usage  with the 2.11.2666 build on arch linux. This issue might be linked with the macOS battery ones : https://github.com/wireapp/wire-desktop/issues/122

![nov01-13 32 46](https://cloud.githubusercontent.com/assets/8171862/19889948/26d2f384-a038-11e6-8a10-a4637653d019.png)

**Comment by markjes** [comment] 2016-11-01 16:15
Same here on 2.11.2666.
![screenshot_2016-11-01_17-53-22](https://cloud.githubusercontent.com/assets/5973448/19896951/c9e0e3da-a05e-11e6-9947-148d15f009fc.png)
![screenshot_2016-11-01_17-53-54](https://cloud.githubusercontent.com/assets/5973448/19896955/cdf1b18e-a05e-11e6-853a-e998ccfb5b78.png)

**Comment by herrmannplatz** [comment] 2016-11-02 13:29
Thanks for the help. So this was when the app was idling. Or was it doing anything specific. Running a call, displaying a gif or processing incoming messages?

**Comment by markjes** [comment] 2016-11-02 19:11
When i start the app is taking a lot of ram and cpu and after that displaying gif's.

**Comment by chmol** [comment] 2016-11-03 16:50
I checked again, it's on idle but gif are present in the conversations. 
If I close the window, the app is still running in background  ( i think) the usage goes to less than 5 percent. 

Hope it helps.

**Comment by DCxDemo** [comment] 2016-11-16 22:25
is 7-10% cpu load during a call on i7-2600 considered normal?

**Comment by lunarthegrey** [comment] 2016-11-17 20:07
I have noticed high CPU usage on Ubuntu 14.04. I was doing a video call and it was using nearly 50% of my CPU.

**Comment by nfind** [comment] 2016-12-07 20:03
Hi! 
I also noticed a "high" CPU usage in idle of Wire, approximate 16-18%. I use Mac OS X 10.11.6 and here it is not the process of the Wire.app itself, the load is produced by a separate process called "Wire helper".  What does this extra process in the background, constantly?

**Comment by nfind** [comment] 2016-12-17 11:17
Update: Suddenly the process "Wire helper" stops to "eat up" the CPU…

**Comment by maximbaz** [comment] 2017-01-10 14:58
I also see Wire using ~15% CPU when it is idling. However this bug reproduces only when _certain_ conversations are open. In other words, select one conversation, switch to another app and do something else for a minute, then observe the CPU usage of Wire process and notice that it is constantly ~15%. Select another conversation, do something else for a minute and observe 0% CPU usage of Wire process.

I don't see any obvious connection between the conversations that do and don't produce high CPU usage: 
- it's not a matter of having gifs (I have one conversation where the CPU usage is high and yet there are no gifs)
- it's not a matter of total history size (I have one conversation with definitely a large history, and yet the bug does not reproduce for it).

And as someone else pointed out, close Wire window and CPU usage drops to 0%, for any conversation.

**Comment by nfind** [comment] 2017-01-10 15:59
Yeah, I have to revise my last post. It started again using constantly about 15% CPU usage. But as I got no feedback, I switched now to an app called [Franz](http://meetfranz.com). Which can handle a lot more messengers and with no uncertain CPU usage.

**Comment by maximbaz** [comment] 2017-01-10 20:52
@nfind you may want to monitor your CPU usage further, I don't think using Franz will solve the issue. In fact I don't think this is a `wire-desktop` issue at all, I think it belongs to `wire-webapp`, and so whatever client you use (let it be `wire-desktop`, Franz or a browser) you will experience this issue. Maybe just like in my case, depending on which conversation is opened the bug is or is not reproducible for you, or maybe there is some other condition.

I can actually reproduce this in Google Chrome. 

I think this is a severe issue, I was wondering lately why the battery on my laptop degraded so quickly, until I stumbled on this bug. I can say now that it is true, my battery lives considerably longer with having Wire window closed.

**Comment by herrmannplatz** [comment] 2017-01-11 10:17
First thanks for all the input and comment. I finally had some time to debug. There are several issues that (might) cause this:

- GIFs (play on user action should improve this)
- offscreen css animations (realized that the image placeholder causes some repainting)

Reworking the image loading a bit, so i will try to knock down these issue.

**Comment by geigi** [comment] 2017-01-30 13:15
Awesome that you may found some things that could cause this issue!
Some observations from me, running 10.12.3 with Wire 2.11.2686:
When I open a conversation Wire Helper consumes about 10-15% CPU in idle, it doesn't matter whether Wire is freshly opened or not. But when I hide Wire with CMD + H the CPU usage drops to 0% immediately. 
Another observation: The bigger the wire window the higher the CPU usage is for me. On a 1080p screen with a maximised Wire window it stays at around 20-25%.

**Comment by anatoli26** [comment] 2017-02-19 07:57
Same here (Ubuntu 16.04, Wire 2.11.2685). Only some windows cause 20-25% CPU usage (no GIFs or animations). When the main window is closed, the CPU usage is below 2-3%.

**Comment by karlo12** [comment] 2017-02-25 11:03
I've just noticed a massive CPU usage during calls. I'm using Kubuntu 16.10 and the AppImage v2.11.2722. When making a video call I got 90% CPU usage cannot use a browser anymore, for example. The person which I called had a similar high usage, using Windows 10. I think we both have an intel i5-4300U CPU. We did not send any GIFs. When idling -without any calling going on- everything seems to be fine.

**Comment by rbieb** [comment] 2017-04-20 20:10
Can confirm the issues with wire helper. Wire helper constantly uses 30% cpu (as reported by activity monitor on macOS) while the wire app is in foreground. Would be really nice if this could be fixed.

**Comment by maximbaz** [comment] 2017-04-22 00:14
I was trying to investigate a little bit, here's what I found:

- It definitely depends on the currently active conversation. Right now I have several conversations, opening some of them results in constant 30% CPU usage, opening others immediately drops to 0% CPU usage.
- It doesn't seem to depend on the content in the currently visible area. One high-cpu conversation has only text in the visible area, while another conversation uses 0% CPU and has youtube video and a link as the last messages.
- It doesn't seem to depend on the age of the last message in the conversation, e.g. one of the conversations that had no messages for the past 2 days is a high-cpu consuming one.
- Chrome DevTools show nothing significant on the Rendering and Animation tabs.
- Chrome DevTools is showing a difference on the JS CPU profiling, but it is a cryptic one:
    - This is a ~10 sec recording when a high-cpu conversation is opened:
    ![image](https://cloud.githubusercontent.com/assets/1177900/25299582/cf0ce09c-2700-11e7-8b4c-0a3d3915a162.png)
    - And this is a ~10 sec recording when a low-cpu conversation is opened:
    ![image](https://cloud.githubusercontent.com/assets/1177900/25299576/bf11e728-2700-11e7-9f33-9cc3e34f88c9.png)

Notice the difference in the something called `(program)`, on a high-cpu conversation this takes 2 out of 10 seconds to compute, while on a low-cpu conversation it consumes almost nothing.

Google search tells me that `(program)` is a chrome instance itself, but this CPU usage is clearly induced by Wire somehow, as different active conversations produce different results.

Does anyone have any suggestions on how to dig deeper and learn what actually is happening during those 2 out of 10 seconds?

**Comment by maximbaz** [comment] 2017-04-22 16:24
Figured it out, it is a `three-dots` animation running above the images until they are loaded that makes some conversations consuming lots and lots of CPU. To check for yourself, just start wire with `--devtools`, open a high-consuming conversation and execute `jQuery(".image-placeholder-icon").remove()` in the console - the CPU usage will immediately drop to 0%.

The bug is filed as https://github.com/wireapp/wire-webapp/issues/1112, let's hope we get a quick hotfix - I can't stand seeing my laptop's battery dying so quickly because of Wire.

**Comment by anatoli26** [comment] 2017-04-22 19:45
Maxim, great analysis! I can confirm that `jQuery(".image-placeholder-icon").remove()` in devtools console reduces CPU usage to almost 0 (Ubuntu 16.04, latest Wire 2.13.2739 from the PPA) in every chat you execute it.

**Comment by rbieb** [comment] 2017-04-22 19:58
Can confirm as well. This fixes the issue. Awesome analysis maxim!

**Comment by ffflorian** [comment] 2017-04-24 09:35
Thanks everyone for reporting!

Closing this since the issue was fixed in https://github.com/wireapp/wire-webapp/pull/1115 and will be included in the next release. :slightly_smiling_face: Feel free to reopen if the issue persists.

**Closed by ffflorian** 2017-04-24 09:35 UTC

**Comment by rkarlsba** [comment] 2020-07-12 22:37
If I leave wire running for some time, it does the same. Fans start whining and I have to restart wire to fix it. This is on macOS 10.15.4 with wire 3.18.3728

**Comment by wwmbes** [comment] 2022-09-14 08:16
Version 3.24.2939 on Ubuntu 20.04 does the same.
**Refer to two nmon screeenshots attached, taken 1 minute apart below.** Then when wire is shut down from the front-end ... (see blow the first two screenshots)
![Screenshot from 2022-09-14 09-58-53](https://user-images.githubusercontent.com/5073954/190096591-644ca4c0-b267-4c4c-8e08-2fcd4cb3e69b.png)
![Screenshot from 2022-09-14 09-59-11](https://user-images.githubusercontent.com/5073954/190096600-64cbe9e6-3ada-40f1-aad3-4e3953abfbb6.png)
**Then when wire is shut down from the front-end, it leaves three processes running in the background. See nmon screen shots, 1 minute apart, below**:
![Screenshot from 2022-09-14 10-10-45](https://user-images.githubusercontent.com/5073954/190099553-25e822d4-216e-44c5-b9de-299954bb2c47.png)
![Screenshot from 2022-09-14 10-11-10](https://user-images.githubusercontent.com/5073954/190099558-913ea832-4bda-4732-93f2-5891c063004c.png)
