### ISSUE TITLE
Support hiding the left panel

### ISSUE THREAD

**Issue by orta** [wireapp/wire-desktop#298] opened 2016-12-28 23:09 UTC
Like everyone else, I enjoy looking at my face - but having it there all taking up a quarter of my laptop screen can be a tad distracting. Have I overlooked the ability to hide it?

**Comment by helenakos** [comment] 2016-12-30 12:47
@orta Thanks for the feedback. We're aware and our design team is working on a solution for this.

**Comment by rbieb** [comment] 2017-01-11 18:01
Resizing would probably be the best solution, that would include the possibility of hiding it.

**Comment by MichielBijl** [comment] 2017-01-22 14:35
I don’t necessarily need to hide it, but changing the background to be, I don’t know, blank or something would be a very good start.

**Comment by anatoli26** [comment] 2017-02-19 07:12
Being able to set a profile picture and a different backgrounds for the left panel and the chat area would be great.

**Comment by Simplenuity** [comment] 2017-02-26 01:53
#445

**Comment by qazip** [comment] 2017-03-03 15:03
I also want the ability to resize (and hide) the left panel. I'm using a 2nd screen in portrait and Wire-Desktop doesn't fit, at all.

**Comment by schlichtanders** [comment] 2017-05-05 07:44
copied from #39:

Suggestions:
1. make the border between contacts and chat windowpart draggable to decrease/increase the size of the panes respectively (increasing the one, decreasing the other)
1. add a button like a common menu three-bar sign &Xi;  to the *top-left* which can hide/unhide the contacts-pane alltogether. If hidden, there is of course the question where to put &Xi; and I think it is still best to leave it *top-left* and place the search symbol right next to it
1. dragging the border between the panes (from 1.) such far as to hide the contactspane completely, the contactspane could switch to the &Xi; presentation (from 2.)

**Comment by schlichtanders** [comment] 2017-05-05 07:45
The same would be great to have for the web-application https://app.wire.com  https://www.github.com/wireapp/wire-webapp

**Comment by anatoli26** [comment] 2017-05-05 08:10
To solve "the question where to put Ξ", the solution may be not to completely hide the left panel, but to reduce it to the current width of contact avatars, i.e. the panel would show only the avatars and on top of the list would be the sandwich button. You can see a similar behavior/layout at http://www.di.fm.

The avatars (when the left panel is minimized) could show overlays with unread message counters.

**Comment by helenakos** [comment] 2017-05-08 14:21
Many thanks for the feedback. Regarding the background picture, there will be a version coming out soon in which the background picture is blurred out with a fresh design of the conversation list. This will solve the issues related to always looking at your own image. Ideas such as draggable chat window are very welcomed, however currently we have different priorities within the team and with limited design and development resources we won't have the time to support this change in the upcoming months. Therefore closing this issue.

**Closed by helenakos** 2017-05-08 14:21 UTC
Labels: Feature Request

**Comment by schlichtanders** [comment] 2017-05-08 14:27
for the potential one being interested in implementing this feature
herself/himself:
what would have to be done roughly for this draggable border to get
implemented?
- where to start looking?
- what not to forget?
- something else?

**Comment by lipis** [comment] 2017-05-08 14:31
I would say approval by designers :) Who are currently busy with something else :D

**Comment by helenakos** [comment] 2017-05-08 14:46
@schlichtanders You can check out https://github.com/wireapp/wire-webapp/pull/543 for a similar discussion.
