### ISSUE TITLE
Poor notifications unter Linux (Kubuntu)

### ISSUE THREAD

**Issue by paulsommer** [wireapp/wire-desktop#449] opened 2017-02-19 15:50 UTC
When I use wire under Kubuntu 16.04 I always miss messages because they are not properly signaled.
When I receive a message I hear an ultra low volume "click" and a message appears for a couple of seconds at the lower right. That's all. 
If I'm not at the PC in that moment I'll miss that message.
The click is really veeery low noise. I can't hear it if there's any other noise like radio, traffic outside or whatever. The volume slider in Pulseaudio is at 100% for Wire.

I would like wire to restore the window (when minimized) or  bring it to front (otherwise) upon message receive, so I'll notice it when I'm back at the desk.
I would also love to be able to choose a different sound / volume in the settings.

I'm currently using wire 2.11.2685 on Kubuntu Xenial 64bit

**Comment by anatoli26** [comment] 2017-02-22 08:14
Duplicate of #252

**Comment by lipis** [comment] 2017-02-24 16:24
Should work now in  2.11.2722 https://wire.com/download/

**Closed by lipis** 2017-02-24 16:24 UTC
Labels: Feature Request, Linux
