### ISSUE TITLE
Wire Web/Desktop constantly uses CPU during idle

### ISSUE THREAD

**Issue by rawlife56** [wireapp/wire-desktop#2507] opened 2019-04-15 21:02 UTC
Wire version: 3.9.2895 <Check the About dialog>
Wire for web version: 2019.04.10.0901<Check the About dialog>
Operating system: Linux (Arch-KDE) 

What steps will reproduce the problem?

1. Open Wire
2. Close and let it sit in the tray
3. Check the constant CPU usage of 2-4% with some spikes upto 10% in regular intervals without any incoming messages.

What is the expected result?
No CPU usage and minimal CPU usage in intervals if needed. 

What is the actual result?
Constant CPU usage of 2-4% with some spikes upto 10% in regular interval

Workarounds I tried-
Searched across issues and found few like [these](https://github.com/wireapp/wire-desktop/issues/135) which are quite old & irrelevant. 

Strange findings- 
1. It also happens in the web app. Tried in Firefox browser and [Rambox](https://github.com/TheGoddessInari/rambox) with the clean chats, both resulted in the same constant CPU usage. 
2. Few specific conversations result in constant 10% CPU usage. (including idle.)

_A note about screenshots_ - Every Electron instance running in this pic is from Wire. This doesn't happen with other electron applications. I took extreme care before capturing these screenshots verifying it's only the Wire running and also did check whether killing wire would terminate these processes too. Yes, they did terminate if I kill wire. 

![Screenshot_20190416_015407](https://user-images.githubusercontent.com/42450674/56164702-e1ffbe80-5fee-11e9-91a2-7c3b57e4c3c9.png)'
![Screenshot_20190416_021201](https://user-images.githubusercontent.com/42450674/56164719-edeb8080-5fee-11e9-99f0-88c37465694c.png)

**Comment by fermulator** [comment] 2019-04-20 16:39
This is a regression I think, I am observing new significant degrade in battery life on notebook for simpler reasons.

```
 ps wauxxx | grep wire-desktop | sort -rnk3 | head -1
fermula+  9107  8.4  3.7 12519836 296416 ?     Sl   12:20   1:05 /tmp/.mount_wire-3UoYI5y/wire-desktop --type=renderer --no-sandbox --enable-features=SharedArrayBuffer --disable-gpu-compositing --service-pipe-token=17888110652218941075 --lang=en-GB --app-path=/tmp/.mount_wire-3UoYI5y/resources/app --node-integration=false --webview-tag=true --no-sandbox --preload=/tmp/.mount_wire-3UoYI5y/resources/app/renderer/static/webview-preload.js --background-color=#fff --guest-instance-id=1 --enable-blink-features --disable-blink-features --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=17888110652218941075 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```
Here's the startup sequence: (it takes a VERY long time to "settle CPU")
```
$ while true; do ps wauxxx | grep wire-desktop | sort -rnk3 | head -1 | awk '{print $3}'; sleep 1; done
0.0
0.0
0.0
19.0   <-- open wire-desktop
40.5
47.0
31.0
30.0
58.0
55.0
50.6
50.7
48.2
55.5
63.5
64.2
60.3
57.2
53.5
50.3
47.5
45.1
42.9
41.0
39.2
37.6
36.1
34.7
33.5
32.4
31.3
29.2
28.4
27.7
26.9
26.2
25.6
25.0
24.4
23.8
23.3
22.8
22.4
22.0
21.6
21.2
20.9
20.5
20.2
19.9
19.6
19.3
19.0
18.7
18.4
^[18.9
19.3
19.0
18.8
18.5
18.3
18.1
17.8
17.3
17.2
17.0
16.9
16.7
16.5
16.3
16.2
16.0
15.9
15.7
15.5
15.4
15.3
15.1
15.0
14.9
14.8
14.6
14.5
14.4
14.3
14.2
14.1
14.0
13.9
13.8
13.7
(got tired of waiting)
```

Here's an "idle" scenario (after its been open for hours or whatever)
```
$ while true; do ps wauxxx | grep wire-desktop | sort -rnk3 | head -1 | awk '{print $3}'; sleep 1; done
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.4
8.5
8.5
8.5
8.5
8.5
8.6
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
8.8
0.0    <--- exit wire
0.0
0.0
```

Sys Info:
```
Linux Mint 18.3 Sylvia
4.15.0-43-generic
mate-desktop 1.18.0-1+sonya
```

Wire is *wire desktop: 3.5.2881 2019.04.10.0901* (run out of appimage)

**Comment by fermulator** [comment] 2019-04-20 16:42
I also report similar CPU vs. chat behaviour.  It doesn't seem to matter which conversation the app sits idle in.

**Comment by fermulator** [comment] 2019-04-27 14:03
Any recent changes to suspect? I scanned briefly but not sure exactly when the regression was introduced so not sure how far back to go.

**Comment by wilhelmy** [comment] 2019-05-22 09:36
Same here, it constantly eats 9% CPU. I've quit it for now, this is unreasonable.

**Comment by Mikaela** [comment] 2019-05-24 07:47
I think I am also seeing this on Debian Testing with Wire 3.9.2895 (from Flatpak). I also find that `--no-sandbox` strange, why is it there?

![Screenshot from 2019-05-24 10-43-06](https://user-images.githubusercontent.com/831184/58311147-d7a7c000-7df7-11e9-976b-45db4846864a.png)

I hope that the root on the bottom is due to using Flatpak and it's related to Flatpak's own sandboxing instead of Wire actually running as root.

**Comment by tomleb** [comment] 2019-06-15 16:14
I am having the same issue.
Getting 15% cpu usage when idle and 75% cpu usage when focusing the application.

**Comment by fermulator** [comment] 2019-07-15 21:33
I checked on my wife's Win10 system and the same idle CPU is happening there too :/
(so not a linux/container specific problem? can anyone else corroborate this?)

**Comment by fermulator** [comment] 2019-07-22 12:17
fwiw, I contacted support directly and they refuse to help; only "professional" tier users get support, and they don't support linux at all; (WTF) - if any1 here pays for a Pro license, please contact them and reference this

**Comment by fermulator** [comment] 2019-07-22 12:26
I scanned past all the commits and stumbled over this

https://github.com/wireapp/wire-desktop/commit/104bdd3ba0ba8dc1c296ed646e670a95f3e72bb4

how to disable hardware acceleration in the AppImage? hmmm

**Comment by vladimiry** [comment] 2019-07-22 12:30
> how to disable hardware acceleration in the AppImage? hmmm

Try passing some of the following CLI args (or all of them):
- disable-gpu
- disable-software-rasterizer

**Comment by fermulator** [comment] 2019-07-22 12:34
Thx @vladimiry , 'twas simple enough.  Tried both, had no affect on the CPU for this issue (as kind of expected), so that delivery is not related to this performance regression.

**Comment by vladimiry** [comment] 2019-07-22 12:36
@fermulator there are a lot more [switches](https://peter.sh/experiments/chromium-command-line-switches/) you could also try :)

**Comment by fermulator** [comment] 2019-07-24 11:56
Open to trying to isolate, but that is too wide a spread.  Really would appreciate maintainer/dev direction here on potential ways to root cause.

**Comment by vomout** [comment] 2019-08-27 11:17
Wire Helper: constant 6% CPU, Wire: constant 3% CPU. (MacOS Mojave)

**Comment by Mikaela** [comment] 2019-08-27 17:39
Adding to https://github.com/wireapp/wire-desktop/issues/2507#issuecomment-495508674, I have since learned that Chromium's sandbox doesn't work in Flatpak currently, so it has to be disabled.

I have also since [enabled full MDS mitigation (`mds=full,nosmt`)](https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html) which disables hyperthreading and makes two CPU cores "disappear" (as they apparently never existed in physical reality) so I think this may be affecting me more.

**Comment by AJolly** [comment] 2019-09-30 02:01
Similar high CPU utilization in Windows.

**Comment by fermulator** [comment] 2019-10-12 14:57
How do we get wire staff to pay attention here? 6 months later ... is this never going to be fixed?

**Comment by ffflorian** [comment] 2019-11-29 10:16
Hi folks, trying to nail this issue down.

First thing: 2-4 % background CPU usage is normal for Electron apps. A spike to 10 % might come from incoming messages or outrunning timed messages.

Further questions:
- did it help disabling GPU for Wire?
- did you see other Electron apps with this behavior? If yes, which Electron version were they using?

**Comment by wilhelmy** [comment] 2019-11-30 02:40
One of the Wire processes in htop eats 8% CPU here, whereas Signal (also electron) eats about 2%.

Didn't try disabling GPU. This is on Linux fwiw (like in the original bug report).

**Comment by AJolly** [comment] 2019-11-30 22:30
It's eating about 7% on a overclocked 4.7ghz 10 core machine.  Signal is at 0%.  The larger your wire history, the worst it gets.

**Comment by fermulator** [comment] 2019-12-14 12:55
@ffflorian my posting earlier shows the results w/ GPU disabled

Indeed I have also used other Electron apps (i.e. Slack) and it does not suffer from this.
Further to @wilhelmy stated, for me too if Wire is open, CPU is hot, fan spins - _**it is degrading our battery and hardware**_.

**Comment by fermulator** [comment] 2019-12-14 12:59
Per noted in #3338, interestingly it _IS_ true if you minimize to tray the excessive CPU is reduced (suggesting indeed we have an aggressive refresh/activity graphically that gets paused while minimized).
* 5-8% while open in background idle (no active messages)
* ~2% while minimized (no active messages)

**Comment by wilhelmy** [comment] 2020-01-11 20:17
2% when idle is still high, to be honest. Signal is at 0.6% when idle with the window still open.

**Comment by electronstudio** [comment] 2020-01-16 23:22
On MacOS I'm seeing >6% when the window is open and 3% even when the window is closed.  No way is that acceptable for an app that shouldn't be doing anything except waiting for message to arrive.

**Comment by fermulator** [comment] 2020-01-18 16:07
Is anyone affected a paying premium subscriber or do they know someone? - Based on what I've seen here in terms of issue activity, and the response from wire-support -- they will not fix this unless complaints are received from paying customers.

**Comment by Shnub** [comment] 2020-01-20 12:40
I also experience constant idle CPU usage of around 9 % (little variation). This is on macOS 10.14.6. It was not an issue under macOS 10.13.6 with the same version(s) of Wire three days ago. In fact, in the ~ 2 years I've been using Wire for macOS, idle CPU usage was always practically nil, as it should be. Now it is by far the most CPU-hungry of all background processes on my system, eating more CPU time on average than kernel_task and considerably draining the battery on my laptop. I have to stop running the app for now and only launch when I get a notification on my phone. Not good.

The issue was almost certainly triggered by the macOS system update from 10.13 to 10.14 – no Wire update took place in the meantime.

The CPU usage is mostly from two helper processes:

![Screen Shot 2020-01-20 at 13 13 33](https://user-images.githubusercontent.com/29605254/72725816-0d6b9700-3b87-11ea-8503-bfdc2d612a23.png)

It doesn't matter which conversation is selected or if the Wire window is active, frontmost, closed, or hidden.

I notice that all mention of the free, personal-use version of Wire has been removed from the official website. I hope this and the ongoing neglect for this issue does not indicate that the free version is being phased out. Security and usage-wise, it is the only messenger app that accomodates my needs.

Wire Version 3.12.3490
Wire for Web Version 2020.01.13.1120

**Comment by sumyungguy** [comment] 2020-01-22 15:39
I'm seeing the same thing described by @Shnub above, a recent increase to about 15% constant CPU core use on a MacBook Air. It happened around the same time that I updated to macOS 10.14 Mojave. In the previous years I've used it, it has been less than 5% when idle. This is probably a different issue than the other reports about Windows/Linux.

It's no longer practical to keep it running in the background as I always have. It has a noticeable impact when watching video, web browsing, etc.,  and causes extra heat, fan activity, and battery drain.

![screenshot_335](https://user-images.githubusercontent.com/5410893/72898792-08dce500-3d25-11ea-841c-6c819f0f39c8.png)

Also echoing the other comment - you could have left the free account as a great alternative to What's App, Telegram, SMS, iMessage, etc., for client and customer communications by and between freelancers and small businesses, while using that as a freemium lead-in to paid "pro" Slack-like accounts for internal teams that you're emphasizing now. I used to recommend a free Wire account as the best way for business customers to contact me. But since it changed to "personal-use only", and now has been removed from the website, it just looks unprofessional for me to recommend it, even though there's nothing technically changed with Wire and the fact that it doesn't require people to give you their personal phone number is a major advantage. Such a shame, and hard to understand why you would prohibit freelancers and small businesses - the very people you want to attract as paying customers - from using Wire as an alternative to other free messaging apps.

Version 3.12.3490
Wire for Web Version 2020.01.13.1120

**Comment by widben** [comment] 2020-03-26 08:42
Can confirm the issue, Wire is using way too much CPU in closed state:
<img width="280" alt="Bildschirmfoto 2020-03-26 um 09 34 17" src="https://user-images.githubusercontent.com/12762663/77626611-e4300400-6f45-11ea-9227-10f6a87b4ba8.png">

MacOS 10.15.4
Wire 3.15.3621

**Comment by TheCapsLock** [comment] 2020-03-30 13:55
even in normal use ; using full cpu quad cores bringing an heavy load on the machine is not normal at all.

**Comment by fermulator** [comment] 2020-04-22 01:13
@ffflorian - anything the community can do to help assist/isolate the problem? -- based on the above historical trail, we clearly have a regression here, enough users have reported the issue, across multiple platforms;

**Comment by tech189** [comment] 2020-06-23 19:51
Still an issue with Wire 3.18.3728 on macOS 10.15.5. I'm getting about 10% CPU usage while idle. For comparison, Caprine (which is another electron app - a web wrapper for Facebook Messenger) uses almost no CPU while idle (between 0.1% and 1%).

**Comment by bennyn** [comment] 2020-07-10 08:00
@tech189 do you know which Electron version is used in your Caprine installation?

We will check if an update to [Electron v9.1.0](https://www.electronjs.org/releases/stable#release-notes-for-v910) will bring better performance since it includes a fix for [intermittent 100% CPU usage on macOS](https://github.com/electron/electron/pull/24415).

**Comment by tech189** [comment] 2020-07-11 12:25
Caprine currently uses Electron v9.0.5
Thanks for looking into it!

**Comment by fermulator** [comment] 2020-08-15 18:10
1. how can we check which version of electron is in place for a given version of wire messenger?
2. is there an expected update to leverage a newer version of electron that _MIGHT_ fix the issue?

**Comment by ffflorian** [comment] 2020-08-18 12:27
@fermulator 
> 1. how can we check which version of electron is in place for a given version of wire messenger?

Please see the [Builds](https://github.com/wireapp/wire-desktop/wiki/Builds) page for that.

**Comment by cachapa** [comment] 2020-09-02 08:29
I don't think this is an Electron issue, since I'm seeing the same on the web app (Chrome 85.0.4183.83 - latest stable)

**Comment by EchedeyLR** [comment] 2020-09-02 14:17
Electron ≈ Chromium ≈ Chrome (with certain differences). 

Could be tested the webapp in other web browser to see that is not general in Chromium?

**Comment by cachapa** [comment] 2020-09-05 07:35
Tested in Firefox. Took a while because Wire doesn't import history in new clients and I had to wait until the conversation was long enough.

I don't quite understand Firefox's task manager, but in a conversation with probably a couple thousand messages the "energy impact" is constantly hovering around "medium" and the tab is consuming over 200MB. On Chrome I see about the same behaviour, with longer conversations reaching almost 1GB of memory usage.

What I've also noticed is that the performance tends to get worse the more you chat, to the point that the UI starts getting unresponsive and I need to reload the entire web app.

**Comment by catap** [comment] 2020-09-15 21:47
Possibly one more lead: `Wire Helper (Renderer)` going to 40%-50% of CPU usage when it was on background (just running) on macOS.

When I've switched to wire, it has this on the screen:
<img width="495" alt="Screenshot 2020-09-15 at 23 45 59" src="https://user-images.githubusercontent.com/37775/93268644-cf725180-f7ad-11ea-82b8-a5956a119d4c.png">

Restart helped.

**Comment by vith** [comment] 2020-12-31 10:21
On Arch Linux/Gnome, Wire's `/usr/lib/electron10/electron --type=gpu-process` uses about 10% of a CPU core constantly for me, and one of the `/usr/lib/electron10/electron --type=renderer` processes uses about 30%.

Restarting doesn't help.

Doesn't matter what's being displayed in the window: an empty chat, the settings screen, or a group chat with a long message history, the CPU usage remains the same. Closing the Wire window but leaving it running as an AppIndicator doesn't reduce the CPU usage either.

Installed package is `community/wire-desktop 3.21.2936-2`.

**Comment by vith** [comment] 2020-12-31 10:32
Running `wire-desktop --devtools` and using the profiler I see nothing under Event Log, nothing under Call Tree. There's just a small amount of GPU activity, around 1% of the time. Not sure what else to check to diagnose this.

![image](https://user-images.githubusercontent.com/3265539/103406584-77443d00-4b5b-11eb-988d-b9d16e88bda8.png)

**Comment by charlag** [comment] 2021-01-08 10:08
Ubuntu 20.04.1 LTS
Wire Version 3.21.2936
wire windows closed, only in backgrond
constant CPU churn of 6-8% from proces with --type=renderer and a little (2%) from from --type=gpu-process.
Our own app based on Electron 10 while in foreground does not do this

**Comment by liskin** [comment] 2021-01-13 13:59
Also still happens with app.wire.com in latest Chrome on Linux. No other tab consumes as much CPU as Wire.
Any chance this will ever get resolved?

**Comment by fermulator** [comment] 2021-01-17 14:43
If April 2021 hits, it will have been 2 years since this perf regression bug, being unfixed.  If not fixed by then I'll be abandoning wire.

**Comment by alien2003** [comment] 2021-02-25 10:04
You are lucky getting just 6-7%, I get 13-15% on my Surface Pro 6

**Comment by xavim86** [comment] 2021-03-16 08:33
Hi, I am having the same issue in Linux. I am experimenting with the command cpulimit trying to see if there is a reasonable way to idle-ize and de-idle-ize the wire-desktop processes ... I am not an expert at all. So far I could list the processes involved using

ps aux | grep wire-desktop | awk '{print $3,$2}' | sort -r

then I pick the PID of the process with largest cpu load from the previous command and do

cpulimit -l 1 -p PID_OF_THE_PROCESS

It seems to calm down the cpu load. It's not a nice mitigation ... but maybe someone could improve this further? Thanks in advance!

**Comment by fermulator** [comment] 2021-03-27 13:31
@xavim86 - note that if you CPU limit ... while this might help stave off the idle CPU, would this not stifle wire from performing "actual work" while in use? (i.e. voice or video calls)

**Comment by xavim86** [comment] 2021-03-27 18:00
@fermulator - yes, you are right. My current (horrible) way to deal with Wire cpu load is to have one script to idle-ize processes names "wire-desktop" using cpulimit and let it run 'limited' for the notification icon to change thus indicating that some new message arrived or somebody calling me. Then, I de-idle-ize Wire with another script that kills the involved "cpulimit" process so that the program runs smoothly again. This is not practical at all and does not make me happy! I wish this would be solved in future updates of Wire Desktop...

**Comment by fermulator** [comment] 2021-03-27 20:01
Given the age of this issue, and lack of official wire developer or support commitments to fix, I have no reason to believe it will ever be fixed at this point. :(

**Comment by dbquarrel** [comment] 2021-04-09 04:03
I started complaining about CPU use in 2017. 

Nothing will ever be done.

Look how hilarious this looks on an M1 Macbook.

<img width="271" alt="Screen Shot 2021-04-08 at 23 51 40" src="https://user-images.githubusercontent.com/5317653/114126591-bacee580-98c6-11eb-9d89-055aefc8f86b.png">

Wire is doing nothing and just burning that CPU. It's the renderer helper processes, just sitting there I guess drawing the same data forever in a loop with 30+ threads each.

I just can't get through my head that someone has actually designed this to behave like this.

<img width="761" alt="Screen Shot 2021-04-08 at 23 58 32" src="https://user-images.githubusercontent.com/5317653/114126697-f5388280-98c6-11eb-89a7-49c1e859a69a.png">

**Comment by liskin** [comment] 2021-05-06 15:19
Inspired by https://github.com/wireapp/wire-desktop/issues/2239#issuecomment-831812239 I took a closer look and indeed there is a loading spinner somewhere in the page, hidden inside a couple of `display: none` elements yet repainted at 60 fps nonetheless`. I ended up with this uBlock filter:

```
app.wire.com##div.loading-wrapper:remove()
```

Now the https://app.wire.com/ browser window consumes much fewer resources. Unfortunately this doesn't really help the poor people who choose to run Wire in Electron as there's no uBlock in there. :-/

Anyway, I'll try reporting the issue to Chromium, so maybe this will get fixed in a couple years.

**Comment by bennycode** [comment] 2021-05-06 16:10
@liskin the `div class="loading-wrapper"` comes from our web app code. How much CPU does it save you when you remove it?

**Comment by liskin** [comment] 2021-05-06 16:39
> @liskin the `div class="loading-wrapper"` comes from our web app code. How much CPU does it save you when you remove it?

Before I removed it, the tab would consistently consume 10 % CPU on my i7-7500U. When I add that uBlock filter, it stays at zero.

**Comment by liskin** [comment] 2021-05-06 21:11
Reported to Chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=1206425
Also seems to be reproducible in Firefox so it'll be better to fix this on Wire's side as well.

**Comment by dbquarrel** [comment] 2021-05-07 09:12
@liskin do you know if it's been reported to Mozilla yet? They are pretty responsive about bugs and would want to know. If not I'll try to do a report over there.

**Comment by liskin** [comment] 2021-05-07 10:10
@dbquarrel I didn't look there, feel free to go ahead. :-)

**Comment by Siguza** [comment] 2021-06-25 10:07
Getting the same behaviour on an M1 Mac mini, macOS 11.4. The Wire Renderer constantly has 10-20% CPU usage, even when idle and off-screen (i.e. on a "desktop space" other than the current one).  
I sampled the process, not sure if this tells you anything:

[Sample of Wire Helper (Renderer).txt](https://github.com/wireapp/wire-desktop/files/6715422/Sample.of.Wire.Helper.Renderer.txt)

**Comment by JMoVS** [comment] 2021-06-29 20:26
> I started complaining about CPU use in 2017.
> 
> Nothing will ever be done.
> 
> Look how hilarious this looks on an M1 Macbook.
> 
> <img alt="Screen Shot 2021-04-08 at 23 51 40" width="271" src="https://user-images.githubusercontent.com/5317653/114126591-bacee580-98c6-11eb-9d89-055aefc8f86b.png">
> 
> Wire is doing nothing and just burning that CPU. It's the renderer helper processes, just sitting there I guess drawing the same data forever in a loop with 30+ threads each.
> 
> I just can't get through my head that someone has actually designed this to behave like this.
> 
> <img alt="Screen Shot 2021-04-08 at 23 58 32" width="761" src="https://user-images.githubusercontent.com/5317653/114126697-f5388280-98c6-11eb-89a7-49c1e859a69a.png">

same for me. Whereas slack was a hog in the past, I don't see slack anymore in my list - Wire on the other hand...

**Comment by JMoVS** [comment] 2021-06-29 20:27
does a debug archive/log help?

**Comment by jviide** [comment] 2021-07-06 15:13
Pull request #5164 attempts to remove the LoadingSpinner contents from the DOM after the spinner has faded out. It seems to lower the idle CPU usage considerably - at least on Macs.

**Comment by alien2003** [comment] 2021-12-20 13:01
> I suspect that part of the issue on M1 Macs is that it's running under Rosetta 2. I have NO CLUE why there is no Universal Binary / Apple Silicon binary of Wire Desktop when we're nearly in 2022.

We don't have even Linux ARM version. ARM Linux runs on a lot of hardware (laptops, tablets, smartphones, single board computers) and you are talking about Mac ARM which is niche of niches - only few laptop models from single vendor

**Comment by dbquarrel** [comment] 2021-12-20 14:42
On Mon, Dec 20, 2021, at 15:01, alien2003 wrote:
> 
> 
>> I suspect that part of the issue on M1 Macs is that it's running under Rosetta 2. I have NO CLUE why there is no Universal Binary / Apple Silicon binary of Wire Desktop when we're nearly in 2022.
>> 
> We don't have even Linux ARM version. ARM Linux runs on a lot of hardware (laptops, tablets, smartphones, single board computers) and you are talking about Mac ARM which is niche of niches - only few laptop models from single vendor
> 

To clear some misconceptions in your note here:

1. all of Apple's laptops are now M1 ARM: (Air and Pro models both, Apple will no longer make Intel based laptops)
2. Apple's Mac Mini has transitioned to M1 ARM
3. Apple's iMac 24" has transitioned to M1 ARM

This leaves Apple with two Intel based products, the Mac Pro (if you want to use the word "niche" there must be only one of these sold for every thousand laptops or something like this), and the iMac 27" (which will almost certainly follow the 24" during the next product refresh).

So, reality is that M1 ARM is the default architecture for Apple at this point. Treating Intel as the default architecture is wrong and calling it "niche of niches" is misinformed.

Lastly, compiling for M1 is literally adding a compiler flag. 

Wire's development group is traditionally looking at the wrong thing, for instance it took the community four years of hassling the developers about CPU use being extremely high while the app is idle, to have these responses: 

a. silence
b. we will look at it at some point
c. closing threads

It took the user community to solve the CPU issues in the end. 

If now the community is going to have to educate about what Apple is using for their hardware, we're into another four years of this. 

That said, Rosetta 2 is extremely effective though a native compile is much, much better. Having recompiled all of my own code for M1 simply by checking off a box in Xcode and having no problem, with some of my code authored as far back as 1988 in C, and using a mix of C, C++, Objective-C and Swift, I find there is little to no excuse for anyone to claim that M1 is niche of niches and so acceptable to ignore. Furthermore the architecture is already supported via iPhone builds which have existed since the beginning.

Ignoring M1 is not the approach of Adobe, Microsoft, etc. 

Yes we will always have an ocean of Intel based products that will always be everyone's focus, but the point here is that M1 is more important than is claimed and should not be ignored.

**Comment by fluffypony** [comment] 2021-12-20 14:55
@dbquarrel nailed it. In addition, Wire *already* has an ARM build for Apple devices - the iOS version! In fact, they could opt-in to the iPad version being available in the M1 App Store, without needing to recompile or do anything, but instead have chosen to purposely disable this. Some apps (eg. Plex) allow for both the macOS and iOS versions to be used on Apple Silicon whilst they're transitioning to a single, unified application.

![Screen Shot 2021-12-20 at 8 51 05 AM](https://user-images.githubusercontent.com/1944293/146786135-8f98b7ac-8834-413a-b379-d8dd4ac44c69.png)

In addition to it largely being a compiler flag, all of the fundamental bits and pieces for Wire Desktop have had M1 support for a significant period of time *precisely because it is not a "niche of niches"*. Electron, for instance, has [had M1 support since November 2020](https://www.electronjs.org/blog/electron-11-0), 5 major releases ago.

**Comment by fluffypony** [comment] 2022-04-11 14:33
New version is FINALLY in the App Store with the patch for this, THREE YEARS after it was patched.

Still not a universal binary, but at least it's no longer hammering at battery life for no real reason.

![Screen Shot 2022-04-11 at 9 32 41 AM](https://user-images.githubusercontent.com/1944293/162762438-00069614-ae24-4199-90e3-7e59f15c9f46.png)

**Comment by fermulator** [comment] 2022-10-01 13:52
Can confirm; Issue is now resolved.
```
Version 3.28.2946
Wire for Web Version 2022.09.20.08.41

$ cat ~/.local/share/applications/appimagekit-Etcher.desktop 
[Desktop Entry]
Name=Etcher
Exec="/home/fermulator/Downloads/etcher-1.2.1-x86_64.AppImage" %U
Comment=Flash OS images to SD cards and USB drives, safely and easily.
Icon=/home/fermulator/.cache/thumbnails/normal/56218a9af4d359f0706ac6229ef4fb02.png
Type=Application
X-Desktop-File-Install-Version=0.22
X-AppImage-Comment=Generated by ./bin//etcher-electron.wrapper
TryExec=/home/fermulator/Downloads/etcher-1.2.1-x86_64.AppImage

```

**Closed** 2022-11-02 12:56 UTC
Labels: platform: macOS 🍏, platform: Windows 🖼️, platform: Linux 🐧

**Comment by rauferd** [comment] 2025-05-17 09:51
My installation of wire uses up to **47%** of memory when idling!

wire-desktop version 3.40.3718
wire web version 2025.05.14.10.47.48
AVS version 10.0.43

installed from the Debian package repository https://wire-app.wire.com/linux/debian on Debian 13 Trixie, linux kernel 6.12.27-amd64.

Should I open a new issue report? Or can this issue be re-activated?
Which additional information should I provide?
