### ISSUE TITLE
wire can't connect, unable to deliver messages

### ISSUE THREAD

**Issue by jacknifejeds** [wireapp/wire-desktop#2816] opened 2019-07-09 22:18 UTC
Wire version: 3.9.2928
Wire for web version: 
Operating system: windows 7

Which antivirus software do you have installed: AVG

What steps will reproduce the problem?

1.  it starts a few seconds after i open wire

What is the expected result?

to connect to wire

What is the actual result?

it doesn't connect

Please provide any additional information below. Attach a screenshot if possible.
i've tried rebooting my computer several times, uninstalling and reinstalling wire, and using the browser version instead. it will not connect. i'm getting notifications for messages via the app on my phone but they will not go through on my app. i have a VPN but i've tried turning it off, rebooting, and then restarting wire and it still won't connect. this issues has been happening for 2 days. it just keeps giving me this message no matter how many times i restart wire. 

![Screenshot_1](https://user-images.githubusercontent.com/52722370/60926793-ac791300-a275-11e9-80e9-2d19930c1b05.png)

**Comment by ffflorian** [comment] 2019-07-10 11:37
@jacknifejeds did you try restarting Wire after disabling your VPN?

**Comment by jacknifejeds** [comment] 2019-07-10 11:45
yes, i’ve tried completely disabling the vpn, restarting my computer, and then restarting wire again. still nothing. i also think it’s strange that when i uninstall wire and then reinstall it it logs me right back in. it’s like it’s not completely uninstalling but i cant find any remaining files on my computer when i do.

**Comment by jacknifejeds** [comment] 2019-07-10 11:46
the web version is having the exact same issue for me.

**Comment by ffflorian** [comment] 2019-07-10 11:49
> it’s like it’s not completely uninstalling but i cant find any remaining files on my computer when i do.

Your profile data is saved to `C:\Users\[username]\AppData\Wire`. You can delete this directory safely if you like to remove your profile data.

You are saying that the webapp has exact the same issue, but the blue bar which is visible in your first post is only available in the desktop version.

So what happens when you try opening https://app.wire.com in your browser?

**Comment by jacknifejeds** [comment] 2019-07-10 11:53
it gives me that same blue message. i cannot receive any messages on it. i know i’m getting them because i’m getting the notifications on my app. 

when i uninstall wire that folder isn’t there. but when i reinstall it, even after restarting my computer, it auto logs me in.

**Comment by jacknifejeds** [comment] 2019-07-10 11:57
![Screenshot_1](https://user-images.githubusercontent.com/52722370/60967278-4a0d2a80-a2e8-11e9-8cda-e792fbf86357.png)
here are both blue messages, together

**Comment by ffflorian** [comment] 2019-07-10 12:39
@jacknifejeds Once the bar appears in the browser, can you please press F12, click on "Console" and post a screenshot of the console output?

**Comment by jacknifejeds** [comment] 2019-07-10 12:43
![Screenshot_1](https://user-images.githubusercontent.com/52722370/60969930-d28ec980-a2ee-11e9-9ba2-40e700363067.png)

**Comment by ffflorian** [comment] 2019-07-10 12:56
@jacknifejeds are you using a firewall? If yes, try disabling it. If not, then something is wrong with your internet connection.

**Comment by jacknifejeds** [comment] 2019-07-10 12:59
i use AVG, my internet is working fine besides this. is there a way to disable the firewall just for wire?

**Comment by jacknifejeds** [comment] 2019-07-10 13:06
ok i disabled windows firewall and it still gives me the same blue message.

**Comment by jacknifejeds** [comment] 2019-07-10 13:28
well for some reason it seems to be working on firefox now. it's still not working on chrome but at least it's working somewhere!

**Comment by ffflorian** [comment] 2019-07-10 13:41
@jacknifejeds good to hear that it's working now. I can't reproduce the issue in Chrome so I'm going to close this one for now. We will continue investigating what went wrong here. Have a good day!

**Closed by ffflorian** 2019-07-10 13:41 UTC
Labels: platform: Windows

**Comment by jacknifejeds** [comment] 2019-07-10 13:43
thank you!
