### ISSUE TITLE
Feature request : Allow image paste from clipboard

### ISSUE THREAD

**Issue by relyd** [wireapp/wire-desktop#132] opened 2016-10-31 19:41 UTC
Pasting image data is currently unavailable (Win client).
Electron clipboard API : 
[Clipboard API](https://github.com/electron/electron/blob/master/docs/api/clipboard.md)

Thanks for considering

**Comment by helenakos** [comment] 2016-11-01 16:29
Thanks @relyd , this is one of the most wanted features on Wire for Web as well.

**Comment by ConorIA** [comment] 2016-11-04 23:26
Re: previous comment: https://github.com/wireapp/wire-webapp/issues/236

**Comment by lipis** [comment] 2016-11-05 08:40
Thanks @ConorIA I'll close it as duplicate of wireapp/wire-webapp#236

**Closed by lipis** 2016-11-05 08:40 UTC
Labels: Feature Request
