### ISSUE TITLE
Not loading any message history when not internet connected.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#2216] opened 2019-02-16 21:32 UTC
To reproduce : Disconect from internet, Launch Wire.

![image](https://user-images.githubusercontent.com/388716/52905455-6ceb5500-3208-11e9-968c-4c3c1fef788a.png)

**Comment by ffflorian** [comment] 2019-02-18 21:14
Duplicate of https://github.com/wireapp/wire-desktop/issues/40

**Closed by ffflorian** 2019-02-18 21:14 UTC
