### ISSUE TITLE
Add Emoji icon

### ISSUE THREAD

**Issue by DragonzMaster** [wireapp/wire-desktop#119] opened 2016-10-26 19:44 UTC
I think it is not comfortable to open touch keyboard every time i want to send an emoji 😞 (sometimes it is not working)
so plz can you just add an icon that display emoji and choose it to be added to conversation.

**Comment by lipis** [comment] 2016-11-04 12:51
I will close that as duplicate of this one: https://github.com/wireapp/wire-webapp/issues/408

**Closed by lipis** 2016-11-04 12:51 UTC
Labels: Feature Request
