### ISSUE TITLE
No desktop notification or badge on macOS upon a new message when inactive

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#2072] opened 2019-01-05 15:58 UTC
When the main window of Wire is open but not active (that is, it's not closed but it's hidden by another application), and the user receives a new message, it gets neither a desktop notification nor a badge in its icon in the dock. This is a regression because it worked less than 3 weeks ago.

Wire version: 3.9.2943
Wire for web version: 2019.04.10.0901
Operating system: macOS Mojave 10.14.4
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Open Wire on macOS;
2.  Switch to another application so that the window of Wire is not active (visible);
3.  Have somebody else send you a message.

What is the expected result?

A desktop notification informs about the new message and the badge in the application icon in the dock is updated with the number of unread messages.

What is the actual result?

Only a sound is heard for the new message.

**Comment by ddobrev** [comment] 2019-01-07 14:17
Happy New Year and all, and I'm aware I reported this over the weekend but this regression is too horrible to wait any longer. Please at least reply.

**Comment by ddobrev** [comment] 2019-01-15 00:18
You seem not to understand that this regression makes Wire unusable. My friends and I consider switching to Telegram which requires a phone number and has poorer encryption but if this bug remains for long we would have no choice.

**Comment by ddobrev** [comment] 2019-02-01 07:56
With the exception of https://github.com/wireapp/wire-desktop/issues/2140 and the lack of a native client, Wire had worked just fine. Until this. Missing messages is one of the very few critical failures any messenger can have. And Wire has regressed to it. The lack of any replies is outrageous. At least comment if you can reproduce it.

**Comment by ddobrev** [comment] 2019-02-20 18:17
At least tell me to shut up.

**Comment by ddobrev** [comment] 2019-03-22 16:30
Seriously, what's wrong with you? You don't understand simple English? You need a psychiatrist? You're simply lazy and/or stupid? When are you going to realize the lack of reliable notifications hurts not simply the user experience but the actual usefulness - when you lose all of your customers? We're not talking about a fancy font here, you know. You need **me** to tell you what to do, is this it? OK then:
1. Try reproducing it on a Mac;
2. Report here that you have;
3. In case that Gregor fellow who adores closing issues around with no actual resolution is dying to do the same here, at least point me to where in your source code you handle notifications so that I can fix it myself;
4. If any of the above is too difficult for you, just run the bullshit generator at http://pasta.phyrama.com:8083/cgi-bin/live.exe and paste me some retarded marketing blabber about how you have no plans to fix anything around here and you need to therefore close this.

**Comment by marcoconti83** [comment] 2019-03-25 16:15
Hi @ddobrev,

Thanks for reporting the issue. Unfortunately we don't have the capacity to follow all github issues in a timely manner and we are sorry for the slow response on this one.

However, we will not tolerate aggressive behavior and language as seen in your comments and we will take the necessary measures to stop any further verbal abuse if this were to continue.

Going back to the technical issue. Is there any scenario in which the notification is actually displayed, or are you never seeing any notification at all?

**Comment by ddobrev** [comment] 2019-03-25 16:36
@marcoconti83 well, I believe my aggressive behaviour and language has justified itself because it was after it that I got any reaction by you. I wish I hadn't had to employ such tactics, believe me, but after 1 report and 2, I'd even say 3 civil comments yielded no results, it was obvious the best approach didn't work so I had to resort to anything that would.
Now, you have replied after all, so we can try the regular manner once more. I haven't mentioned it explicitly but the other case does work: when Wire's had its window closed, a notification always arrives.

**Comment by epapushev** [comment] 2019-03-25 16:49
Notifications show when the window is closed or minimized. 

No notifications show when the window is open, but covered by other windows and the app is not the active one.

**Comment by marcoconti83** [comment] 2019-03-25 16:52
> @marcoconti83 well, I believe my aggressive behaviour and language has justified itself because it was after it that I got any reaction by you. I wish I hadn't had to employ such tactics, believe me, but after 1 report and 2, I'd even say 3 civil comments yielded no results, it was obvious the best approach didn't work so I had to resort to anything that would.

Hi @ddobrev , just to make it clear, the fact that you use such aggressive language does not in any way alter the priority of the issue on our side and we won't tollerate this kind of interaction any further.

**Comment by marcoconti83** [comment] 2019-03-25 16:53
> Notifications show when the window is closed or minimized.
> 
> No notifications show when the window is open, but covered by other windows and the app is not the active one.

Thanks for clarifying.

**Comment by ddobrev** [comment] 2019-04-08 11:52
@marcoconti83 two more weeks have passed and if there's any change about this issue, it certainly isn't reflected here. So would you mind sharing if there's been any progress or at least success in reproduction?

**Comment by AndyLnd** [comment] 2019-04-15 10:10
Hi @ddobrev, we just tried various scenarios and cannot reproduce this. Can you please tell me which version you are using and if this issue still exists?

**Comment by ddobrev** [comment] 2019-04-15 12:49
@AndyLnd thank you very much for your productive reply, it's the first one I've got here.
I have updated the description, you can see all of my versions there.
I observed some strange behaviour: it started working properly yesterday and today it fails again. A friend reported it fully working the day before yesterday, and yesterday he said there were still occasions he didn't get notifications. He uses the exact same version I do, including the OS.
What else can I do to help out?

**Comment by AndyLnd** [comment] 2019-04-16 08:58
@ddobrev We will keep our eyes peeled for that behaviour. If it happens again and you find a reliable way to reproduce this by any chance, please let us know. We need to be able to reproduce it to fix it.

**Comment by ddobrev** [comment] 2019-04-16 11:49
@AndyLnd thank you for your effort. As surprised as I am that the problem doesn't occur for you, I can no longer provide reliable reproduction. I used to because back when I reported the bug it happened every single time. I'm sorry to say that if Wire's team had reacted back then, you would've now been able to repeat the problem.

**Comment by ddobrev** [comment] 2019-05-05 14:57
@AndyLnd there's something which might help you fix the issue without reproducing it. Even though a notification doesn't always arrive when it should, the "click" sound for a newly received message does. So all you need to do is bind your code for the sound with the code for a notification and you'll have guaranteed they always work in sync. Let me know what you think.

**Comment by ddobrev** [comment] 2019-05-20 20:19
@AndyLnd ? @marcoconti83 ? Anyone? What do you think about my suggestion?

**Comment by ddobrev** [comment] 2019-07-03 12:01
Bewildered as I am that noone besides myself and @epapushev have complained about this, it goes on. I updated yesterday and notifications still don't arrive reliably. By this time I have done even more than reporting the bug and pointing your attention to its significance, I have actually made a more than reasonable suggestion about a possible fix. You haven't even replied. Does Wire have any future at all?

**Comment by marcoconti83** [comment] 2019-07-03 12:09
Hi @ddobrev , 

As @AndyLnd mentioned, we are still not able to reproduce the issue. 

Please also appreciate that we don't have the capacity to work on all reported issues, and we need to prioritize according to various factors, including the number of affected users. However, there's an upside: Wire is an open source project, and anyone from the community can contribute. 

If someone out there is having this issue and is happy to play around with the source code and make a PR, we would be happy to provide insight and answers questions on the code until that bug is addressed.

**Comment by ddobrev** [comment] 2019-07-03 12:21
@marcoconti83 this reply of yours has been the first step towards an actual resolution of this bug in the 6 months since I've reported it. What's sad is that it comes 3 months after [my own very same suggestion](https://github.com/wireapp/wire-desktop/issues/2072#issuecomment-475688077) (**"point me to where in your source code you handle notifications so that I can fix it myself"**).
Oh, well. Yes, I would check your source code to try fixing it myself. I need the locations of your code for notifications and for the sound upon a received message, and also build instructions. A recommendation for an IDE for Electron would be useful too since I haven't worked with it before.

**Comment by marcoconti83** [comment] 2019-07-03 13:25
You can find the build instructions in the README. It's in the root of the repository: https://github.com/wireapp/wire-desktop

@AndyLnd or @ffflorian can later point you to the code that handles notifications

**Comment by ddobrev** [comment] 2019-10-02 18:44
@marcoconti83 @AndyLnd @ffflorian I haven't had the opportunity to check the code myself but I had an observation which might help you. All notifications actually do arrive - they are visible in the Notification Center of macOS. So what most probably happens is that you have some bug in the code which determines whether the main window is focused, or active, which causes the newly received notification to be considered as read. This, in turn, removes the badge from the dock and fails to show a notification at the top right. I've also seen this: the window is visible but inactive, I receive a message and the badge appears for less than a second and then disappears.
I ask that you'd be kind enough to answer me if this information might help you reproduce and fix this.

**Comment by ddobrev** [comment] 2019-11-06 22:38
@marcoconti83 @AndyLnd @ffflorian are we starting this all over again? I gave you a key clue more than a month ago and not even a reply? In case I haven't been clear enough - I have **confirmed** the problem is in the activation of the main window. I have **seen** the notifications in Notification Center. By the way, I have meanwhile upgraded to Catalina and the problem persists – in case you hoped it would fix itself.

**Comment by marcoconti83** [comment] 2019-11-07 13:20
Hi @ddobrev ,
thanks for looking into this, and great job in finding a key clue! I am going to repeat myself and say  that we don't have the capacity to work on all reported issues. However, there's an upside: Wire is an open source project, and anyone from the community can contribute. 

Since you already dug so far, perhaps you'll be able to do an experimental fix in the code and submit a PR? If not, does someone else from the community want to give a shot, following @ddobrev conclusions?

Just to be clear, we appreciate the report and the effort in trying to find the cause, and we acknowledge that this is an issue that needs to be addressed. We will eventually be able to have a look at this ourselves, but the "eventually" might be months, as other more pressing issues and features on our roadmap are preventing us from tackling all issues that are opened.

**Comment by ffflorian** [comment] 2019-12-02 08:39
@ddobrev are you starting the app minimized?

**Comment by ddobrev** [comment] 2019-12-02 10:42
@ffflorian thank you for taking interest in this long standing issue. :) Yes, I do. I don't start it by hand, it's simply a log-in item in macOS (`System Preferences -> Users and Groups -> Login Items`). I think applications start minimized in this case. I have, however, also started it by hand by quitting and starting in again in futile attempts to make notifications appear.

**Comment by ffflorian** [comment] 2019-12-02 10:56
I just created a fix (https://github.com/wireapp/wire-desktop/pull/3315) which might solve the case when the app is not receiving notifications after starting minimized.

However, when you (re)started it manually, notifications should arrive. Are you using a second device with your account (iPhone, other computer, etc.)?

**Comment by ddobrev** [comment] 2019-12-02 11:01
@ffflorian I've tried it twice before on an Android but not at present (by the way, the reason is that it's too hard on the battery because of the web view you host, you should get rid of it). However, I've checked your fix and it is indeed possible that it might help. When you've released the fix and I've tried it for a week or two, I'll let you know about any change in behaviour.

**Comment by ffflorian** [comment] 2019-12-02 11:07
Alright, I'll notify you as soon as it's released.

**Comment by ddobrev** [comment] 2019-12-17 14:02
@ffflorian I keep missing important messages because of this bug, when is the new version expected?

**Comment by ffflorian** [comment] 2020-01-03 10:06
@ddobrev we just released the new version.

**Comment by ddobrev** [comment] 2020-01-03 20:09
@ffflorian I'm sorry to say there's no difference in this regard. May I ask you: do you have people who at least occasionally test on macOS? I'm quite surprised all of you claim not to reproduce it.

**Comment by ffflorian** [comment] 2020-01-04 11:02
@ddobrev are you using the Wire app on mobile at the same time?

**Comment by ddobrev** [comment] 2020-01-04 21:03
@ffflorian everything's been on since the very beginning in August 2017.

**Comment by chriseomi** [comment] 2020-02-14 17:35
Just wanted to say, this notification bug been occurring for me and my friends too. It used to work so definitely a regressionn.

macOS 10.15.3, latest wire etc.

Unfortunately I don't have the skills to submit a patch. Also appreciate the dev team is busy with other things and can't reproduce it.

So yah not expecting much to happen

**Comment by ffflorian** [comment] 2020-08-17 14:34
Hi @ddobrev and @chriseomi, I think this was fixed with https://github.com/wireapp/wire-desktop/pull/4042. Can you check if this issue still exists for you?

**Closed** 2021-03-25 15:18 UTC
Labels: platform: macOS 🍏, type: bug / fix 🐞
