### ISSUE TITLE
No vertical scroll on the screen for all images or links

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#981] opened 2017-09-27 08:46 UTC
Wire Version: 2.15.2750
Wire for Web Version: 2017.09.26.1300
OS: macOS Sierra 10.12.6
Do you have an antivirus software installed: No.

What steps will reproduce the problem?
1. Work with a contact you have sent to or received from at least 20 images or links;
2. Open the searching in messages;
3. Don't type anything;
4. Open the link for seeing all images or links.

What is the expected result?
A vertical scroll appears and scrolling down with the mouse or trackpad works.

What happens instead?
No vertical scroll appears and scrolling down with the mouse or trackpad doesn't work - only the arrow keys help.

**Comment by ffflorian** [comment] 2017-09-27 15:19
I'm pretty sure this is a duplicate of #625.

**Comment by gregor** [comment] 2017-09-27 15:27
I believe the same. Please resize the app width and try again. This is an unfortunate known issue we have not gotten around to fix. Thereby closing this.

**Closed by gregor** 2017-09-27 15:27 UTC
