### ISSUE TITLE
Call stops working after 10 seconds

### ISSUE THREAD

**Issue by Eriton33** [wireapp/wire-desktop#1169] opened 2017-12-16 19:25 UTC
When making a audio call to a friend, the call stops working after 5 to 10 seconds. The Call is still up an running, the timer keeps working and continues to list the duration of the call but the parties cannot hear each other.

Both parties are using Windows 7 and the wire version listed below

Wire version: Version 3.0.2828
Wire for web version:  2017.12.07.1113
Operating system: Windows 7 pro (SP1 with the latest updates)
Which antivirus software do you have installed: none
What steps will reproduce the problem?
1. make a call
2. the other party picks up
3. talks far some time and after 10 seconds the parties cannot hear each other anymore

What is the expected result?

A working audio chat

What is the actual result?

Audio calls not working

**Comment by helgisteinar** [comment] 2018-01-18 02:16
Similar:  Android -> Mac/OS.  Worked for 50 seconds and then one party (Android) could not hear the other.

**Comment by WildYorkies** [comment] 2018-03-30 20:01
I have two friends having this same exact issue. One with Windows 7 and one with Windows 10.

Longest the Windows 7 guy lasted in the voice call was 2.5 minutes. 

Any way we can troubleshoot the reason for getting booted? Is it mismatched bitrates maybe? Or you get booted if the connection loses strength?

**Comment by harmancasvi** [comment] 2018-04-30 04:37
# Similar issue on version 3.0.2828 with Windows 10
The main issue is not voice related, but is triggered while screen sharing is enabled and suddenly it fails and then the call hangs up.
### Tested scenarios
> **OS:** Windows 10 (1709 build 16299.371]) - on both ends.
>**Wire version:** 3.0.2828 (desktop) - on both ends.
#### Scenarios where the issue reproduces (screen sharing fails):
> + VPN on sharer side and no vpn on the other side.`
> + VPN on both sides.
> + No VPN at all on any side an then change of sides while screen sharing in the same call (the viewer becomes sharer).
#### **Scenarios without issue (screen sharing):**
> + No VPN on any side and no change of sides on same call.
> + No VPN on sharer side and no change of sides on same call.

The call stops on sharer side like 10 seconds after screen sharing starts, on the other side it continues the counter and keeps going infinitely.

The VPN used is IPSec w/ PSK on a Mikrotik router with version RouterOS 6.41.2 and corresponding firmware.

Let me know if you have any relevant info or question.

If this issue deserves to be independent, please let me know and I'll create a new one accordingly, I just wrote it here because it seems to me that it could be triggered by the same casue, therefore the issue would end up being the same.

**Comment by gregor** [comment] 2018-06-01 09:40
We have added a call log features option in your account preferences. If you still see these problems please get in touch with our customer support providing them with logs. I am going to close the issue here.

**Closed by gregor** 2018-06-01 09:40 UTC
