### ISSUE TITLE
Red Hat/Centos/Fedora rpm support

### ISSUE THREAD

**Issue by lfarkas** [wireapp/wire-desktop#959] opened 2017-09-21 12:58 UTC
Is there any plan to provide an rpm or dare i provide a spec file for it?

**Comment by ffflorian** [comment] 2017-09-27 15:30
Hi @lfarkas, thanks for asking. For now we don't plan to provide a rpm file. You could either build the app yourself or use the `.AppImage` file.

Closing as duplicate of #799.

**Closed by ffflorian** 2017-09-27 15:30 UTC
Labels: Linux
