### ISSUE TITLE
Video keeps playing after closing wire

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#272] opened 2016-12-13 15:55 UTC
Wire 2.11.2670 (.deb package).
- receive a youtube video
- play it
- close wire (not by clicking "quit wire" in the menu, just click the X)
- the video keeps playing

**Comment by Kasmetski** [comment] 2016-12-23 08:53
I don't know your graphic interface, but in KDE when you click 'X' it's like to click minimize for most of the programs. For me this is a normal behavior.
If I play a song in Amarok (KDE player) and click 'X' it continues to play to music until I stop it or click Quit (Ctrl + Q).

**Comment by ffflorian** [comment] 2017-01-27 10:10
As far as I know, this is intended behaviour - not by Wire, but by most Linux Desktop Managers. By clicking the X, only the window gets closed, not the app.

Try using Ctrl+Q, as @Kasmetski suggested. :slightly_smiling_face:

**Comment by someoneEsle** [comment] 2017-01-27 20:28
But *I do* want the app to remain open in the background, otherwise I can just click "quit" in the menu. I just don't want the video to keep playing. Clicking the X to me means something like "okay, I'm done using wire now, it can go back to listening to notifications". I think every process should be stopped (playing sounds, videos, etc) except for whatever is needed to deliver notifications.

It makes sense that clicking the X on the music player keeps the music playing, because that's the main function of that program and it's something that can be done from the icons tray (doesn't need you to be looking at it). But this is a different app that I think requires a different behavior. That being said I understand this is definitely not a priority for the developers

**Comment by gregor** [comment] 2017-01-27 20:49
Also please keep in mind that people also send music video clips where you actually do want to continue to listen to the music.

**Comment by lipis** [comment] 2017-02-24 16:28
It looks like everything is by design here, so I'll close this one.

**Closed by lipis** 2017-02-24 16:28 UTC
Labels: Bug, Linux
