### ISSUE TITLE
Global hotkey bug ctrl+(1/2/3)

### ISSUE THREAD

**Issue by thisnickwasfree** [wireapp/wire-desktop#2577] opened 2019-05-04 12:57 UTC
Duplicate of this one: https://github.com/wireapp/wire/issues/274

0. Platform is GNU\Linux, some KDE5 soft onboard..
1. Start wire-app .
2. Switch to another workspace.
3. Wait during random time. You may do something: file operations, internet browsing, etc. Not sure, but looks like this time is corresponding with the time of changing status in wire-app or something like this.
4. Open an application which uses global hotckeys ctrl+1/2/3. For example, dolphin file manager.
5. Press a key combination and get no effect.
6. Switch back to a workspace with wire-app and let a wire-app to get focus.
7. Global hotkeys in dolphin work again.
Well, it's a really bad idea to use global hotkeys, that can not be changed or switched off, because it can affect other user's soft.

**Comment by thisnickwasfree** [comment] 2019-07-05 08:05
One more time.
Rewrite please wire-desktop/electron/src/menu/ strings 438 — 454: 

export const registerShortcuts = (): void => {
  // Global mute shortcut
  globalShortcut.register('CmdOrCtrl+Alt+M', () =>
    WindowManager.sendActionToPrimaryWindow(EVENT_TYPE.UI.SYSTEM_MENU, EVENT_TYPE.CONVERSATION.TOGGLE_MUTE),
  );

  // Global account switching shortcut
  const switchAccountShortcut = ['CmdOrCtrl', 'Super'];
  const accountLimit = config.maximumAccounts;
  for (const shortcut of switchAccountShortcut) {
    for (let accountId = 0; accountId < accountLimit; accountId++) {
      globalShortcut.register(`${shortcut}+${accountId + 1}`, () =>
        WindowManager.sendActionToPrimaryWindow(EVENT_TYPE.ACTION.SWITCH_ACCOUNT, accountId),
      );
    }
  }
};

This is serious bug that affects other daily soft like file-browsers. You should not use unchangeable global hotkeys in your application because they can conflict with other hotkeys of de/wm and a user of your application can do nothing in this case .

**Comment by ffflorian** [comment] 2019-07-12 10:23
@thisnickwasfree I can't reproduce your issue on Debian + Gnome. "Wait during random time" also doesn't really help me debugging the issue, sorry.

> Rewrite please wire-desktop/electron/src/menu/ strings 438 — 454:

Why don't you create a PR if you know how to solve it? :slightly_smiling_face:

**Comment by thisnickwasfree** [comment] 2019-07-24 13:09
>Why don't you create a PR if you know how to solve it?

This is not a solution but workaround. I have rebuilded my own copy of wire-desktop so it works without an annoying bug now, but this is not a universal solution: other users can have their own opinion about the cutted off function. And of course I prefer not to rebuild it after any release.

>I can't reproduce your issue on Debian + Gnome.

Does Gnome have ctrl+1,2,3 shortcuts? Are they local or global?

>Wait during random time

As I said before, this can be somehow corresponding with changing wire's status.

Anyway, the bug is in the strings. Even if you can not reproduce it. You are a developer. You should understand what does «global shortcut» mean. It means that this shortcut should work anywhere in user's session having greater priority than «local shortcuts», which works only while their application is in focus. So, according to the code, the fact that you can not reproduce the bug is the bug itself: global shortcuts should work all the time or they are not global. But this behaviour (global hardcoded shortcuts) is not comfortable for users who have their own local shortcuts (which can be default for DE/WM/FM).
So, the easy way is to remove a part of code, the best way is to allow users to change global shortcuts or even switch them off.

**Comment by ffflorian** [comment] 2019-11-04 16:17
This will be fixed in the next release.

**Closed** 2019-11-04 16:17 UTC
Labels: platform: Linux 🐧
