### ISSUE TITLE
[Linux] constant CPU use...

### ISSUE THREAD

**Issue by jdiercks** [wireapp/wire-desktop#607] opened 2017-04-24 19:22 UTC
Wire for Linux 2.11.2685 appears to be using about 16% CPU constantly.

**Comment by ConorIA** [comment] 2017-04-24 19:30
Likely related: #14 #122 #135 #280 #473 
Root cause: https://github.com/wireapp/wire-webapp/issues/1112
and fix: https://github.com/wireapp/wire-webapp/pull/1115

**Comment by ffflorian** [comment] 2017-04-25 10:06
Closing because of duplication.

**Closed by ffflorian** 2017-04-25 10:06 UTC
