### ISSUE TITLE
Won't build on Fedora (aarch64)

### ISSUE THREAD

**Issue by bkeys** [wireapp/wire-desktop#1338] opened 2018-03-13 15:17 UTC
Wire version: Master
Operating system: Fedora 27 (aarch64)
Which antivirus software do you have installed: None.

What steps will reproduce the problem?
1. Clone Wire on an aarch64 machine
2. Run `npm start` at the repo root
3. Get the output mentioned in the results section

What is the expected result?
For it to build/work

What is the actual result?
```
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.7.1
added 63 packages, removed 6 packages and updated 49 packages in 31.939s
[bkeys@localhost wire-desktop]$ npm start
module.js:540
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```
Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ffflorian** [comment] 2018-03-28 08:35
@bkeys any update on this? Did you try reinstalling Node / npm?

**Comment by Britaliope** [comment] 2018-04-11 03:34
Got  the same issue ( Fedora 27 - x86-64 - npm 5.6.0). 

I've solved it removing npm with dnf, then
```
sudo rm -rf /usr/lib/node_modules/
sudo rm -rf /usr/local/lib/node_modules/
sudo rm -rf /usr/local/bin/npm/
 ```
then reinstall npm.

That's clearly a `npm` problem

**Comment by ffflorian** [comment] 2018-05-23 08:26
I'll close this for now. Feel free to reopen if the problem is related to Wire and still exists.

**Closed** 2018-05-23 08:25 UTC
Labels: status: Need more info
