### ISSUE TITLE
Program crashes after update in Windows 7

### ISSUE THREAD

**Issue by bryc** [wireapp/wire-desktop#1933] opened 2018-11-26 04:33 UTC
Wire version: 3.4.2885 - 2018.11.15.1314
Operating system: Win 7 Ultimate SP1.
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Open program
2.  Chat with people, scroll up and down chat, etc. Minimize and return later.
3.  Program will "stop responding" at random and close.

What is the expected result?

No crash should occur (this has not happened before)

What is the actual result?

Crashing occurs, and it takes a good 1-2 minutes to reopen and properly load.

Please provide any additional information below. Attach a screenshot if possible.

There is also an odd delay in sending messages. They stay grey longer than normal and it is not related to connnection issues.

**Comment by ffflorian** [comment] 2018-11-26 15:55
Thanks for reporting @bryc. We are investigating.

**Comment by agolks** [comment] 2018-11-29 07:40
see crashs, too. don't know how to reproduce, though.
wire window just disappears, the taskbar icon disappears, too, after hovering over it.
only two wire process keep the cpu busy at 100%.

**Comment by w7zz** [comment] 2018-11-29 11:46
Also having this issue. Can send a few messages and it'll randomly and instantly crash- causing 2-3 wire processes to use 100% cpu until manually terminated

**Comment by agolks** [comment] 2018-12-03 09:17
any logs we can provide?

**Comment by ejmount** [comment] 2018-12-04 00:06
I also have this issue. I had a look in Process Explorer, and found that what appears to happen is that a bunch of subprocesses that Wire spawns during normal operations end up orphaned when the parent process crashes. (Why those processes then starting using a whole CPU each isn't obvious.) There is a [Windows API that can prevent that happening](https://stackoverflow.com/questions/53208/how-do-i-automatically-destroy-child-processes-in-windows), which might present a stop-gap until the source of the original crash can be found, but I don't know how you'd use it from within Electrum.

**Comment by cm-v** [comment] 2018-12-06 14:35
same here, wire now version 3.4.2885 218.12.04.1424, W7 SP1 64bit de,
from the at least 6 wire processes 2 remain after program crash and eat up to 25% CPU each.

**Comment by juyu4323** [comment] 2018-12-08 21:14
Same issue here.

Wire on Windows 7 crashes randomly since a few days ago.
Several friends who also use wire on Wndows 7 have the same issue.

Wire is currently completely unuseable with Windows 7.

Please fix asap

**Comment by Mromson** [comment] 2018-12-09 11:11
It has seemingly gotten worse over the past few days. Now even the notification icon is showing a pixelated (looks like the width was increased of the Wire Notification icon and Windows 7 is correcting it).

Messages take ages to send and the app crashes.

**Comment by cm-v** [comment] 2018-12-10 11:16
bump - at least couldn't you give us the opportunity to rollback the W7 client software to a working stage?

**Comment by tokariu** [comment] 2018-12-10 11:43
having the same issue here on win7x64. Program suddenly disappears without plausible reason including the systray icon and CPU load is running wild after that.
This currently renders Wire Desktop useless on Windows 7 and urges for a fix.

**Comment by AxelBoldt** [comment] 2018-12-11 17:01
I also see random crashes on Windows 7 Enterprise SP1 with Wire 3.4.2885.  I noticed that after each such crash, there is one stray Wire process left running which consumes 100% CPU time of one of my four cores.

**Comment by cm-v** [comment] 2018-12-12 08:35
the beta 3.4.2890 apparently fixed the problem - at least until now, thx.

**Comment by agolks** [comment] 2018-12-12 09:11
#metoo
i'm interested, what change exactly fixed the problem?

**Comment by ffflorian** [comment] 2019-01-02 16:55
This was fixed in the latest release.

**Closed by ffflorian** 2019-01-02 16:55 UTC
Labels: platform: Windows, type: fix 🛠
