### ISSUE TITLE
Feature Request: Send images from clipboard

### ISSUE THREAD

**Issue by danoe** [wireapp/wire-desktop#49] opened 2016-09-23 15:29 UTC
In the Wire Desktop App I'd like to send pictures to my contacts by pasting them into the chat window. 

* Telegram Windows Desktop Client has that feature
  * in telegram you can even tell it if you want to send it compressed or uncompressed
* HipChat Desktop Client has this feature as well

Use case for me:
On Windows 10 I use greenshot (http://getgreenshot.org/) a lot to take screenshots of small areas of my desktop and send it to my contacts, because I use that a lot, at least 5 times every day or more, I don't want to save every file on my computer. In greenshot i can choose to just save the screenshot to clipboard, which I do and then paste it to a chat to send it to a one of my contacts.

**Comment by lipis** [comment] 2016-09-23 15:31
Closing this as duplicate of https://github.com/wireapp/wire-webapp/issues/236 add a reaction to raise your voice :D

**Closed by lipis** 2016-09-23 15:31 UTC
