### ISSUE TITLE
Change usernames

### ISSUE THREAD

**Issue by theincogtion** [wireapp/wire-desktop#554] opened 2017-04-05 17:32 UTC
I could not found an option in the Windows and Android app to change usernames in my contact list.
Please add this feature.

**Comment by helenakos** [comment] 2017-04-06 17:26
@theincogtion Do you mean change the names of your connections? If so it is a duplicate of #44

**Comment by lipis** [comment] 2017-04-06 17:42
Smells duplicate.. 👃

**Comment by theincogtion** [comment] 2017-04-06 18:24
Right this is a duplicate. Sorry.

**Closed** 2017-04-06 22:18 UTC
