### ISSUE TITLE
Page down and Page up keys disabled when Wire is in tray.

### ISSUE THREAD

**Issue by Tuj3Bz90dV** [wireapp/wire-desktop#2046] opened 2018-12-28 21:41 UTC
Due to [this piece of code](https://github.com/wireapp/wire-desktop/blob/5a0a4fcdcbbb2faba616b60d1050be45b7df2e82/electron/src/menu/system.ts#L458-L460), the page up and down keys are globally overridden. This should probably not use the `globalShortcut` module.

This causes, in Linux at least, the page up and down keys to not work in other applications when Wire is minimized to tray.

**Comment by Aranad** [comment] 2018-12-31 21:15
I'm getting this issue to on Mint 19

**Comment by ffflorian** [comment] 2019-01-02 09:12
Hi, thanks for reporting.
This behavior is strange, since Electron should [unregister all shortcuts on blur](https://github.com/wireapp/wire-desktop/blob/master/electron/src/main.ts#L186) and on Debian / Gnome I can't reproduce that. How do you guys minimize the app? With a shortcut or by clicking somewhere?

**Comment by Tuj3Bz90dV** [comment] 2019-01-02 14:55
`Window -> Close`. The unregistering of shortcuts works when minimizing or simply losing focus. I suppose the question is whether the `hide()` event also triggers `blur` or not. I'm on XFCE, for whatever that's worth.

**Comment by ffflorian** [comment] 2019-01-02 15:06
@Tuj3Bz90dV
Ah, I see. I can reproduce that.

**Comment by ffflorian** [comment] 2019-01-02 16:16
This fix will be included in the next release.

**Closed** 2019-01-02 16:16 UTC
Labels: platform: Linux, type: fix 🛠

**Comment by terba** [comment] 2019-01-29 06:40
I compiled Wire from the current sources some days ago, but the problem is still there. What can I do to solve this? I can not work without page up and down, so I have to quit Wire when this happens (many times per day).

**Comment by ffflorian** [comment] 2019-01-29 09:03
@terba when was "some days" ago? Try building from latest master.

**Comment by terba** [comment] 2019-01-30 13:10
It was compiled from good sources (on 2019-01-22), and it works well! I've played with the keyboard settings to solve the problem (before I found out that Wire causes the problem), and some apps were not working correctly because of this. Sorry for taking your time!

**Comment by ffflorian** [comment] 2019-01-30 13:58
Alright :slightly_smiling_face:

**Comment by hylkevds** [comment] 2020-04-02 11:46
For me this problem still exists, or maybe it exists again.
