### ISSUE TITLE
Long app start times: Slow decryption and high CPU use

### ISSUE THREAD

**Issue by tomleb** [wireapp/wire-desktop#876] opened 2017-08-12 14:38 UTC
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.08.1509
OS: Linux
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Open the application

What is the expected result?
Not seeing the loading screen for 5 minutes with my cpu hitting 100%.

What happens instead?
Loading screen for 5 minutes with my cpu hitting 100%.

**Comment by ConorIA** [comment] 2017-08-12 16:09
Are you using the Deb package or a home build? Have you used Wire on this device previously but then left it for a while?

It sounds like you have a lot of messages that are being decrypted at startup.

**Comment by tomleb** [comment] 2017-08-12 16:16
Yeah I don't open it often because of performance problem (#661) so that must be the
decryption then (and also slow internet speed).
Is there a way I could set a cronjob or similar to get the new messages without actually opening the application? Something like 
```
$ wire-desktop --pull-messages
```

I'm using the wire-desktop package from the AUR iirc.

**Comment by ConorIA** [comment] 2017-08-12 16:42
Startup should be much quicker with `libsodium-neon`, but I can't recall if the compilation was working recently. @maximbaz, do you know if the neon compilation issue has been resolved? 

As for starting Wire silently, the best option that I'm aware is `wire-desktop --hidden` which would start minimized to the tray. That's not what you're looking for though.

**Comment by tomleb** [comment] 2017-08-12 16:46
> As for starting Wire silently, the best option that I'm aware is wire-desktop --hidden which would start minimized to the tray. That's not what you're looking for though.

Should I make a suggestion in this repo? I would like a way to get the messages without having the application run afterwards.

**Comment by ConorIA** [comment] 2017-08-12 16:50
@tomleb sure. Or you could even rename this issue so that it reflects your request. I'm sure the devs will look at it. Although my guess is that you'd have to justify the use case.

e.g. Why not leave Wire running when you're at your computer? The slow startup will only happen once, then it should be quick on subsequent startups.

or

Try again once `libsodium-neon` is working correctly.

**Comment by maximbaz** [comment] 2017-08-12 16:59
The issue is not solved, but the workaround is still the same - install `lsb-release` package and then reinstall `wire-desktop` from AUR.

**Comment by ConorIA** [comment] 2017-08-12 17:01
Do I smell a temporary makedep? Or would that be overreaching?

**Comment by maximbaz** [comment] 2017-08-12 17:39
We could add it, although this workaround is valid only for the current version, since the next version (or to be more precise, when Wire upgrades rust_sodium dependency) there is a different approach, we will add `export RUST_SODIUM_DISABLE_PIE=1` in PKGBUILD (unless this is not done from within Wire).

**Comment by SafariLeader** [comment] 2017-08-19 14:58
Does the same procedure (lsb-release and reinstallation) work for the `wire-desktop-bin` package in the AUR as well? Or won't tha be affected because it uses the .deb file?

**Comment by ConorIA** [comment] 2017-08-19 15:17
@safarileader, the deb files should already have libsodium-neon built-in, I'd imagine.

**Comment by davidak** [comment] 2017-10-08 00:03
It takes also 5 minutes to load today on my system. Was faster in the past...

Here is a video about the experience: https://youtu.be/1bP_Lrc-3uE

---

![screenshot from 2017-10-08 02 01 02](https://user-images.githubusercontent.com/91113/31312765-9a5e5b0e-abcc-11e7-8780-a33cc6ed879d.png)

**Comment by gregor** [comment] 2017-10-11 19:56
We are still investigating. Long loading times can have multiple isses. Some are unfortunately still expected at this time. To better track this problem down, please answer the following questions:

- Which desktop platform are you using wire on? (Linux, macOS, Windows)
- When did you last start the desktop app before now launching it with the long load time?
- Are you using Wire with the same account on another device (desktop, mobile)?
- Approx. how many messages have you written and received during the time since you last started the desktop app? (10s, 100s, 1000s)

Thank you very much for your replies.

**Comment by jack-cole** [comment] 2017-10-11 20:22
On my laptop Wire can take up to 1.5 hours to load.

**Comment by davidak** [comment] 2017-10-12 09:05
@gregor thanks for investigating.

like you see in the video, i close it and start again directly.

I use it on one other desktop, but not very often becouse it louds too long.

There was aprox. 0 new messages in the 1 second it was closed.

Platform: elementary OS 0.4.1 Loki (based on Ubuntu 16.04.2 LTS) (Linux)

The other desktop is OS X 10.10.5.

**Comment by Termuellinator** [comment] 2017-11-13 08:30
i've got the same issue:
Platform: Linux (Manjaro KDE, so package from AUR) at home, Win10 at work - both show the same behaviour, win10 is MUCH worse, sometimes close to an hour of startup time, linux normally around 5min
last time normal start: can't remember :/
Account: Same account on android, linux and windows
Messages: normally i would say around 50ish, sometimes more, sometimes less. Now that you mention it, i THINK mondays are the worst at work, when many messages are written during the weekend - i'll have to keep an eye on that.

**Comment by gregor** [comment] 2017-11-13 10:28
Looking at some of the performance profiles I see a really weird behavior. Something is throttling the decryption process. It seems to be decrypting a single event only before waiting for a second or longer before continueing with the next one. The cause is currently unknown. Any feedback that would help us understand this behavior, which apparently only happens to a few and not all users, would be greatly appreciated.

**Comment by Termuellinator** [comment] 2017-11-13 11:04
if there is any further testing i can do or information i can provide, i'm happy to help - is there a logfile that can help or a way to issue verbose logging?

**Comment by gregor** [comment] 2018-01-30 18:11
How big is your IndexedDB if you run into this issue?

**Comment by Termuellinator** [comment] 2018-01-30 20:59
here on Linux it's 34mb atm for ~/.config/Wire/IndexedDB/
On Windows it's much worse, i'll look at how big it is there tomorrow.

**Comment by gregor** [comment] 2018-01-30 21:02
Are you using Wire with a single account only? If you have multiple accounts the IndexedDBs for the other accounts will be in Wire/Partitions/{partitionId}/IndexedDB

**Comment by Termuellinator** [comment] 2018-01-30 21:13
Nope, single account. I don'T see a partitions-folder either.
But i noticed that a folder in ~/.config/Wire/Service Worker/CacheStorage/ is pretty big (650mb), if that matters.
Where are those folders on Windows? Appdata?

**Comment by luciusbono** [comment] 2018-02-02 02:15
I'm super interested in this problem as well. Decrypt on my Windows machine is veeerrrry slow, although I'm also running an Ivy Bridge i5, so it's not exactly a modern processor. No idea how many messages it's generally decrypting but it's probably around 1000ish and it usually takes around 30mins

Happy to look at any logs / metrics that would be helpful. I use this machine infrequently (about once a week). 

Intel Core i5-3570 @ 3.4Ghz
16GB RAM
SSD
Windows 10 Pro (1709 build 16299.192)
Wire 3.0.2828

**Comment by gregor** [comment] 2018-02-02 08:24
@luciusbono Again the question about the size of your IndexedDB and whether you have a single or multiple accounts in you app?

For the first account:
What's the size of the folder `%AppData%\Wire\IndexedDB`?

If you have additional accounts:
What's the size of of the `IndexedDB` folders that can be found in  `%AppData%\Wire\Partitions\{SOME_UNIQUE_ID}`?

**Comment by tomleb** [comment] 2018-02-02 11:52
Hi,

I still have the same issue where decryption of new messages takes a very long time. (~1h)

```sh
$ du -hs ~/.config/Wire/IndexedDB/
35M	/home/tomleb/.config/Wire/IndexedDB/
```

I have a single account.
Scrolling is still slow.

I very rarely open the desktop app anymore due to these reasons.

**Comment by EgbertW** [comment] 2018-02-26 19:32
It takes somewhere between 5 and 10 minutes to start Wire on my laptop: Core I7-6700HQ, Ubuntu 16.04, Wire 3.0.2816-2816 from .deb package.

My IndexedDB size is 12MB. I had 2 accounts set up, one experimental and disabled Wire for Teams account and one regular account Basically all messages are in the regular account.

**Comment by Isvvc** [comment] 2018-03-01 06:54
On my various devices (Desktop Ryzen 5 1600x runing both Archlinux and Windows 10, as well as Surface Book gen 1 running Ubuntu 17.10 and Windows 10), it always takes ~10 minutes _at least_, or hours if it's been a long time since I've synced on that device, using up a LOT of CPU power (in Windows at least. Haven't measure in Linux).

On the other hand, if I have my Android phone (with no SIM card) completely disconnected from the internet, it can sync a day's worth of messages in about a minute once I connect it back.

**Comment by dubochet** [comment] 2018-06-11 08:50
Just for reference, this issue is also present on the macOS version of Wire desktop (I'm currently running version 3.1.2822 on macOS 10.13.4). Hope it will be fixed soon.

**Comment by Silun** [comment] 2018-06-21 15:37
Still seeing this issue on Win10.

**Comment by gregor** [comment] 2018-09-17 18:39
Since we released the fix of the bottleneck database call, app start time has been drastically improved. We have been monitoring the situation here and through our CS channels and the core issue to be fixed. While we can and will continue to work on further improvements, the underlying problem discussed in this issue is considered fixed.

**Closed by gregor** 2018-09-17 18:39 UTC
Labels: Investigation

**Comment by luciusbono** [comment] 2018-09-17 19:02
👍 thanks for the support, startup performance across all my clients has been great.

**Comment by robertnurnberg** [comment] 2018-09-20 08:36
On Linux, the latest update to the wire-desktop client is a regression for me. Start-up times used to be greatly improved, with fast decryption even after long periods away. However, with the latest update (1 or 2 days ago), start-up decryption is slow again, even if there are only a couple of new messages.

**Comment by janost** [comment] 2018-10-16 17:49
I'm experiencing the same issue with the Linux desktop client as @robertnurnberg. Not sure about other platforms.

**Comment by csibar** [comment] 2018-10-16 19:21
Same issue on macOS High Sierra 10.13.6 (17G65), Wire version 3.3.2862 (Wire for Web version 2018.10.15.0814) installed from the App Store. It would be awesome if you could fix this. Thanks in advance.
