### ISSUE TITLE
Lost access to all cameras

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3487] opened 2020-01-21 19:55 UTC
Wire desktop lost access to my cameras, 

![image](https://user-images.githubusercontent.com/388716/72838212-dd42f780-3c5d-11ea-99ff-a48886b3d311.png)

It look like the message and instructions only apply to the webapp browser.

**Comment by Transisto** [comment] 2020-01-23 18:15
Confirm problem is solved when turning on the software associated with the virtual cam, 
In that instance Logitech Capture.

If I click to go straight to the camera it locks the cameras again.
I used to have another virtual cam installed and never caused any problem beside showing a black image.

**Comment by ffflorian** [comment] 2020-01-24 08:52
Duplicate of https://github.com/wireapp/wire-webapp/issues/8036

**Closed by ffflorian** 2020-01-24 08:52 UTC
