### ISSUE TITLE
Chat doesn't scroll down properly when sending/receiving images.

### ISSUE THREAD

**Issue by lightswitchr** [wireapp/wire-desktop#405] opened 2017-02-04 18:43 UTC
I have noticed that if you send or receive an image, the window doesn't scroll to the bottom properly when you receive another message until you do so manually.

**Comment by anatoli26** [comment] 2017-02-19 07:00
Same here

**Comment by jwarner112** [comment] 2017-07-28 21:26
Same here! On Windows.

**Comment by gregor** [comment] 2017-09-15 14:22
The problem is rooted in the webapp used within the desktop offerings. Thus I am closing this in favor of the webapp issue that tracks it.

https://github.com/wireapp/wire-webapp/issues/1106

**Closed by gregor** 2017-09-15 14:22 UTC
Labels: Bug
