### ISSUE TITLE
Pasting images from clipboard incredibly slow and freezes entire application

### ISSUE THREAD

**Issue by rkapur-gds** [wireapp/wire-desktop#2988] opened 2019-08-28 14:10 UTC
Wire version: 3.10.3133
Wire for web version 2019.08.22.1145
Operating system: macOS 10.14.6 (18G87)

What steps will reproduce the problem?

1.  Take screenshot
2.  Copy to clipboard
3.  Paste in wire
4. Wait

What is the expected result?
Image pasting should be relatively quick.
...

What is the actual result?
It is not quick.
...

**Comment by ffflorian** [comment] 2019-08-29 05:09
Duplicate of https://github.com/wireapp/wire-desktop/issues/1175

**Closed by ffflorian** 2019-08-29 05:09 UTC
