### ISSUE TITLE
Calling to/from Windows 7 doesn't connect.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-desktop#11] opened 2016-08-17 15:42 UTC
Tried with both wire-desktop and Chrome (52)

Since wire use WebRTC, ports should need to be open - So what can cause this?

Is it possible to debug connection issues?

EDIT: Sometimes it connects, but the Windows 7 machine cannot send voice.

**Comment by gregor** [comment] 2016-08-17 17:01
I will try get access to a Windows 7 machine to reproduce your issues. Otherwise logs from your side would be helpful. After logging in on Chrome, please open the console and start logging by `wire.app.enable_debugging()`. Then try to calll and report back with the output. As logging will decrease perf you can later disable debugging by entering `wire.app.disable_debugging()`.

**Comment by gregor** [comment] 2016-08-18 18:00
@tmikaeld I tried using Chrome 51 on a Windows 7 machine and my calls connected flawlessly. Please provide some logs with the above mentioned method and I will further investigate.

**Comment by tmikaeld** [comment] 2016-08-18 18:05
Hello,

I tried this earlier today but couldn't verify if sounds works because i could only remote control the clients computer (Not listen to the headset). Will try again tomorrow.

(I removed any unique ID's and personal information):

````javascript
Failed to load resource: the server responded with a status of 404 (Not Found)
wire.app.enable_debugging()
true
z.calling.CallCenter                                         | 17:33:43.225 | Set logging for webRTC Adapter: true
z.event.WebSocketService                                     | 17:33:44.309 | Sending ping to WebSocket
z.calling.handler.MediaDevicesHandler                        | 17:33:52.435 | Updated MediaDevice list [Array[11]]
z.calling.handler.MediaDevicesHandler                        | 17:33:52.439 | Set constraints for MediaStream [Object]
z.calling.handler.MediaDevicesHandler                        | 17:33:52.441 | Requesting MediaStream access for 'audio' [Object]
z.calling.handler.MediaDevicesHandler                        | 17:33:52.681 | Received initial MediaStream with '1' MediaStreamTrack/s [Object]
z.calling.handler.MediaDevicesHandler                        | 17:33:52.683 | Local MediaStream contains MediaStreamTrack of kind 'audio' [Object]
z.calling.handler.CallStateHandler                           | 17:33:52.684 | PUTting the state to 'joined' in '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.telemetry.calling.CallTelemetry                            | 17:33:52.884 | Request PUT /conversations/{conversation_id}/call/state took 195ms
z.telemetry.calling.CallTelemetry                            | 17:33:52.884 | # of requests 1 - Avg: 195.00ms | SD: 0.00
z.calling.handler.CallStateHandler                           | 17:33:52.890 | PUTting the state to 'joined' in '211b922c-08e2-416e-9ea9-REMOVED' successful [Object]
z.calling.handler.CallStateHandler                           | 17:33:52.892 | Handling call state event with self client change: true [Object]
z.audio.AudioRepository                                      | 17:33:52.898 | Looping sound: ringing-from-me [g]
z.calling.handler.CallStateHandler                           | 17:33:52.940 | Outgoing 'audio' call to 'Thomas REMOVED - REMOVED' [a]
z.event.EventRepository                                      | 17:33:52.960 | Handling notification '300236c8-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:33:52.962 | Received unencrypted event 'conversation.voice-channel-activate' from user '26460094-98c5-4654-8845-REMOVED' [Object]
z.cryptography.CryptographyRepository                        | 17:33:53.089 | Saved unencrypted event 'conversation.voice-channel-activate' with primary key '211b922c-08e2-416e-9ea9-REMOVED@26460094-98c5-4654-8845-REMOVED@1471534441327'
z.conversation.ConversationRepository                        | 17:33:53.094 | »» Event: 'conversation.voice-channel-activate' [Object]
z.calling.CallCenter                                         | 17:33:53.107 | »» Event: 'conversation.voice-channel-activate' [Object]
z.event.EventRepository                                      | 17:33:53.108 | Distributed 'conversation.voice-channel-activate' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:33:53.110 | Last notification ID updated to '300236c8-6559-11e6-bfff-REMOVED'
z.storage.StorageService                                     | 17:33:53.126 | Updated 0 record(s) with key '211b922c-08e2-416e-9ea9-REMOVED' in store 'conversations' [Object]
z.conversation.ConversationService                           | 17:33:53.136 | Conversation '211b922c-08e2-416e-9ea9-REMOVED' was stored for the first time
z.event.EventRepository                                      | 17:34:11.752 | Handling notification '3b41a0d2-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:11.754 | Received call event 'call.state' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.CallCenter                                         | 17:34:11.755 | »» Event: 'call.state' [Object]
z.calling.handler.CallStateHandler                           | 17:34:11.756 | Handling call state event with self client change: false [Object]
z.event.EventRepository                                      | 17:34:11.756 | Distributed 'call.state' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.handler.CallStateHandler                           | 17:34:11.758 | State processed: Sequence '57' > '56'
z.event.EventRepository                                      | 17:34:11.758 | Last notification ID updated to '3b41a0d2-6559-11e6-bfff-REMOVED'
z.event.EventRepository                                      | 17:34:11.864 | Handling notification '3b52cb28-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:11.865 | Received call event 'call.flow-add' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.CallCenter                                         | 17:34:11.866 | »» Event: 'call.flow-add' [Object]
z.event.EventRepository                                      | 17:34:11.867 | Distributed 'call.flow-add' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.audio.AudioRepository                                      | 17:34:11.870 | Initialized a new AudioContext [AudioContext]
z.event.EventRepository                                      | 17:34:11.882 | Last notification ID updated to '3b52cb28-6559-11e6-bfff-REMOVED'
z.event.EventRepository                                      | 17:34:12.124 | Handling notification '3b7a4608-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:12.126 | Received call event 'call.remote-sdp' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.CallCenter                                         | 17:34:12.128 | »» Event: 'call.remote-sdp' [Object]
z.event.EventRepository                                      | 17:34:12.129 | Distributed 'call.remote-sdp' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.handler.CallSignalingHandler                       | 17:34:12.130 | Received remote SDP for existing flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510' [RTCSessionDescription]
z.event.EventRepository                                      | 17:34:12.134 | Last notification ID updated to '3b7a4608-6559-11e6-bfff-REMOVED'
z.calling.handler.MediaElementHandler                        | 17:34:12.146 | Created MediaElement of type 'audio' for MediaStream of flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510' [audio]
z.calling.handler.CallSignalingHandler                       | 17:34:12.153 | PUTting local SDP for flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510' [a]
z.telemetry.calling.CallTelemetry                            | 17:34:12.296 | Request PUT /conversations/{conversation_id}/call/flows/{flow_id}/local_sdp took 130ms
z.telemetry.calling.CallTelemetry                            | 17:34:12.297 | # of requests 1 - Avg: 130.00ms | SD: 0.00
z.calling.handler.CallSignalingHandler                       | 17:34:12.305 | PUTting local SDP for flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510' successful
z.event.WebSocketService                                     | 17:34:14.309 | Sending ping to WebSocket
z.event.EventRepository                                      | 17:34:26.523 | Handling notification '440fef84-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:26.524 | Received call event 'call.flow-active' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.525 | Distributed 'call.flow-active' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.525 | Last notification ID updated to '440fef84-6559-11e6-bfff-REMOVED'
z.event.EventRepository                                      | 17:34:26.533 | Handling notification '440fd24c-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:26.534 | Received call event 'call.state' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.CallCenter                                         | 17:34:26.536 | »» Event: 'call.state' [Object]
z.calling.handler.CallStateHandler                           | 17:34:26.536 | Handling call state event with self client change: false [Object]
z.event.EventRepository                                      | 17:34:26.538 | Distributed 'call.state' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.handler.CallStateHandler                           | 17:34:26.538 | State processed: Sequence '58' > '57'
z.event.EventRepository                                      | 17:34:26.539 | Last notification ID updated to '440fd24c-6559-11e6-bfff-REMOVED'
z.calling.handler.CallStateHandler                           | 17:34:26.540 | Delete call in conversation '211b922c-08e2-416e-9ea9-REMOVED'
z.audio.AudioRepository                                      | 17:34:26.541 | Stopping sound: ringing-from-me [g]
z.audio.AudioRepository                                      | 17:34:26.548 | Playing sound: call-drop [g]
z.calling.handler.MediaElementHandler                        | 17:34:26.554 | Deleted MediaElement of type 'audio' for flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510'
z.audio.AudioRepository                                      | 17:34:26.556 | Closed existing AudioContext
z.calling.handler.MediaDevicesHandler                        | 17:34:26.557 | Stopping MediaStreamTrack of kind 'audio' successful [MediaStreamTrack]0: MediaStreamTrackenabled: trueid: "225dc7e8-6891-42e5-861c-e434a773dfb7"kind: "audio"label: "Mikrofon på headset (Microsoft LifeChat LX-3000 )"muted: falseonended: nullonmute: nullonunmute: nullreadyState: "ended"remote: false__proto__: MediaStreamTracklength: 1__proto__: Array[0]
z.calling.handler.CallSignalingHandler                       | 17:34:26.558 | DELETEing flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510'
z.event.EventRepository                                      | 17:34:26.644 | Handling notification '441067ac-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:26.645 | Received call event 'call.state' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.calling.CallCenter                                         | 17:34:26.646 | »» Event: 'call.state' [Object]
z.calling.handler.CallStateHandler                           | 17:34:26.648 | Handling call state event with self client change: false [Object]
z.event.EventRepository                                      | 17:34:26.649 | Distributed 'call.state' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.651 | Last notification ID updated to '441067ac-6559-11e6-bfff-REMOVED'
z.event.EventRepository                                      | 17:34:26.652 | Handling notification '441450b0-6559-11e6-bfff-REMOVED' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:26.654 | Received unencrypted event 'conversation.voice-channel-deactivate' from user 'fad59198-701d-4b1a-9664-879e988fd5c5' [Object]
z.cryptography.CryptographyRepository                        | 17:34:26.682 | Saved unencrypted event 'conversation.voice-channel-deactivate' with primary key '211b922c-08e2-416e-9ea9-REMOVED@fad59198-701d-4b1a-9664-879e988fd5c5@1471534474996'
z.conversation.ConversationRepository                        | 17:34:26.684 | »» Event: 'conversation.voice-channel-deactivate' [Object]
z.calling.CallCenter                                         | 17:34:26.688 | »» Event: 'conversation.voice-channel-deactivate' [Object]
z.event.EventRepository                                      | 17:34:26.689 | Distributed 'conversation.voice-channel-deactivate' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.690 | Last notification ID updated to '441450b0-6559-11e6-bfff-REMOVED'
z.event.EventRepository                                      | 17:34:26.691 | Handling notification '4423f5c4-6559-11e6-bfff-22000a520a63' from 'WebSocket' containing '1' events [Object]
z.event.EventRepository                                      | 17:34:26.693 | Received call event 'call.flow-delete' in conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.695 | Distributed 'call.flow-delete' event for conversation '211b922c-08e2-416e-9ea9-REMOVED' [Object]
z.event.EventRepository                                      | 17:34:26.696 | Last notification ID updated to '4423f5c4-6559-11e6-bfff-22000a520a63'
z.telemetry.calling.CallTelemetry                            | 17:34:26.796 | Request DELETE /conversations/{conversation_id}/call/flows/{flow_id} took 236ms
z.telemetry.calling.CallTelemetry                            | 17:34:26.796 | # of requests 1 - Avg: 236.00ms | SD: 0.00
z.calling.handler.CallSignalingHandler                       | 17:34:26.797 | DELETEing flow '4ad3e0d7-9cdf-4297-9e5a-0908d9313510' successful
z.event.WebSocketService                                     | 17:34:44.309 | Sending ping to WebSocket
wire.app.disable_debugging()
true
z.user.UserRepository                                        | 17:34:46.425 | Saved updated settings: 'enable_debugging' - 'false'

````

**Comment by tmikaeld** [comment] 2016-08-18 18:07
We have used Wire on various platforms and computers and this is the third time it didn't work, so quite curious to find out the reason this time. But we will have to wait for the client to be in the office and have time over.

**Comment by tmikaeld** [comment] 2016-08-18 18:10
By the way, two client's want to use Wire from China, have you tested if Wire works across The Great Firewall?

**Comment by gregor** [comment] 2016-08-19 13:12
Hi @tmikaeld, thanks for the log. After the clearing the personal information also the helpful debugging information that would help me is also gone from the log. I do need the lines that contain info about the call and flow (prefixed z.calling.entity.Call and z.calling.entity.Flow). I certainly understand that you do not want to post them oublicly here, but would you mind sending the log to me directly? You can email it to gregor [at] wire.com.

Which microphone is set to default on your machine? We unfortunately do not yet allow you to choose your input device and just use the default. If this is not working corretly you might actually be sending silence.

I have not personally tried whether Wire works from or to Chine and would be interested in hearing your results.

**Comment by tmikaeld** [comment] 2016-08-19 13:59
I think you want the arrays but they are "folded" in Chrome debug and i cannot save it to file.

I'll try and select the text and copy it but it will not look nice.

**Comment by gregor** [comment] 2016-08-19 14:07
Arrays certainly add even more information but just the lines you removed in order to avoid having to remove personal information from them individually would be a good start.

**Comment by tmikaeld** [comment] 2016-08-19 14:09
The only things i changed are marked with REMOVED, personal names and unique ID's didn't seem relevant.

**Comment by gregor** [comment] 2016-08-19 14:21
Thanks for pointing that out. The javascript code I gave you does not overwrite the logging defaults. The intesting lines I was taking about were missing. Please also run the following in the console before you gather a new log: `z.config.LOGGER.OPTIONS.domains["app.wire.com"] = function(){ return 300;}`

You can later reset it with: `z.config.LOGGER.OPTIONS.domains["app.wire.com"] = function(){ return 0;}`

**Comment by tmikaeld** [comment] 2016-08-21 10:13
After a reboot we could get it to work via Chrome but not via the App, in Chrome the sound level where really low so i could barely hear anything. Could this be the issue?

I found this, among other things:
http://stackoverflow.com/questions/32204985/webrtc-reduces-system-volume

**Comment by tmikaeld** [comment] 2016-08-22 15:20
Wire (Or WebRTC) works very well from China, tested from Shenzhen.

**Comment by tmikaeld** [comment] 2016-10-09 09:49
After doing a lot more testing, this is not an issue with connecting any more but with sound device not being correct. The client having problem have a custom Sound Driver for DSP sound processing - if that unit is chosen and it's connected to a device that don't produce sound - Wire cannot connect (in fact, most apps hang in this case).

So i would really suggest making it a priority to be able to choose the Sound Input/output device in Wire!

**Comment by gregor** [comment] 2016-10-10 10:18
@tmikaeld Thanks for the update. This is very high on my wish list as well. As I previously stated the ability is already in the code, but not yet exposed in the UI due to limitations in our current preferences design. I am working this week on updating our preferences to a fresh new look that is much easier to extend so we can add the options - hopefully soon.

**Comment by gregor** [comment] 2017-01-26 13:45
Though we never identified the cause for these specific calls not connecting, we have/are doing many changes to our calling infrastructure. Above mentioned preferences changes have also been live for quite some time. Thereby closing this. Please open a new issue if you run into problems again.

**Closed by gregor** 2017-01-26 13:45 UTC
Labels: Bug, Windows

**Comment by tmikaeld** [comment] 2017-01-26 13:47
@gregor Sorry for not replying in a while, we recently replaced the router hardware for this client and that was the issue. The internal cache memory was worn out (flash memory) so it would randomly stop streams from working.

**Comment by gregor** [comment] 2017-01-26 14:24
@tmikaeld Glad you found the root cause of the issue.
