### ISSUE TITLE
Profile picture in new sidebar not updating until restart

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-desktop#667] opened 2017-06-05 08:18 UTC
Wire Version: 2.13.2741
Wire for Web Version: 2017.06.01.1002
OS: Ubuntu 16.04

What steps will reproduce the problem?
1. change profile picture

What is the expected result?
The profile picture in the top left corner should automatically update.

What happens instead?
The background of the chats list updates correctly, but the profile picture at the top stays the same.

**Comment by gregor** [comment] 2017-07-09 14:00
We have been unable to reproduce this issue. The new sidebar will also be changing soon. Thus I am closing this ticket.

**Closed by gregor** 2017-07-09 14:00 UTC
