### ISSUE TITLE
German locale not working in desktop app on first launch automatically

### ISSUE THREAD

**Issue by rehoehle** [wireapp/wire-desktop#705] opened 2017-06-21 17:34 UTC
Wire Version:  2.14.2743
Wire for Web Version: 2017.06.07.1805
OS: OSX 10.12.5

I have a german system and get the english version. I've looked to the Web-Version and it seems that the translations is correct and available but it's not used. 

On my Android it's working well.

**Comment by lipis** [comment] 2017-06-21 18:23
If the automatic language detection didn't work you can always change it from the menu.  

Wire > Language > Deutsch

**Comment by rehoehle** [comment] 2017-06-21 18:35
Thx... yes the automatic language detection isn't working but i can switch to german.

**Comment by lipis** [comment] 2017-06-21 19:09
I guess we can close this one then.

**Comment by rehoehle** [comment] 2017-06-21 19:10
But that doesn't solve the main problem that the language detection isn't working ;)

**Comment by lipis** [comment] 2017-06-21 19:11
True, I updated the issue title accordingly.

**Comment by WDGroll** [comment] 2017-08-03 20:09
Since I upgraded to 2.15.2751-154 (using apt-get), i's impossible to switch to any other language but english. After the required restart wire-desktop comes up again with english, despite the language choosen before.
The preceding versions came up with the english language after installation, but one could easily change to the preferred langunge using the Language menu. 

Environment:
- Debian 9 amd64 with gnome desktop
- wire-desktop 2.15.2751-154 from "deb https://wire-app.wire.com/linux/debian stable main"
- Wire für Web Version 2017.08.03.1519

**Comment by gregor** [comment] 2017-08-04 09:16
@WDGroll Thanks for the report. The issue is known to us. Until we push out a fix you can use the following workaround. You should be able to switch the language, select restart later and then manually restart. You should then see the app in your desired language. Please report back if this doest not work.

**Comment by shvchk** [comment] 2017-08-06 18:53
Came here to file a report about language switching to be unreliable (initial switch only works after manual restart, also sometimes language is just resets to English by itself), but as issue is already known there seems to be no need to. Hope it will be resolved soon.

**Comment by AyelGoth** [comment] 2017-09-16 22:24
The same goes for the Spanish language. When you change the language to Spanish and restart the application, the program in linux does not change the language.

**Comment by gregor** [comment] 2017-09-18 08:37
Thanks. As stated the broken language change is known. The fix for this was merged last week and will be part of the next release. https://github.com/wireapp/wire-desktop/pull/944

**Comment by drdaeman** [comment] 2017-09-22 13:46
Just a hint: while the release containing the fix is not yet out there, one can manually edit `init.json` (search for "Wire" in `%AppData%\Roaming` on Windows or `$XDG_CONFIG_HOME` on GNU/Linux - sorry, no clue about macOS) and add a key to the object e.g. `"locale": "de"` for the German language.

Just in case someone would want to invite someone to Wire (helping to install it), and need the language switcher working.

**Comment by bennyn** [comment] 2018-11-12 16:44
@rehoehle Thanks for your report! We solved this issue with [3.3.2862 - macOS](https://github.com/wireapp/wire-desktop/releases/tag/release%2F3.3.2862).

**Closed by bennyn** 2018-11-12 16:44 UTC
Labels: type: fix
