### ISSUE TITLE
Wire can’t access your system's safe storage.

### ISSUE THREAD

**Issue by KitchM** [wireapp/wire-desktop#7820] opened 2024-05-05 18:07 UTC
Wire version: 3.35.3348
Wire for web version: 2024.04.25.09.21.36
Operating system: Debian 11 (Bullseye)
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Start wire-desktop
2.  Try to log in with email and password

What is the expected result?  Being able to log in.

What is the actual result?  Got error message:  "Wire can’t access your system's safe storage. Find out how to log in"

Please provide any additional information below. Attach a screenshot if possible.

Went thru various steps to fix the problem:
wire-desktop --password-store="gnome-libsecret"
[24374:0504/163710.162726:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
Error occurred in handler for 'EVENT_TYPE.ACTION.ENCRYPT': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /opt/Wire/resources/app.asar/electron/dist/main.js:254:115
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: preload-context.js:116:13
Remote event names: context-menu
Error occurred in handler for 'EVENT_TYPE.ACTION.ENCRYPT': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /opt/Wire/resources/app.asar/electron/dist/main.js:254:115
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)

Using Debian 11 Bullseye and Xfce 4.6.  Have KeePassXC with Secret Service Integration and Kleopatra.  I installed keychain and then rebooted.  Wire came up without a prompt.  On next boot, the program had same problem: Wire can’t access your system's safe storage. Find out how to log in

There appears an inconsistency in operation,  as well as incomplete directions found at https://github.com/wireapp/wire-desktop/wiki/Grant-access-to-system's-keychain-(Linux)

Maybe I'm doing something wrong or missing a step, but the program does not seem to work out of the box.

**Comment by Dr64h** [comment] 2024-05-22 11:24
The same problem, in my case it happened when upgrading from kde5 to kde6.

**Comment by istankovic** [comment] 2024-05-27 08:12
Duplicate of #7764.

**Closed by istankovic** 2024-05-27 08:12 UTC
