### ISSUE TITLE
Missing notifications from Android to Desktop

### ISSUE THREAD

**Issue by skostrigin** [wireapp/wire-desktop#2315] opened 2019-03-11 12:13 UTC
version wire for android 3.28.743
android version 8.0.0
wire desktop 3.6.2885

What steps will reproduce the problem?
If from a single account that uses Android, make an audio or video call on the second account that uses the computer, notifications do not come to the account that uses the computer

Steps to reproduce :
1. wire android version, call audio or video call
2. open wire desktop
3. no notification that there was a missed audio or video call from the android version of the wire

**Comment by Mikaela** [comment] 2019-06-04 08:20
I wonder if this is related to https://github.com/wireapp/wire-desktop/issues/2570 ?

**Comment by ffflorian** [comment] 2020-08-20 08:18
Yes, this is a duplicate of https://github.com/wireapp/wire-desktop/issues/2570.

**Closed by ffflorian** 2020-08-20 08:18 UTC
