### ISSUE TITLE
Exception window showing up 

### ISSUE THREAD

**Issue by vecna** [wireapp/wire-desktop#1530] opened 2018-06-11 12:04 UTC
Hi, I'm using Wire for Windows
Version 3.0.2828 
_despite is a desktop app, it also display_
Wire for Web Version 2018.05.24.1549

Today this window keeps popping up. It happens "once a while" I can't say what is the trigger:

![image](https://user-images.githubusercontent.com/89555/41230433-1bc5304e-6d80-11e8-8527-2a4636309b83.png)

**Comment by ffflorian** [comment] 2018-06-11 13:55
Hi @vecna,

this is a duplicate of https://github.com/wireapp/wire-desktop/issues/968.

**Closed by ffflorian** 2018-06-11 13:55 UTC
