### ISSUE TITLE
High memory usage on MacOS

### ISSUE THREAD

**Issue by JMoVS** [wireapp/wire-desktop#5247] opened 2021-08-11 19:47 UTC
Wire version: 3.26.4145 
Wire for web version: 2021.06.01.12.23
Operating system: Mac OS Big Sur 11.5.1
Which antivirus software do you have installed: Apple default

What steps will reproduce the problem?

1.  run wire continuesly for a couple of days
2.  ![grafik](https://user-images.githubusercontent.com/7354506/129092984-9fe00a5d-8d7e-4aaa-ba62-32e7d1807f14.png)
3.  ...

What is the expected result?

memory usage not balooning to literally 5.84GB!

What is the actual result?

![grafik](https://user-images.githubusercontent.com/7354506/129092984-9fe00a5d-8d7e-4aaa-ba62-32e7d1807f14.png)

Please provide any additional information below. Attach a screenshot if possible.

It seems like 2 Wire Render processes are the major culprit. I attached a spindump (should be free of private data I guess).

[Analyse von „Wire Helper (Renderer)“.txt](https://github.com/wireapp/wire-desktop/files/6970991/Analyse.von.Wire.Helper.Renderer.txt)

**Comment by ffflorian** [comment] 2021-08-24 14:27
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/2507.

**Comment by JMoVS** [comment] 2021-08-24 14:39
is high memory really the same as constant CPU usage?

**Comment by ffflorian** [comment] 2021-08-24 14:46
Sorry, I meant https://github.com/wireapp/wire-desktop/issues/2239.

**Closed by ffflorian** 2021-08-24 14:46 UTC
