### ISSUE TITLE
err with build on latest archlinux 

### ISSUE THREAD

**Issue by world-breaker** [wireapp/wire-desktop#563] opened 2017-04-08 08:37 UTC
The dependency library expires in the build tool，**readline**,on latest archlinux,the libreadline.so version defalut 7, but build tool need 6. The following error message is given：

> npm run build:linux
....
/home/kevin/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
....

on my archlinux:
libreadline.so
libreadline.so.7
libreadline.so.7.0

I don't want to use make install replace pacman...

**Comment by ConorIA** [comment] 2017-04-08 10:38
That is during the AppImage stage, right? The issue isn't really with Wire. 

A quick workaround is to symlink libreadline.so to libreadline.6.so.

However, on Arch I recommend installing from the AUR.

**Comment by ffflorian** [comment] 2017-04-11 15:38
@world-breaker Closing this one for now as this isn't a wire-desktop related issue. Feel free to reopen if there are any news.

**Closed by ffflorian** 2017-04-11 15:38 UTC
