### ISSUE TITLE
[Desktop] Audio and Video calls without hardware components

### ISSUE THREAD

**Issue by ArchiveBase** [wireapp/wire-desktop#2899] opened 2019-07-26 08:56 UTC
Subj. feature request had opened several months ago however it disappeared already. Do repository maintainers delete issues without even close?

**What steps will reproduce the problem?**

( Use a Desktop PC (Or a Laptop disabled integrated camera, microphones )

1.  Try to make a audio and video call. 
     Result > Unable make call
2.  Try to accept/join to incoming audio and video call. 
     Result > Unable answer call

**What is the expected result?**

1. Wire desktop client should allow to make audio or video call with only showing notification about the device doesn't have camera, microphone or unable access them.
2. Wire desktop client should allow to answer audio or video call with only showing notification that the device doesn't have camera, microphone or unable access them.

  ( What's the useful? Example: One end client able join with video call without having microphone or both of them & ability to make calls even any hardware failures or any emergency time )

...

**What is the actual result?**

Wire desktop client prevent make or answer call and shows notification similar below ,
 Video calls - You cannot call because your computer does not have a camera (access to camera)
 Audio calls  - You cannot call because your computer does not have a microphone 
...

**Comment by ArchiveBase** [comment] 2019-07-26 09:33
I found it transferred to webapp repository however hope will remember to apply the same for desktop-app

**Comment by ffflorian** [comment] 2019-07-26 10:06
@ArchiveBase yes, sorry, I was moving issues around a bit. We are not deleting issues, sorry for the confusion.

Since the desktop app is just a wrapper around the webapp, the feature needs to be integrated into the webapp. Once it's in, you will have it in the desktop app, too.

Closing this as duplicate of https://github.com/wireapp/wire-webapp/issues/7018.

**Closed by ffflorian** 2019-07-26 10:06 UTC
