### ISSUE TITLE
Wire Version 3.0.2816   2018.05.05.0718 Web Cam light

### ISSUE THREAD

**Issue by lunixgeek** [wireapp/wire-desktop#1468] opened 2018-05-14 19:58 UTC
Wire Version 3.0.2816   2018.05.05.0718

Logitech Web Cam blue light won't go out.

When I start a video call the blue light on my web CAM comes on which is as it should be.  However, when I turn off the Web  Cam but keep talking on the microphone the light does not go out.  Version 3.0.2816 Wire for Web Version 2018.05.04.0718

**Comment by ffflorian** [comment] 2018-05-28 14:50
Hi @lunixgeek,
thanks for reporting. AFAIC this is a duplicate of https://github.com/wireapp/wire-desktop/issues/48.

@gregor can you confirm?

**Comment by lunixgeek** [comment] 2018-05-28 15:07
It looks like you understood and it appears to be the same.  So you are saying the fix must come from Chrome.  In todays world of security concerns I hope that gets attacked soon.

**Comment by gregor** [comment] 2018-06-01 09:43
Yes, it is a duplicate. Going to close it as such. Be assured that the camera only runs locally and the stream is no longer transfered to the remote side.

**Closed by gregor** 2018-06-01 09:43 UTC
