### ISSUE TITLE
Timed messages appear to increase background CPU Usage

### ISSUE THREAD

**Issue by chriseomi** [wireapp/wire-desktop#4182] opened 2020-08-25 16:16 UTC
Wire version: Version 3.18.3728
Operating system: macOS Catalina
Which antivirus software do you have installed: none

Ok so I don't have time to investigate fully, but seems to be a correlation between having expiring messages and CPU usage. 

I couldn't understand why Wire was using 20-30% CPU simply by being in the background and slowing down my machine. It seems to me, to correlate with switching some of my conversations to "ephemeral" or timed messages.

It also appears that the the usage may also climb linearly as the conversations get longer O(n). My guess is it's some interrupt, polling, event thingie attached to every single individual message that's kinda over zealous about strictly removing messages when their time is up ;)

Just my hunch or call it a fallible intuition as a dev for 20 years. Could be 100% wrong. 

Thought I'd get the convo started either way.

**Comment by chriseomi** [comment] 2020-08-25 16:32
Additionally I can confirm, after upgrading to the latest version (Version 3.19.3799) that includes Electron 9.1.2, the problem still persists.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/49441974/91201737-bd464b80-e6f8-11ea-8cc4-ac3e1ce7d1dd.png">

**Comment by ffflorian** [comment] 2020-08-25 18:03
Hi @chriseomi, thanks for the in-depth report. We are aware of the issue and this is a duplicate of https://github.com/wireapp/wire-desktop/issues/1650.

**Closed by ffflorian** 2020-08-25 18:03 UTC
