### ISSUE TITLE
Wire fail to start on Debian

### ISSUE THREAD

**Issue by aptailor** [wireapp/wire-desktop#605] opened 2017-04-24 08:49 UTC
I followed the Debian repo instruction and when i start Wire i get a error message. I am using Debian 8 Qubes VM.

machine1 :~$ /opt/wire-desktop/wire-desktop

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:95:36)
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:377:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)

**Comment by ffflorian** [comment] 2017-04-24 09:22
Hello @aptailor, thanks for reporting. The issue is known and was fixed in https://github.com/wireapp/wire-desktop/pull/587. Our next release will include the fix.

Feel free to reopen this issue if the error persists.

**Closed by ffflorian** 2017-04-24 09:22 UTC
