### ISSUE TITLE
Menu bar is fully black, menu titles not visible

### ISSUE THREAD

**Issue by Filbuntu** [wireapp/wire-desktop#2173] opened 2019-02-07 13:23 UTC
Since I upgraded via deb-file to Wire 3.5.2881-2881 (Ubuntu 18.04, no antivirus installed), the menu bar is black and the menu titles (e.g. Wire, Conversation) are not visible (only when a window like "About Wire" is opened). I first thought there are no menus anymore and accidentally discovered the hidden menus today.

![screenshot from 2019-02-07 21-19-34](https://user-images.githubusercontent.com/12456480/52414096-5402e580-2b1e-11e9-8efc-6ea52919fa83.png)
![screenshot from 2019-02-07 21-22-10](https://user-images.githubusercontent.com/12456480/52414170-8876a180-2b1e-11e9-90c2-e7a9b73585a1.png)

**Comment by nynhex** [comment] 2019-02-07 17:05
@Filbuntu I spun this up in a VM same OS release and wire-build.  Cannot replicate.  Are their any other parameters that might be missing?

**Comment by Filbuntu** [comment] 2019-02-08 00:57
@nynhex Thanks for quickly checking this! Indeed, it is most likely related to another parameter. I normally run Ubuntu 18.04 with the communitheme snap (Yaru, https://snapcraft.io/communitheme, https://www.omgubuntu.co.uk/2018/08/linux-release-roundup-yaru-cantata-vscode). 
When I login with the default theme, the menu bar is light and the menu titles are seen. Now I am not sure who can adjust the colour/brightness of the menu titles depending on the colour/brightness of the menu bar.
![screenshot from 2019-02-08 08-49-07](https://user-images.githubusercontent.com/12456480/52452777-5e090080-2b7f-11e9-9282-b4615a446eef.png)

**Comment by Filbuntu** [comment] 2019-02-18 02:18
Thanks for working on this!

**Comment by ffflorian** [comment] 2019-03-08 12:17
Duplicate of https://github.com/wireapp/wire-desktop/issues/1208

**Closed** 2021-05-05 07:31 UTC
Labels: platform: Linux 🐧, type: electron-issue 🔀
