### ISSUE TITLE
Emoji not displaying / square instead

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-desktop#1588] opened 2018-07-02 11:16 UTC
Wire version: Version 3.2.2860 
Wire für Web Version 2018.06.19.0804 
Operating system: Win7 x64 

What steps will reproduce the problem?

1.  Receive a emoji

What is the expected result?
Showing the puking emoji 
Emoji image of 'face_with_open_mouth_vomiting'

What is the actual result?
Getting a square 🤮 

This is the case for many emojis.

NB For the signal electron version, emoji is displayed correctly.

**Comment by gregor** [comment] 2018-07-02 12:34
We rely on the system support for emojis and have never implemented our own emojis. Windows 7 was released in 2009 and Microsoft ended mainstream support for it in 2015. Newer operating system have support for all the emojis you would expect. At this time we do not intend to invest the resources necessary to maintain emoji support on outdated operating systems.

**Comment by mahescho** [comment] 2018-07-04 06:12
Count me in for the :-) emoji only, all others I use work. I noticed this first after the upgrade from Kubuntu 16.04 to 18.04. I suspect the Linux client to be a web view and the emojis look like font awesome ... if I'm right this should be no local issue.

**Comment by Sledge-Hammer** [comment] 2018-07-07 19:11
Same thing with Windows 8.1 and 2012 R2 about the `:)` emoji.

**Comment by maximbaz** [comment] 2018-07-07 20:53
I suspect you observe this because you tried a bunch of [people emoji](https://emojipedia.org/people/) and all of those were released in 2012 as part of Unicode 6.1, but the `:)` emoji is [slightly smiling face](https://emojipedia.org/slightly-smiling-face/) released in 2014 as part of Unicode 7.0. If I'm right, you will probably find that some emoji from [Unicode 7.0](https://emojipedia.org/unicode-7.0/) or later are also not working for you. Wire has lots of emojis, everything released up until [Unicode 10.0](https://emojipedia.org/unicode-10.0/).

On Windows you cannot do much about it, I'm afraid, but on Linux I recommend installing some a modern emoji font, like Google Noto Color Emoji or Emoji One (see [Linux setup help](https://github.com/emojione/emojione/tree/master/extras/fonts#google-font---emojione-androidttf)).

**Comment by Sledge-Hammer** [comment] 2018-07-07 23:35
Can it be easily detected if an emoji is missing from the user's system and then just display the text equivalent instead of a square?

**Comment by maximbaz** [comment] 2018-07-08 00:05
Cool idea, but I don't think it's possible, unfortunately. 

For missing glyphs there is a font fallback mechanism, where if a font number 1 doesn't have a given glyph, font number 2 is tried, then number 3 and so forth, until a glyph is found or we are out of fonts. However, the situation with emoji fonts is a bit special because there are multiple font formats and different browsers on different OS support different subsets of formats (🤦‍♂️). 

Moreover, Windows will not respect a custom font for emojis regardless of font format, it seems the font name `Segoe UI Emoji` is hardcoded deep inside it with no way to override it. People still work around that by replacing the font files (see [Twitter Emoji](https://github.com/eosrei/twemoji-color-font#install-on-windows)), but then again, the format SVGinOT is not supported by Chrome on Windows, and so by Wire.

Having said that, I've just checked Wire on latest Windows 10 and it does support `:)` and other emojis from Unicode 10, so if this is an option, just upgrade your Windows and you will have all emojis out of the box.

**Comment by tokariu** [comment] 2018-07-15 11:00
I have spoken many times with the support about this problem since the beginning and I'm disappointed that no ressources went into this issue. I'm also using Win7 and upgrading to Win10 is no option due to it's data and privacy violations and general customer unfriendly manner (regarding failing updates, "windows as a service" == beta tester for MS, not having any real control over the system anymore, etcpp.)

So don't recommend upgrading to Windows 10 as a solution to this issue, because it introduces a megaton other issue on other fronts.

I consider relying on system fonts for the wire emoji system as one of the biggest mistakes made. Not just because Win7 does not support them, but due to the emoji inconsistency over all the devices and os's. On every device an emoji looks different. If you try to send a specific emoji because you want the receiver to see exactly this face/emoji/emoji-symbol/pic he won't see exactly this, but his version of this emoji. these look often very different and the receiver gets a wrong impression or intention of the sender.

From the beginning on, wire should have implemented it's own emoji-set across all devices and os', just like all the other messenger did.

For the Win7 users, the only way to decode the square placeholder emojis is, to have a second device like android and look at the same conversation there to see the real emoji.

It's a pitty that the devs accepted waiting until all users have newser operating systems as a solution for this issue, instead of investing a little ressources.

**Comment by maximbaz** [comment] 2018-07-15 13:12
> From the beginning on, wire should have implemented it's own emoji-set across all devices and os', just like all the other messenger did.

Just so you know, the other messengers don't have a peaceful life with that decision, here are just a few examples from Telegram desktop:

- [Why doesn't Telegram let every system handle emojis?](https://github.com/telegramdesktop/tdesktop/issues/2111)
- [[Feature Request] Option to use System/EmojiOne emoji set?](https://github.com/telegramdesktop/tdesktop/issues/3336)
- [Replacement of Apple Emoji set with Twemoji](https://github.com/telegramdesktop/tdesktop/issues/3033)
- [Using EmojiOne instead of Apple Emoji](https://github.com/telegramdesktop/tdesktop/issues/3281)
- [Change emoji style](https://github.com/telegramdesktop/tdesktop/issues/3726)
- [Allow user to choose font and font size](https://github.com/telegramdesktop/tdesktop/issues/90)
- [Prefer system-wide emoji font over baked-in Qt resource](https://github.com/telegramdesktop/tdesktop/issues/4206)

There are numerous emoji sets, some of them are less popular, some of them are restricted by license which would prevent Wire to officially include them in the distribution. I'm personally extremely happy that I am able to try each and every of the available emoji sets, choose my favorite one and instantly make Wire use it without having to beg for including it in the distribution or fighting legal battles.

I think you should realize that using an outdated operating system is a choice that has consequences of lacking modern features, keep in mind that Windows 7 was released in 2009, 3 years before the basic people emoji were even invented! (i.e. added to Unicode 6.1 in 2012)

**Comment by tokariu** [comment] 2018-07-15 16:55
there is no way to please everyone. But i think there are options to improve the current situation. offering one general wire-owned emoji set (w/o licensing issues) might be one attempt to improve the situation. 
of course it's good that you can change emoji sets in your case, but as a windows 7 user you don't have that option anyway.

And I think you should know that we (=many of the wire users still using win7) don't use windows 7 because we don't want modern features - of course we want. The problem is Windows 10 brings so much problems at a completely underlaying level (above mentioned problems are just the tip of the iceberg) that we have no other chance than abstain from the OS and it's "modern features". If there would be a new windows which resolves these issues, we wouldn't wait a single day longer to migrate to the new OS, but that's simply not the case.

Therefor, instead of recommending windows 7 users to upgrade to windows 10 to get these emojis, you should rather recommend them to install a linux operating sytem where emojis might be also working.

**Comment by gregor** [comment] 2018-07-16 09:21
It would be a solution but we are not willing to spend the resources needed to maintain this. We will continue to rely on the operating system support for emoji support.

**Closed by gregor** 2018-07-16 09:21 UTC
