### ISSUE TITLE
Wire messes with PageUp and PageDown on Lubuntu

### ISSUE THREAD

**Issue by Svalorzen** [wireapp/wire-desktop#2094] opened 2019-01-14 18:11 UTC
- Wire version: 3.5.2881
- Operating system: Lubuntu 18.04 = Two separate machines have this problem.
- Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Have Wire open for a while

What is the expected result?

PageUp and PageDown keep working as expected.

What is the actual result?

They don't as long as Wire is not restarted. In particular, the keypresses are still registered, but they don't allow you to scroll.

Using them in combination with modifiers works perfectly: using them with Ctrl still changes tab in Firefox, using Shift can still allow me to scroll in the terminal.

They are still registered as when I press them alone there is some flashing of the current window (in the terminal the cursor blinks, in Firefox the sidebar flashes) but no movement occurs.

Running xev when in this state returns some sort of event for the keys:

    FocusOut event, serial 48, synthetic NO, window 0x3c00001,
    mode NotifyGrab, detail NotifyAncestor

    FocusIn event, serial 48, synthetic NO, window 0x3c00001,
    mode NotifyUngrab, detail NotifyAncestor

    KeymapNotify event, serial 48, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

But not a KeyPress/KeyRelease event. For reference, normally xev returns

    KeyPress event, serial 48, synthetic NO, window 0x2a00001,
    root 0x5e3, subw 0x0, time 57346975, (652,584), root:(2333,632),
    state 0x0, keycode 117 (keysym 0xff56, Next), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

    KeyRelease event, serial 48, synthetic NO, window 0x2a00001,
    root 0x5e3, subw 0x0, time 57347127, (652,584), root:(2333,632),
    state 0x0, keycode 117 (keysym 0xff56, Next), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

    KeyPress event, serial 48, synthetic NO, window 0x2a00001,
    root 0x5e3, subw 0x0, time 57347575, (652,584), root:(2333,632),
    state 0x0, keycode 112 (keysym 0xff55, Prior), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

    KeyRelease event, serial 48, synthetic NO, window 0x2a00001,
    root 0x5e3, subw 0x0, time 57347671, (652,584), root:(2333,632),
    state 0x0, keycode 112 (keysym 0xff55, Prior), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

Looking around it seems that this behavior can happen when one registers a global keymap which does nothing, but I'm not sure what inside Wire is triggering this.

**Comment by mythsunwind** [comment] 2019-01-14 21:00
This might have been broken by this PR: https://github.com/wireapp/wire-desktop/pull/2019

**Comment by terba** [comment] 2019-01-16 13:19
Exactly the same here on OpenSuSE TW.

**Comment by ffflorian** [comment] 2019-01-16 16:36
Duplicate of https://github.com/wireapp/wire-desktop/issues/2056.

**Closed by ffflorian** 2019-01-16 16:36 UTC
