### ISSUE TITLE
[Linux] Messages not received while file select dialog open

### ISSUE THREAD

**Issue by Nateowami** [wireapp/wire-desktop#490] opened 2017-03-02 15:14 UTC
While sending some files I accidentally left a file select dialog open. A couple hours later I realized it and closed the dialog. Immediately afterwards messages appeared. While this is certainly an edge case, it would be preferable for messages to arrive and notifications to be displayed while the dialog is open.

**Comment by mythsunwind** [comment] 2017-03-03 09:45
https://github.com/electron/electron/pull/8702

**Comment by ffflorian** [comment] 2017-04-11 15:54
@Nateowami This should have been solved in Electron 1.6.2 and thus in 17d3fde64c27bc00434cc89ba0b6cf1893ebb16b. I just tried it on Debian 9 with Gnome 3 and could not reproduce - therefore I am closing this for now. Feel free to reopen if this problem persists.

**Closed by ffflorian** 2017-04-11 15:54 UTC
Labels: Bug

**Comment by Nateowami** [comment] 2017-04-13 09:37
@ffflorian Thanks, glad to hear it! Inasmuch as the latest .deb is at 2.12.2729 and I haven't been building from source, let's just assume for now it's fixed and I'll give it a try when a new binary is released.
