### ISSUE TITLE
Two of three participants of a calling session can't hear each other anymore

### ISSUE THREAD

**Issue by kaymio** [wireapp/wire-desktop#896] opened 2017-08-23 11:37 UTC
Wire Version: 2.15.2751-2
Wire for Web Version: 
OS: Arch Linux x64 4.12.8-2
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Three users start a session between Linux, Browser (Win10) and Windows 7 clients
2. 10 - 20 minutes pass by
3. Two of the three users hear a disconnect sound
4. The third user is able to talk to the other two but they can't talk to each other. Don't hear each other.
5. Clients have to be started up again till the same problem occurs again.

What is the expected result?
Talking for hours uninterrupted.

What happens instead?
Talking for 10 - 20 minutes till clients have to be restarted.

During a call session between three accounts, two callers suddenly hear the disconnect sound. This results in a weird situation when the one caller not affected by the bug is hearing the other two participants and can talk to them, but they can't hear each other. This happened regularly, at least five times in a row, within 10 to 20 minutes into the call. 

Affected clients were Browser, Linux, Windows.  I changed to the Browser client to ensure that the (experimental) Linux client (Arch Linux - Wire 2.15.2751-2) was not the source of the problem, but it still happened. So I don't know where the problem lies. The support page of wire doesn't allow me to post the problem and is referring to this github page.

By the way, no useful information was found in the logs under ~/.config/Wire. 
I get this when starting wire-desktop via the console.
Failed to rename log file (/home/X/.config/Wire/logs/0cf7e59c-5d0f-4327-ae5f-b33fae88685c/console.log) with error: ENOENT: no such file or directory, rename '/home/X/.config/Wire/logs/0cf7e59c-5d0f-4327-ae5f-b33fae88685c/console.log' -> '/home/X/.config/Wire/logs/0cf7e59c-5d0f-4327-ae5f-b33fae88685c/console.old'

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by kaymio** [comment] 2017-08-24 13:53
Bug confirmed between three Browsers on Windows. So I should report it on the support page from Wire? They don't let me if they recognize a Browser on Linux...

**Comment by FHTheron** [comment] 2017-09-10 08:25
I've reported this via the support site previously and could not provide enough useful details. They said they set up group calls as a mesh and have rolled out fixes in the past, but because we were also connected to a VPN we might have triggered some corner cases.

I'll add parts of the ticket here. For Wire reference, support ticket 42178.

> I and two colleagues have just had a group audio call with a very weird problem. One person disconnected and rejoined, but then it was as if two of us were in one-to-one calls with the third person and the third person was in a call with both of us at the same time. Since each of us had a different view of the event, I'll try to explain the sequence of events as best I can. If we can provide more info that could help identify anything useful in server logs, please let me know.
> 
> Person A:
> * used Wire Desktop on Windows 10.
> Person B:
> * used Wire Web. Windows 7 Professional, Google Chrome 58.0.3029.110 (64-bit)
> Person C:
> * used Wire Desktop on Arch Linux
> 
> * Person A created a group with persons B and C and then started a call.
> * The call lasted a long time, then person B dropped off suddenly.
> * Person A heard a notification sound that might mean "disconnect", but still saw the profile picture of person B.
> * At the same time person C saw the profile picture disappear and kept talking to person A without any issue.
> * After a while, person A heard a second "disconnect" notification sound and person B's profile picture disappeared.
> * Person A kept talking for a while and then person C began asking if we can hear him and after some confusion we determined that person B had rejoined the call but only person C could hear both A and B. Persons A and B had no idea (no profile picture, no audio) that the other person was in the call, so were talking at the same time and person C could hear both at the same time.
> 
> * Person B rejoined the call using a reconnect button.

**Comment by kaymio** [comment] 2017-09-12 08:54
It didn't come to my mind that my VPN might be a culprit. Thx for the precise description. Hopefully someone of the Wire team is picking this up. I'd be happy to test/debug up to the level of my experience.

**Comment by FHTheron** [comment] 2017-09-12 14:34
Just to clarify, the VPN in our case is not a tunnel-all. It's a corporate VPN for a few subnets only and we did not check to see if calls were routing over normal internet or VPN.

If you are actually able to reproduce this, perhaps list the steps specifically and then bring this ticket to attention via the support site.

**Comment by pasikarkkainen** [comment] 2017-09-13 08:13
I've seen this same issue aswell. Basicly it's impossible to have group calls with Wire, because very often some of the users won't hear other. It's super annoying.

We're using VPNs aswell, so it the issue might be related to VPNs indeed.

**Comment by gregor** [comment] 2017-10-11 20:06
Thank you very much for your reports. We are continously working on improvements to our call and group call experience. Since this was opened a number of problems have been addressed. If you run into specific cases and can provide valuable information that might help us track down additional problems.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Closed by gregor** 2017-10-11 20:06 UTC
