### ISSUE TITLE
Do you plan to support the snap-package for the application in order not to be tied to distribution libraries?

### ISSUE THREAD

**Issue by BlinCT** [wireapp/wire-desktop#2071] opened 2019-01-04 11:29 UTC
It would be nice if the application began to distribute in the snap package. Simplify access and support in many distributions.

**Comment by ffflorian** [comment] 2019-01-07 09:47
Hi @BlinCT,
we do not intend to support additional Linux distribution methods and packages at this time.

(duplicate of https://github.com/wireapp/wire-desktop/issues/1168)

**Closed by ffflorian** 2019-01-07 09:47 UTC
Labels: platform: Linux, type: feature-request ✨

**Comment by bitinerant** [comment] 2019-03-02 11:26
A snap package is available. Install via:
```
sudo snap install wire
snap connect wire:camera core:camera
```
