### ISSUE TITLE
"Missing required parameter: client_id" when importing contacts from gmail on linux

### ISSUE THREAD

**Issue by msbentley** [wireapp/wire-desktop#91] opened 2016-10-17 14:04 UTC
Using the linux desktop client (on ubuntu 16.10) the option to get contacts from gmail gives the following error:

```
Error: invalid_request
Missing required parameter: client_id

with the request details:

scope=https://www.googleapis.com/auth/contacts.readonly
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=
```

**Comment by rkyleg** [comment] 2016-10-19 20:46
I am getting this error as well.

**Comment by VosaXalo** [comment] 2016-10-27 16:03
I can confirm this issue too. 
Here my original bug report created on the wire site:

===================================

When I try to import my Google Contacts there is this OAuth2 Error:

400. That’s an error.
Error: invalid_request
Missing required parameter: client_id

So, I'm not able to import my contacts.
This happens with the app on the web, and on the Linux Desktop.
I have not tried yet on the phone.

=====================================
![image](https://cloud.githubusercontent.com/assets/6298140/19775014/4a63f608-9c6f-11e6-8ded-18443adb9614.png)

**Comment by VosaXalo** [comment] 2016-11-06 19:57
I have just updated Wire to the version 2.11.2670 and now the connection to my Google Account works, even with the two-step login that I have activated. However the problem remain. 
After confirming that I allow Wire to connect to the google account, nothing happens. My google contacts are still not imported in Wire.

**Comment by lipis** [comment] 2017-01-25 08:56
Is this still an issue?

**Comment by msbentley** [comment] 2017-01-25 09:09
It works fine for me now!

**Comment by lipis** [comment] 2017-01-25 09:10
Thank you!

**Comment by ConorIA** [comment] 2017-01-25 20:12
Not so fast Mr. @lipis!

![screenshot from 2017-01-25 15-11-04](https://cloud.githubusercontent.com/assets/870746/22307331/8effd538-e310-11e6-9de0-9601df0acd16.png)

v. 2.11.2695

**Comment by lipis** [comment] 2017-01-25 20:24
I see :) and I was happy for a while that it got resolved.. that's a clue though. We had something special for keys, which maybe was never implemented on Linux distributions.  Thanks @ConorIA, I reopened the issue.

**Comment by ConorIA** [comment] 2017-01-25 20:27
I did a quick "search this reposity", and the clientid is at some point `GOOGLE_CLIENT_ID`, `client_id`, and `clientId`, so I wasn't too sure where to look! It's all javascript magic to me! :wink:

**Comment by ConorIA** [comment] 2017-01-28 19:08
The gruntfile `update-keys` task updates the keys in the config file with the following: 
```
        .replace "RAYGUN_API_KEY: ''", "RAYGUN_API_KEY: '#{process.env.RAYGUN_API_KEY or ''}'"
        .replace "GOOGLE_CLIENT_ID: ''", "GOOGLE_CLIENT_ID: '#{process.env.GOOGLE_CLIENT_ID or ''}'"
        .replace "GOOGLE_CLIENT_SECRET: ''", "GOOGLE_CLIENT_SECRET: '#{process.env.GOOGLE_CLIENT_SECRET or ''}'"
```

The keys have to be stored in the local environment. That is why users who are using the official tarballs produced by @lipis aren't having any trouble with this option, whereas users that build their own package (i.e. everyone on Arch or Arch-based distros) are.

**Comment by ConorIA** [comment] 2017-01-28 19:11
By the way @lipis, are the API keys "top secret"? Because if so, we'll need to rethink `asar: false` for the Linux builds. `config.js`, which should contain the correct keys is exposed at `<basedir>/resources/app/js/config.js`.

**Comment by lipis** [comment] 2017-01-28 22:01
Well of course..!! Didn't think of it when you building it yourself you are not getting the keys. We might want to write that in our README file.. 

Also I don't think that there will be any issue with the `asar: false`, because even if it's otherwise you can simply extract it and get the source files if you really want to :) So for now, I think I'll close this issue, because the official distributions are working :)

**Closed by lipis** 2017-01-28 22:01 UTC
