### ISSUE TITLE
Wire breaks urls with underscores

### ISSUE THREAD

**Issue by hylkevds** [wireapp/wire-desktop#820] opened 2017-07-21 07:35 UTC
Wire Version: can not be copy-pasted?! 2.15.2751
Wire for Web Version: can not be copy-pasted?! ....18.1250
OS: Linux Mint
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Past a url with a word with underscores into a message (i.e. http://test.com/something/_something_/somethings)

What is the expected result?
Url is sent as is

What happens instead?
Url is broken, the underscores are removed

**Comment by bennyn** [comment] 2017-07-21 14:30
Thanks for letting us know! It's a duplicate of https://github.com/wireapp/wire-webapp/issues/1538.

**Closed by bennyn** 2017-07-21 14:30 UTC
