### ISSUE TITLE
Screensharing mutes microphone and does not reenable it on Linux

### ISSUE THREAD

**Issue by e-alfred** [wireapp/wire-desktop#457] opened 2017-02-21 20:54 UTC
Hello,

on Kubuntu 14.04, if I start to share my desktop while on a video call, the microphone gets muted and if I end the screen sharing, the audio still stays muted and only ending/restarting the call helps to solve the problem.

**Comment by gregor** [comment] 2017-02-27 17:55
Closing as dupe of wireapp/wire-webapp#219 and #406

**Closed by gregor** 2017-02-27 17:55 UTC
Labels: Bug
