### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by hakito** [wireapp/wire-desktop#1517] opened 2018-06-04 10:26 UTC
Wire version: 3.0.2828 Operating system: Win10 x64 Enterprise Which antivirus software do you have installed: Windows Defender

What steps will reproduce the problem?

1.  Click on any UI Element

What is the expected result?

No error message.

What is the actual result?

Windows error dialog pops up.

Please provide any additional information below. Attach a screenshot if possible.

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from C:\Users\hakito\AppData\Local\wire\app-3.0.2828\resources\app.asar\img\tray.badge.ico
    at _useBadgeIcon (C:\Users\hakito\AppData\Local\wire\app-3.0.2828\resources\app.asar\js\menu\tray.js:83:13)
    at Object._updateBadgeIcon [as updateBadgeIcon] (C:\Users\hakito\AppData\Local\wire\app-3.0.2828\resources\app.asar\js\menu\tray.js:61:5)
    at EventEmitter.ipcMain.on (C:\Users\hakito\AppData\Local\wire\app-3.0.2828\resources\app.asar\main.js:153:8)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\hakito\AppData\Local\wire\app-3.0.2828\resources\electron.asar\browser\api\web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by leehi0210** [comment] 2018-06-04 10:27
![image](https://user-images.githubusercontent.com/37580034/40912725-5bbe0408-682d-11e8-862c-88f2949648c5.png)

**Comment by gregor** [comment] 2018-06-04 10:33
Closing as duplicate of #968

**Closed by gregor** 2018-06-04 10:33 UTC
