### ISSUE TITLE
Wire window becomes white, starts to bring itself to the foreground

### ISSUE THREAD

**Issue by shvchk** [wireapp/wire-desktop#1936] opened 2018-11-26 23:59 UTC
Wire: 3.4.2879 | Wire for web: 2018.11.15.1314 | OS: Ubuntu 18.10 | Antivirus: none

1. Launch Wire
2. Wait some hours, maybe a day
3. Wire suddenly brings itself to the foreground, does so again and again if minimized. Wire window content is just white, no chats, no contacts. I remember once seeing a message like "If you open this ... it will open in another window [or was it tab?]" — not sure I remember it good enough.

**Comment by shvchk** [comment] 2018-12-05 00:33
Video: https://youtu.be/DZ0QTFsfICY
After some time it goes to login screen with a message mentioned above, which says: "Wire is already open in this browser \ If you continue here, you will be logged out on the other tab" ([screenshot](https://i.imgur.com/6vYJROQ.png))

**Comment by ffflorian** [comment] 2018-12-21 13:55
Hi @shvchk,
we just released version [3.5.2881](https://github.com/wireapp/wire-desktop/releases/tag/linux%2F3.5.2881) for Linux. Can you please check if the issue is fixed for you?

**Comment by shvchk** [comment] 2018-12-23 05:11
No, unfortunately the issue still persists.

**Comment by ffflorian** [comment] 2019-05-15 09:19
This should be fixed by now. If not, feel free to comment and I'll reopen.

**Closed by ffflorian** 2019-05-15 09:19 UTC
Labels: platform: Linux, type: fix 🛠
