### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by thisnickwasfree** [wireapp/wire-desktop#4815] opened 2021-02-24 18:21 UTC
70%+ CPU usage in some situations

CPU: i7 Skylake 6770K
OS: Fedora linux
Version of Wire-desktop: wire-desktop-3.22.0_fc22fa7c-1.x86_64 (build from github)

How to reproduce:
1. Start voice call with wire-desktop
2. Switch to second instance of X-server
3. Start some resource-greedy app (some heavy game for example)
4. In 2 or 3 hours you'll get hardly loaded system with wire-desktop utilizing CPU at 70+ percents

Strange thing: I've noticed this only using "simple" calls, not group ones (they were ok).
Previous installed version (wire-desktop-3.11.0_f6917f9-1.x86_64) had no this issue.

**Comment by alien2003** [comment] 2021-02-25 10:01
The same happens to me. Full version of Wire is constantly using 15-17% of CPU. It's too much for app which basically decrypts and encrypts data and sends it over the network?

**Comment by dbquarrel** [comment] 2021-04-09 03:13
It's not just on Linux it's everywhere.

Wire is great for killing your battery on mobile. Wire, while doing nothing will take 50% of a core on an M1 mac. Doing nothing. Sitting there, doing nothing. 

I've been complaining about this for five years. Just have to switch to something else.

**Comment by liskin** [comment] 2021-05-06 14:08
Is this a duplicate of https://github.com/wireapp/wire-desktop/issues/2507 and possibly also https://github.com/wireapp/wire-desktop/issues/2239?

**Comment by ffflorian** [comment] 2021-08-24 14:27
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/2507.

**Closed by ffflorian** 2021-08-24 14:27 UTC
Labels: platform: Linux 🐧
