### ISSUE TITLE
Linux, PgUP and PgDn doesn't work when "wire" window is closed

### ISSUE THREAD

**Issue by marek141017** [wireapp/wire-desktop#2056] opened 2019-01-03 02:50 UTC
Wire version: 3.5.2881 
Wire for web version: 2018.12.04.1424
Operating system: Ubuntu 16.04.5 LTS 
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Start application
2.  Then press "X" to close the window
3.  In any other application window press PgUp or PgDn, they will be ignored

What is the expected result?
PgUp or PgDn works as expected in any other application window

What is the actual result?
PgUp or PgDn is ignored.

Please provide any additional information below. Attach a screenshot if possible.

xinput test "my keyboard device #"
wire window is open:
key press   112 
^[[5~
key release 112
key press   117 
^[[6~
key release 117

as soon as I close the wire window, I get:
key press   112 
key release 112 
key press   117 
key release 117 
key press   112

Wire-desktop intercept PgUp or PgDn pressing.

Thank you.

**Comment by ffflorian** [comment] 2019-01-03 08:50
Closing as duplicate of https://github.com/wireapp/wire-desktop/issues/2046.

**Closed by ffflorian** 2019-01-03 08:50 UTC
