### ISSUE TITLE
🤷‍♂️ 

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#3740] opened 2020-04-02 22:16 UTC
https://youtu.be/SbIijFJ71m0

**Comment by ffflorian** [comment] 2020-04-05 15:26
@Transisto without any kind of background information on this we are not able to find out what's going wrong. Please fill out the issue template instead of just posting YouTube links. Thanks!

**Comment by Transisto** [comment] 2020-04-05 20:10
Windows 10,

How to reproduce : launch wire normally, (happens rarely)

Problem : ask to login when already logged in

Workaround : close wire and open again.

I assume if someone were to try logging at that point he might have his
whole chat history reset.

**Comment by ffflorian** [comment] 2021-03-23 10:03
Duplicate of https://github.com/wireapp/wire-desktop/issues/3790.

**Closed by ffflorian** 2021-03-23 10:03 UTC
Labels: platform: Windows 🖼️
