### ISSUE TITLE
Tray icon doesn't change on new messages in GNU/Linux

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-desktop#359] opened 2017-01-25 11:23 UTC
In Windows when the message is received and the window is not active tray icon changes (blue corner) indicating about new messages. In GNU/Linux nothing happens, only dbus notificaition pops up, icon remains white.

Linux Mint 18 x64 (Ubuntu 16.04)

**Comment by MadEgg** [comment] 2017-01-25 14:01
FYI: In my laptop running Ubuntu 16.04 the tray icon does change: a blue dot appears in the top right corner of the tray icon.

**Comment by ConorIA** [comment] 2017-01-25 20:09
@alien2003, what version are you running? There was an issue some time ago where a bug stopped the badge from working in Linux (#264), but that has since been resolved.

**Comment by lipis** [comment] 2017-01-25 20:20
I'm using Ubuntu 16.04 and it works.. I hope it's just an older version of the app before the #264 fix as @ConorIA mentioned..

**Comment by alien2003** [comment] 2017-01-27 09:38
@ConorIA I've installed it in January. 2.11.2685-33. No badge and that is very annoying

**Comment by ffflorian** [comment] 2017-01-27 09:58
@alien2003 Which Desktop Manager are you using? For Mint there are at least [three default options](http://unix.stackexchange.com/questions/254828/what-is-desktop-manager-of-mint) and IMO in this case that's more important than the Linux version.

As a sidenote: on Debian 8 + Gnome 3 it works correctly.

**Comment by alien2003** [comment] 2017-01-27 14:08
@ffflorian Xfce and it uses usual tray icons, not only indicators and Wire appears as usual tray icon which supports right click

**Comment by gregor** [comment] 2017-01-27 14:47
Version 2.11.2685 is confirmed to be affected by the bug that the icon is missing on Linux. It will work properly again in the next release. Fix #264 was merged after cut off for 2.11.2685. Thereby closing this issue.

**Closed by gregor** 2017-01-27 14:47 UTC

**Comment by alien2003** [comment] 2017-02-03 15:08
And still not fixed. It makes Wire unusable at all

**Comment by ConorIA** [comment] 2017-02-04 16:45
@alien2003, the issue is fixed in upstream. If you are running a Debian-based OS, you can use the instructions in the repo readme to roll a fresh .deb to install.

**Comment by ffflorian** [comment] 2017-02-05 11:25
@alien2003 You could also use my [Wire Desktop build script for Debian](https://gist.github.com/ffflorian/b5e684b5aa449f9338c58ed46b6a5ee5). :slightly_smiling_face:
