### ISSUE TITLE
wire-desktop freezes when receiving a message while window is unfocused (Linux)

### ISSUE THREAD

**Issue by ignacio-vc** [wireapp/wire-desktop#1403] opened 2018-04-15 05:07 UTC
**Wire version:** 3.0.2816
**Wire for Web Version:** 2018.04.12.1337
**Operating system**: Debian GNU/Linux unstable (sid) x86_64
**Window manager**: i3-gaps
Which antivirus software do you have installed: None

**What steps will reproduce the problem?**
1. Start wire-desktop
2. Unfocus the chat window (By either going to the Wire preferences/settings menu, focusing another window, or just switching to a different i3 workspace)
3. Receive a message from any contact

**What is the expected result?**
Being able to focus the window again and see the message normally

**What is the actual result?**
When attempting to refocus the window, wire-desktop freezes and requires a restart (although sound alerts can still be heard going off)
It seems like the problem is cross platform, as Windows users also experience it #179 

**Workaround:**
Like #179 mentions, a workaround is selecting "Off" on Notifications. Sound alerts work fine, but visual notifications are what seem to be the problem.

**Comment by residus** [comment] 2018-04-15 17:56
Hi,

I have exactly the same problem (under Debian testing, using i3wm from the official repos).

**Comment by BVollmerhaus** [comment] 2018-06-14 18:44
Can't reproduce on Linux but can confirm on Windows 10 (1607) with Wire 3.0.2828.

**Comment by BVollmerhaus** [comment] 2018-06-14 18:45
Can't reproduce on Linux (i3wm) but can confirm on Windows 10 (1607) with Wire 3.0.2828.

**Comment by MikeStutzzzz** [comment] 2018-07-08 19:32
I am Starting to see it freeze when receiving messages on Ubuntu 18.04 This is if the app is focused or not. Version 3.2.2840

**Comment by gregor** [comment] 2018-07-13 13:09
Thanks for bearing with us on this.

This is most likely linked to wireapp/wire-webapp#3988 and slow app starts, which have bugged us for way too long. We have identified one particular place in the code that was that slowed this task down significantly. It turned out to be a quite simply fix from the code point of view. Previously a database request  became slower and slower with an increasing database size.

With the performance of this request beeing greatly improved, the app should no longer freeze when you receive a message. This optimization will be part of the next release. Please let us know if you see an improvement.

**Comment by 0xpr03** [comment] 2018-07-17 13:15
This was introduced to me with the latest update. Starts fine, freezes on incoming message when it is in background. After ~3 minutes it's responding again.
[screenshot_20180717_150854](https://user-images.githubusercontent.com/1280209/42819529-2751ca10-89d4-11e8-8b55-8e89bd72e07f.png)

**Comment by gregor** [comment] 2018-07-18 08:36
@0xpr03 Please update your desktop app to the latest version. The update now banner only takes care of the webapp component. The latest version of the desktop app for Linux is 3.2.2840, which can be acquired from https://wire.com/download/.

**Comment by 0xpr03** [comment] 2018-07-18 11:30
I didn't knew about that, thanks for mentioning. Would be nice if the app would at least warn about that, as you normally don't expect an application to have two different update mechanisms, for which one doesn't even notice you about possible updates.

**Comment by MikeStutzzzz** [comment] 2018-07-19 05:06
The startup is quick but I still freeze when receiving new messages. 
Version 3.2.2840
Wire for Web Version 2018.07.16.1405

**Comment by ffflorian** [comment] 2019-01-03 10:46
@MikeStutzzzz did you try updating to the latest version 3.5? I wonder if this still happens for you since I can't reproduce that behavior on Linux or Windows.

**Comment by pExeen** [comment] 2019-04-08 18:29
I found the problem. You need to have a libnotify client running (eg. dunst).

**Comment by pExeen** [comment] 2019-04-08 18:48
But I think the wire should still check if there is a notification daemon running to prevent this from happening.

**Comment by ffflorian** [comment] 2019-04-17 14:59
Seems to be solved. Feel free to comment if @pExeen's comment didn't help you.

**Closed by ffflorian** 2019-04-17 14:59 UTC
Labels: platform: Linux
