### ISSUE TITLE
Grayed out messages???

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#2350] opened 2019-03-15 17:39 UTC
I'm sending a important message and I guess there was a connection interuption

a few day later we find out the text was never sent. 

How can we know if it was sent or not?

The text has a slightly darker shade, that's it, No "not sent" no "Send again"

**Comment by ffflorian** [comment] 2019-03-15 21:01
Duplicate of https://github.com/wireapp/wire-desktop/issues/1256

**Closed by ffflorian** 2019-03-15 21:01 UTC
