### ISSUE TITLE
Large sidebar is neither hideable nor resizeable

### ISSUE THREAD

**Issue by jm3** [wireapp/wire-desktop#825] opened 2017-07-21 21:00 UTC
Wire Version: `2.15.2750`
Wire for Web Version: `2017.07.18.1250`
OS: `Mac OS X Sierra 10.12.5 (16F73)`
Do you have an antivirus software installed: _n/a_

**What steps will reproduce the problem?**
1. Open Wire Desktop
2. Attempt to hide or resize the very large sidebar

**What is the expected result?**
Very large sidebar is hidden, or resizes.

**What happens instead?**
Very large sidebar does not hide or resize.

**Notes:**
Most apps with a split "sidebar / content area" layout allow users to hide and show the sidebar with a menu item and keyboard shortcut. Additionally, it's standard for users to be able to adjust the size of UI panels, especially ones which default to a large size. This feature is therefore expected by users, especially laptop users, and would be welcomed in Wire. Thanks for the consideration.

**Comment by that1communist** [comment] 2017-07-23 21:40
Would it be possible to make it into a seperate window then have various chat windows?

**Comment by UweSauter** [comment] 2017-08-08 20:24
Probably duplicate of #762.

But +1 for one separate window for each conversation.

**Comment by gregor** [comment] 2017-08-29 17:02
Closing as duplicate

**Closed by gregor** 2017-08-29 17:02 UTC
