### ISSUE TITLE
Fails to start with "Error: Cannot find module 'minimist'"

### ISSUE THREAD

**Issue by cwells** [wireapp/wire-desktop#95] opened 2016-10-17 16:26 UTC
Fedora 24, building from source:

```
$ npm start

> wire-desktop@ start /usr/local/src/wire-desktop
> electron electron --debug=5858 --devtools --enable-logging

App threw an error during load
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/local/src/wire-desktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/src/wire-desktop/electron/main.js:25:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/local/src/wire-desktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/src/wire-desktop/electron/main.js:25:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

npm test completes successfully.

**Comment by cwells** [comment] 2016-10-17 16:56
After manually installing dependencies, it runs. Is there some npm command that is missing from the docs to install dependencies?

**Comment by lipis** [comment] 2016-10-17 17:00
Never had issues with that.. maybe it was some kind of glitch in the matrix.. :)

can you try again with a clean version (the first command will delete all the newly created files in that folder.. so at your own risk):

```
git clean -fdx
npm install
```

**Comment by ConorIA** [comment] 2016-10-17 22:10
@lipis, just thought I'd point out that this is the same issue I was experiencing in #56 when I was trying to build in a super minimal docker image.

**Comment by ac360** [comment] 2016-11-08 04:53
We're having the same issue with [our electron app](https://github.com/serverless/dashboard/issues/16).  `minimist` is being tricky.

**Comment by ffflorian** [comment] 2017-03-24 15:15
Since I can't reproduce this I'll close it for now. @cwells Feel free to reopen if you still have issues.

**Closed by ffflorian** 2017-03-24 15:15 UTC

**Comment by maikokuppe** [comment] 2017-04-30 13:58
This is how I solved this in my case:
I had a local npm package linked (with `npm link mylocalnpmpackage`), which itself had to run `npm install`  in its own directory to resolve the error (apparently it depended on minimist).
