### ISSUE TITLE
Wire Android App Not Updating

### ISSUE THREAD

**Issue by purpleden** [wireapp/wire-desktop#2881] opened 2019-07-24 09:07 UTC
Wire version: 3.34.789
Android: Nougat

App not receiving messages if phone gone in to standby, need to reboot phone to get them coming through again

**Comment by ffflorian** [comment] 2019-07-24 09:25
Duplicate of https://github.com/wireapp/wire-webapp/issues/7011

**Closed by ffflorian** 2019-07-24 09:25 UTC
