### ISSUE TITLE
Wire does not add an extension when downloading an image

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#907] opened 2017-08-31 09:48 UTC
Wire Version: 2.15.2750
Wire for Web Version: 2017.08.24.1057
OS: macOS Sierra 10.12.6
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Have a contact send you an image;
2. Choose to download the image;
3. Save it with no changes;
4. Open it from your file system.

What is the expected result?
The image is opened in the default image viewer.

What happens instead?
The image is not opened at all.

The image is saved in a file with no extension so the operating system does not know what to open it with.

**Comment by gregor** [comment] 2017-08-31 10:06
@ddobrev Thanks for your report. This is a known issue caused by electron. The issue is tracked on their end at https://github.com/electron/electron/issues/9933.

Currently we can only point you to the workaround found in that issue as we can no longer downgrade electron due to other limitations.

**Comment by gregor** [comment] 2017-10-11 19:34
Fixed by #971 as part of next release.

**Closed by gregor** 2017-10-11 19:35 UTC
Labels: Bug
