### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#1396] opened 2018-04-10 23:48 UTC
The title says it all!

Is there any plan to distribute **Wire** as a Flatpak?

**Comment by ffflorian** [comment] 2018-04-12 15:18
Duplicate of https://github.com/wireapp/wire-desktop/issues/424, please see https://github.com/wireapp/wire-desktop/issues/424#issuecomment-284144894.

**Closed by ffflorian** 2018-04-12 15:18 UTC
