### ISSUE TITLE
Wire from APT repo throws JS errors (alert dialog)

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire-desktop#590] opened 2017-04-19 13:41 UTC
Uninstalled wire and re-installed via APT repo. Getting errors (screenshot) after startup and similar after switching conversations. (Ubuntu 17.04)

![wire](https://cloud.githubusercontent.com/assets/1159817/25182985/943f0774-2516-11e7-986c-aa57662a3579.png)

**Comment by gregor** [comment] 2017-04-19 13:58
Thanks for your report. Closing as duplicate of known issue #467.

**Closed by gregor** 2017-04-19 13:58 UTC
