### ISSUE TITLE
[Linux] Wire pseudo-hangs for 20-40 seconds before starting to decrypt messages on launch

### ISSUE THREAD

**Issue by lrenaud** [wireapp/wire-desktop#3806] opened 2020-04-24 02:38 UTC
Wire version: 3.16.2923
Wire for web version: 2020.04.21.0832
Operating system: Linux
Which antivirus software do you have installed: N/A

What steps will reproduce the problem?

1.  Launch wire either by calling `wire-desktop` from a command line or using a GUI launcher.
2.  Wire loads to a screen showing the main electron menu bar (Wire, Conversation, Edit, Window, Help), and the account selector (active accounts, and a gray circle missing the + sign to add a new account) and the reamainder of the window is white.
3. Clicking the + button or the existing users does not change the UI other than displaying a close X in the upper right hand corner when the grey button is selected. The menus appear to behave somewhat normally. After between 20-40 seconds the normal "Decrypting Messages" style loading bar appears and the desktop app loads as expected.
4. After the loading bar appears clicking the grey circle presents the conventional wire login window.
5. Behavior is persistent across reboots and relaunching wire in a single desktop session.

What is the expected result?

1. Launch wire.
2. The UI opens and promptly shows the loading bar indicating activity. Presenting the login window should be available nearly immediately after startup.

What is the actual result?

1. Unclear behavior obfuscates some unknown process to the user giving the impression of broken software if extreme patience is not taken.
2. A single divergence on initial launch and subsequent launches where the "add account" login option is available promptly on subsequent launches, but not the initial launch.

Please provide any additional information below. Attach a screenshot if possible.

Ryzen 2700 with 16GB of RAM using an SSD. No other processes are being launched when trying to launch wire. This is not a resource constraint problem.

![Screenshot_20200423_0001](https://user-images.githubusercontent.com/836281/80169173-9e447b00-8599-11ea-8988-2fe3134a16a3.png)

Delay following launch in a 33 second GIF. https://media.giphy.com/media/XxpI46JrcRvdaD2jXO/giphy.gif

**Comment by ffflorian** [comment] 2020-05-07 09:21
Hi @lrenaud,

thanks for the detailed issue description. The empty window you see is Wire trying to load the Webapp hosted on app.wire.com. I am wondering why it takes so long for you. Can you try opening [app.wire.com](https://app.wire.com) in a browser and see if it also takes that long?

**Comment by xtotdam** [comment] 2020-05-07 18:08
This problem is also present on Windows

**Comment by lrenaud** [comment] 2020-05-08 01:53
As of the most recent update to my desktop package (Wire reporting version 3.17.2924, and "Wire for Web Version 2020.05.07.0941) the problem no longer presents itself.

Whatever the root cause is is very clearly linked to that specific Wire for Web version.

**Comment by ffflorian** [comment] 2020-05-08 06:46
Thanks for the info, since the problem is gone I'll close this issue. Feel free to comment if the problem happens again.

**Closed by ffflorian** 2020-05-08 06:46 UTC
Labels: platform: Linux 🐧, status: need-more-info
