### ISSUE TITLE
Feature request: ctrl+`+ or -` to change the zoom level of the app 

### ISSUE THREAD

**Issue by NukeManDan** [wireapp/wire-desktop#4295] opened 2020-09-17 18:36 UTC
Wire version: 3.19.2928
Wire for web version: 
Operating system: Linux
Which antivirus software do you have installed: N/A

What steps will reproduce the problem?

1.  try ctrl++ and ctrl+- to adjust zoom and nothing happens 

What is the expected result?

zoom level of the app is adjusted

What is the actual result?

No response. 

Please provide any additional information below. Attach a screenshot if possible.

most electron apps I use have this feature. As an alternative, letting a user set the font size for the app would provide most of what I am looking for (easy to read, larger text)

**Comment by ffflorian** [comment] 2020-09-18 07:32
Hi @NukeManDan, this feature request is a duplicate of https://github.com/wireapp/wire-desktop/issues/2892. The feature was implemented [recently](https://github.com/wireapp/wire-desktop/pull/4158) and will be part of the next release.

**Closed by ffflorian** 2020-09-18 07:32 UTC
