### ISSUE TITLE
"Happy face" emoji is not displayed

### ISSUE THREAD

**Issue by Vlado-99** [wireapp/wire-desktop#1862] opened 2018-11-05 21:50 UTC
Wire version: 3.3.28.68 Wire for web version: 2018.11.05.1121 Operating system: Windows 7 Professional 64-bit

What steps will reproduce the problem?

1.  Send string :-) in chat. Send string :-( in chat.

What is the expected result?

String :-) converted to "happy face" emoji. String :-( converted to "sad face" emoji.

What is the actual result?

Empty square instead of "happy face". "Sad face" is displayed correctly.

Please provide any additional information below. Attach a screenshot if possible.

On mobile device (android) are both emojis displayed correctly.

**Comment by ffflorian** [comment] 2018-11-06 08:56
Duplicate of https://github.com/wireapp/wire-desktop/issues/1588.

**Closed by ffflorian** 2018-11-06 08:56 UTC
