### ISSUE TITLE
Wire for OSX/Windows - issues with Audio/Video

### ISSUE THREAD

**Issue by lu-chi** [wireapp/wire-desktop#321] opened 2017-01-15 19:28 UTC
Wire on OSX/ Windows has several issues with audio/video settings. Connecting directly via video call is almost impossible - most of the time either video or voice (most of the time both) do not work both ways. Connecting only a voice chat most of the time works fine after a couple connection attempts.

**Comment by herrmannplatz** [comment] 2017-01-18 10:22
These calls where always between desktop clients?

**Comment by lu-chi** [comment] 2017-01-19 21:56
Sorry for late answer. Yes, indeed, both are desktop clients.

**Comment by shortybeard** [comment] 2017-01-25 22:32
I just started using Wire today and experienced very similar issues myself. Using the desktop Windows 10 app from a desktop PC on both ends my connection and I only managed to get video and audio working both ways 1 time out of 5-6 attempts. Voice only both ways worked fine, but who's camera would work and when seemed random.
We tested further by connecting one web client to a desktop client (both still windows 10) and the issues were the same. Only successful connection both ways required us to both use the web app, and even then we had to reconnect and reload the webpage several times to get there. Often I would be able to hear and see my connection fine but he could only hear me and not see me, despite the settings inside Wire showing my webcam working properly. This issue would sometimes reverse and my connection would say his cam was showing fine but I could not see it, yet audio worked both ways.
When this occurs screen share does not work either for the end where video is also not working.
Of the available experiences on windows desktop the web based client is the better of the two. The standalone Windows 10 app has yet to function properly anytime I have launched it.

**Comment by shortybeard** [comment] 2017-01-25 22:46
Just discovered another issue. When using one web app and one desktop app(windows 10) after any user screen shares(from the desktop app), once they return to webcam the audio is no longer working for the person that screen shared. The issue is not fixable until the call is ended and re-established.

**Comment by helenakos** [comment] 2017-01-26 10:43
@shortybeard Hey, thanks for reporting the issues. Can you grab the logs next time you have a failed call and attach them here or send to our CS?

**Comment by gregor** [comment] 2017-01-26 14:39
Second issue is known. We depend on `RTCSender.replaceTrack` functionality, which still is not implemented in Chrome. This has been pushed back so that we might have to reconsider implementing a fix for the current renegotiation used instead.

**Comment by shortybeard** [comment] 2017-01-26 19:53
@helenakos I will grab the logs and attach them next time I have an issue with the video calling.
@gregor So far I haven't had screen share work without causing audio to cut out. However it is implemented, the way it should work is that audio should always be continuous regardless of video source. Same thing happens if I switch webcams (i have 2 cams setup for streaming.) It appears any change at all to video source except disabling video causes the audio to cut out(only for the user who changed cams or screen shared.) Obviously this is specific to the windows desktop app, as screen sharing doesn't seem to be an option in browser.

**Comment by gregor** [comment] 2017-01-27 15:20
@shortybeard If you start screensharing from an audio call, the audio will not interrupt. You can also use Firefox and the audio will not interrupt when screensharing from a video call or switching cameras in an ongoing video call.

Sorry for the inconvenience. I hope I will be able to dedicate time to fix this soon.

**Comment by shortybeard** [comment] 2017-01-28 03:27
@gregor Thanks for the reply Gregor. No inconvenience at all. I personally want Wire to be as great as it can be because I fully support open source software and anyone who support privacy etc.
I have already convinced 5-6 of my friends to switch over to wire, but we are all tecky computer people and don't mind a few bugs. I just worry for the non-tech user if some of the bugs are a deal breaker, especially when platforms such as Skype are so established already. Keep up the great work and I think Wire will be successful.

**Comment by gregor** [comment] 2017-03-17 15:55
We have made many improvements which are already live, are going live next week or fairly soon like https://github.com/wireapp/wire-webapp/pull/915. Will thereby close this issue. Please reopen if you continue to see problems.

**Closed** 2017-03-28 10:13 UTC
Labels: Bug
