### ISSUE TITLE
Blurry text / screen rendering issues (Windows 10)

### ISSUE THREAD

**Issue by bryc** [wireapp/wire-desktop#2045] opened 2018-12-28 19:34 UTC
Wire version: Wire 3.5.2899
Operating system: Windows 10 v. 1703 (Fresh installation)
Which antivirus software do you have installed: Malwarebytes

This does not seem to occur on a Windows 7 machine.

**What steps will reproduce the problem?**

1. Opening any chat window with any contact and moving the mouse over text repeatedly
or switching back and forth from wire window and any other program will eventually cause text to become blurry, or out of focus.

**What is the expected result?**

Text should not, and has never been blurry intermittently with Wire, ever before.

**What is the actual result?**

Text becomes blurry, and intermittently comes _into and out of focus_.

Here are some screenshots depicting the issue (they have not been altered in image-editing software):
(Please view the larger images in a new tab to see it non-scaled)

On a fresh start of Wire, it looks markedly off:
![image](https://user-images.githubusercontent.com/1408749/50526000-1f2a5a00-0aad-11e9-884d-c788a51be62b.png)

![image](https://user-images.githubusercontent.com/1408749/50526015-41bc7300-0aad-11e9-9d17-874c754933fb.png)

It gets worse during run-time when moving mouse/window around:
![image](https://user-images.githubusercontent.com/1408749/50525932-aaefb680-0aac-11e9-8564-ba0c0dc9d39e.png)

![image](https://user-images.githubusercontent.com/1408749/50525950-c0fd7700-0aac-11e9-9dea-39dcf7e7f76b.png)

**Comment by bryc** [comment] 2018-12-28 19:38
Possibly the blurring algorithm used for the sidebar is somehow being applied globally?

**Comment by ffflorian** [comment] 2019-01-02 09:20
@bryc I'm pretty sure this is a duplicate of https://github.com/wireapp/wire-desktop/issues/1937.

**Comment by ffflorian** [comment] 2019-01-03 10:37
@bryc can you try applying my instructions from https://github.com/wireapp/wire-desktop/issues/1937#issuecomment-442448094 and report back if it worked for you?

**Comment by bryc** [comment] 2019-01-04 06:10
@ffflorian yea that seemed to work. it was an issue with NVIDIA drivers.

**Comment by ffflorian** [comment] 2019-01-04 07:21
@bryc Glad to hear that! I'll close this issue then.

**Closed by ffflorian** 2019-01-04 07:21 UTC
Labels: platform: Windows
