### ISSUE TITLE
Markdown interferes with links that contain underscores at word boundaries

### ISSUE THREAD

**Issue by Siguza** [wireapp/wire-desktop#990] opened 2017-09-30 09:55 UTC
Wire Version: 3.0.2814
Wire for Web Version: 2017.09.26.1300
OS: macOS Sierra 10.12.6
Do you have an antivirus software installed: Nope

What steps will reproduce the problem?
1. Have a link that contains underscores at a word boundary, e.g. `https://example.com/_test_` (the link that triggered this discovery was `https://www.theiphonewiki.com/wiki/Dillon_13D15_(iPad4,4)`).
2. Post that link in a wire chat.

What is the expected result?
The entire link is detected, coloured and made clickable.

What happens instead?
![screen shot 2017-09-30 at 11 50 29](https://user-images.githubusercontent.com/1659374/31044767-a99398fc-a5d5-11e7-9769-30a8db577638.png)
'Nuff said?

It doesn't happen with any underscores though, e.g. `https://github.com/xerub/extra_recipe` renders correctly. It seems to be limited to the case where an underscore appears next to a word boundary, i.e. expressed in regex: `\b_` or `_\b`.

**Comment by gregor** [comment] 2017-09-30 12:26
Thank you very much for your report. This is a known issue in the webapp component used within our desktop offering. The issue is tracked at https://github.com/wireapp/wire-webapp/issues/1538. Thus I am going ahead with closing this.

**Closed by gregor** 2017-09-30 12:26 UTC
