### ISSUE TITLE
Weird beeping noise before connection breaks down.

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-desktop#167] opened 2016-11-08 18:18 UTC
The issue has been occuring a few times in the last few days, both when video calling and when doing a voice call only.

The beeping starts, and you stop hearing/seeing the other person, a few seconds later, the connection is terminated.

What is the beeping supposed to indicate and why is the connection being terminated? How could I fix this?

**Comment by shvchk** [comment] 2016-11-14 06:29
I think I've experienced the same just once a few days ago. Wire 2.11.2670 on Ubuntu linux

**Comment by ConorIA** [comment] 2016-11-16 04:36
I think this is normal behaviour. The beeping is a warning to indicate that the connection has broken down (I am pretty sure).

**Comment by rbieb** [comment] 2016-11-16 07:31
Well, that's what I thought, but the question remains: Why does the connection break down? I've also experienced this in a voice call from one computer to another (both on ethernet, so no wifi).

**Comment by helenakos** [comment] 2016-11-22 09:52
@rbieb The beeping means that the connection is being re-established. Unfortunately in your case the connection broke down.

**Comment by gregor** [comment] 2017-01-26 13:59
As @helenakos. The beeping noise indicates a broken down connection while we try to recover. This is currently by design and there are no current plans to change this. Connections can be terminated due to a magnitude of reasons. Changing networks, packet loss, unstable connections in general. All of this is handled inside the Chrome webRTC implementation, which we do not touch. Thereby closing this.

**Closed by gregor** 2017-01-26 13:59 UTC
