### ISSUE TITLE
Pasting image has no GUI indicator and is confusing 

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire-desktop#1209] opened 2018-01-15 18:02 UTC
When you copy and paste an image from your desktop into wire, there is a delay. Usually this delay is between 2-8 seconds. Sometimes i'm unsure if the paste took and am forced to just wait. It would be a user interface enhancement to have a graphical indicator letting the user know the image is being 'processed', sent, etc. 

Wire version: 3.0.28.28
Operating system: Windows 10

**Comment by gregor** [comment] 2018-01-15 20:05
Thanks for your feedback. We are aware of this usability limitation and intend to improve in this area with no fixed timeframe as of now.

**Comment by cardassian-tailor** [comment] 2018-01-15 20:06
awesome thank you

**Comment by gregor** [comment] 2018-06-01 10:28
I will go ahead and close this as a duplicate of #1175 at this time. Unfortunately we still have not been able to allocate the resources to implement the improvements we have in mind.

**Closed by gregor** 2018-06-01 10:28 UTC

**Comment by cardassian-tailor** [comment] 2018-06-01 11:57
Thank you. I would add, if im making a wish list here, that when the image does paste into wire after the delay - there is the smallest of small previews of the image. So small that you cant tell what the image is. If this image preview (before the message is sent) could be made bigger that would be AWESOME. The image preview should allow the user to know they are sending the correct pasted image - right now it does not fill that need. All I can tell is some image posted and I click send hoping i pasted the right image.
