### ISSUE TITLE
[Mac] Cannot show emoji palette in text entry field

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#4869] opened 2021-03-19 12:07 UTC
Wire version: 3.23.4046
Wire for web version: 2021.03.14.14.25
Operating system: MacOS 11.2.3 (20D91)
Which antivirus software do you have installed: none

What steps will reproduce the problem?

1.  Start typing a message to someone
2.  try to enter an emoji from the emoji palette (opens with command-control-space for me in other apps)
3.  … *crickets* palette doesn't appear.

What is the expected result?
<img width="353" alt="image" src="https://user-images.githubusercontent.com/57199/111777683-e3f5ea80-88b3-11eb-91d3-b11fa435bf5d.png">

A palette like this should appear.

What is the actual result?
... <- this exactly

This has worked in the past - I am not sure since when exactly it is broken, but I suspect it has been broken for some weeks now.

**Comment by ffflorian** [comment] 2021-04-01 08:27
Hi @dwt, can you retry with version 3.24? I just tested it and it works for me on macOS 11.2.3.

**Comment by dwt** [comment] 2021-04-08 10:59
Version 3.24.4059 does not work for me - same problem as described.

**Comment by ffflorian** [comment] 2021-04-08 11:13
Does the emoji input appear in Chrome?

**Comment by dwt** [comment] 2021-04-08 12:22
<img width="467" alt="image" src="https://user-images.githubusercontent.com/57199/114025815-d52ca300-9875-11eb-8c9b-a88e8489404e.png">
In the input window of Chromium Version 90.0.4414.0 (Entwickler-Build) (x86_64) erscheint der emoji input wie erwartet.

**Comment by dwt** [comment] 2021-04-08 12:26
Same on Version 91.0.4472.0 (Entwickler-Build) (x86_64) (current nightly)

**Comment by ffflorian** [comment] 2021-04-08 12:32
What about the conversation input bar on a conversation in the WebApp? Does the input appear there, too?

**Comment by dwt** [comment] 2021-04-08 12:43
The input bar works in chromium Version 91.0.4472.0 (Entwickler-Build) (x86_64)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/57199/114028464-c8f61500-9878-11eb-813a-bd372366c801.png">

**Comment by ffflorian** [comment] 2021-04-26 08:17
Super strange as I still can't reproduce it.

**Comment by dwt** [comment] 2021-04-26 09:00
Hm, I just switched the language form  'Englisch' to 'Deutsch' - and now the emoji input palette appears perfectly. Switching back to 'Englisch' and it is gone again.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/57199/116056808-7c834580-a67e-11eb-9cf0-9a37ac057212.png">

So it seems the Language Settings play a role? (BTW: WTF isn't automatically the system language selected?)

**Comment by ffflorian** [comment] 2021-04-26 09:10
Ah, good find! I will investigate this.

**Comment by tlebon** [comment] 2022-10-12 17:17
this is a bit old and it definitely works now so I will close this. Please reopen if it recurs.

**Closed by tlebon** 2022-10-12 17:17 UTC
Labels: platform: macOS 🍏, status: investigating
