### ISSUE TITLE
Wire Desktop Using Excessive RAM

### ISSUE THREAD

**Issue by rkapur-gds** [wireapp/wire-desktop#4939] opened 2021-04-13 14:12 UTC
Wire version: 3.21.3959
Wire for web version: 2021.04.01.08.46
Operating system: macOS 11.2.3 (20D91)
Which antivirus software do you have installed: ESET

Wire for desktop on macOS slowly increases in RAM usage. A restart of the application fixes this, but over time (a few hours) the RAM usage increases substantially. 

![image](https://user-images.githubusercontent.com/44845232/114566871-b3019f00-9c40-11eb-9a46-b925c0b2c550.png)

**Comment by ffflorian** [comment] 2021-04-13 14:20
Duplicate of https://github.com/wireapp/wire-desktop/issues/2993

**Closed** 2021-04-15 12:19 UTC
