### ISSUE TITLE
Screen sharing during video call causes no sound for the rest of the call

### ISSUE THREAD

**Issue by NikEfth** [wireapp/wire-desktop#437] opened 2017-02-15 14:32 UTC
Hi, 
Just installed in two machines. One Ubuntu and one Arch. We shared desktops from Ubuntu and sound crashed.

**Comment by DetlevCM** [comment] 2017-02-15 19:29
I just observed the same - on this occasion using Windows to Windows.

**Comment by wangkesen** [comment] 2017-02-16 07:31
Also have this problem as well!

**Comment by gregor** [comment] 2017-02-27 17:55
Closing as dupe of https://github.com/wireapp/wire-webapp/issues/219 and #406

**Closed by gregor** 2017-02-27 17:55 UTC
Labels: Calling
