### ISSUE TITLE
Create native MacOS version for better memory management/less energy usage

### ISSUE THREAD

**Issue by MoritzFago** [wireapp/wire-desktop#642] opened 2017-05-15 18:48 UTC
OS: macOS 10.12.4
Create a native Cocoa Client from the wire-ios client, according to https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/OSX_Technology_Overview/MigratingFromCocoaTouch/MigratingFromCocoaTouch.html this should be doable and would increase performance and decrease energy and general resource consumption. Also this would decrease the attack surface, because it would rip out the electron framework and remove all possible bugs due the use of chromium. For a messenger, whose primary goal is privacy
> Full privacy  
> wire.com

, this would be a huge improvement.
 A port should only need minor code changes and porting the UI from UIKit to AppKit.

**Comment by ddobrev** [comment] 2017-08-24 19:53
I fully support this request. Besides, you could use Qt for a cross-platform client so that Windows and Linux users have better experience too.

**Comment by capasicum** [comment] 2017-08-25 16:34
Hi, I think my problem is related to this thread:

Quite often I see Wire in the list of apps **Using Significant Energy**. The problem is that most of the time I work on my laptop on battery.

It is a bit absurd for a simple chat client to be an energy hog.

**Comment by gregor** [comment] 2017-08-29 17:36
Thank you very much for this request. We currently have no plans to change our desktop app approach. While we know the limitations of relying on electron we will continue this path. Thereby I am closing this request.

**Closed by gregor** 2017-08-29 17:36 UTC
Labels: Feature Request

**Comment by ddobrev** [comment] 2017-09-11 16:17
@gregor I clearly understand your priorities may be different but I cannot help but feel you underestimate this problem. Electron uses an unjustifiable amount of system resources and these are not just bugs in it but rather its very nature. So there's simply no way around it, it has to be entirely replaced. Earlier today a friend sent me this screen-shot taken at a time when Wire was sitting completely idle:

![wire 2017-09-11 at 16 30 12](https://user-images.githubusercontent.com/5193072/30284917-12c96906-9725-11e7-9ece-4f10b1602619.jpg)

This is appalling. My friends and I have so far been unable to find anything else to serve as an adequate replacement for Skype but I am really not certain for how long we can put up with this. In addition, @MoritzFago has a point that you already have a significant portion of the code in the form of your iOS client. I would suggest to at least point us to uservoice.com or some other platforms where users can vote fro this feature, among others. I am fully confident it's going to be in the top 5 of most requested.

**Comment by gregor** [comment] 2017-09-11 16:58
@ddobrev All I am trying to do is manage your expectations. We did have a native macOS app at the time of the launch back in Dezember 2014. Work on this was eventually stopped and the app replaced by the current approach in order to cater for Windows, Linux, macOS and web users with the resources of a single team. While we hear your voices, this is not just a feature request but a business decision we stand behind for the time being. Feel free to upvote this issue even if it is closed. We continue to monitor all our feedback channels but this decision is nowhere near to being revised.

**Comment by ddobrev** [comment] 2017-10-04 18:06
@MoritzFago @capasicum I have started a prototype for a much lighter desktop client for Wire. It's called Fibre - https://gitlab.com/ddobrev/Fibre/ . It consumes 80 % less memory and less power as well.
