### ISSUE TITLE
Dark Theme disabling after quitting app

### ISSUE THREAD

**Issue by jayjay2580** [wireapp/wire-desktop#5117] opened 2021-06-14 21:23 UTC
Wire version: 3.25.4071
Wire for web version: N/A
Operating system: Windows 10 Enterprise OS build 19042.985
Which antivirus software do you have installed: Windows Defender (no 3rd party) 

What steps will reproduce the problem?

1.  ...Turn on Dark Theme via Settings > Options > Dark theme.
2.  ...Dark theme remains enabled/turned on until Wire app has been quit.
3.  ...After quitting Wire app then the Dark Theme needs to be turned on again.

What is the expected result?
Previously, all of our users Dark theme setting was staying enabled upon quitting/reopening of the Wire app.
...

What is the actual result?
The Dark theme is not enabled/turned on when opening Wire app.

![2021-06-14 16_19_32-Wire](https://user-images.githubusercontent.com/44910489/121960928-5dbf3800-cd2c-11eb-931f-17f31ad33cef.jpg)
![2021-06-14 16_18_45-Wire](https://user-images.githubusercontent.com/44910489/121960934-5ef06500-cd2c-11eb-8ad9-9b769ac663f6.jpg)

...

Please provide any additional information below. Attach a screenshot if possible.

This was last working for us in Wire version 3.21.3932. I've also attached a screenshot of that previous working version. 
![2021-06-14 16_34_46-Remote Desktop](https://user-images.githubusercontent.com/44910489/121962720-babbed80-cd2e-11eb-91f1-b95ec5be679a.jpg)

...

**Comment by ffflorian** [comment] 2021-06-15 04:35
Duplicate of https://github.com/wireapp/wire-desktop/issues/5006

**Closed by ffflorian** 2021-06-15 04:35 UTC
