### ISSUE TITLE
enable "calls" without microphone / soundcard or webcam (e.g for screensharing and debugging)

### ISSUE THREAD

**Issue by kolAflash** [wireapp/wire-desktop#2901] opened 2019-07-28 20:14 UTC
Please enable "calling" without a microphone/soundcard or webcam. This will be useful:
- for screensharing
- for debugging - see #2900 weird "no microphone" problem

Currently the app won't allow to call without a working soundcard or webcam.

**Comment by ffflorian** [comment] 2019-07-29 07:37
Duplicate of https://github.com/wireapp/wire-webapp/issues/7018

**Closed by ffflorian** 2019-07-29 07:37 UTC
