### ISSUE TITLE
Two new bugs occuring: Calls silently dropping, screen share not working

### ISSUE THREAD

**Issue by bryc** [wireapp/wire-desktop#1165] opened 2017-12-14 21:46 UTC
I've been using Wire with a friend for some time now, it was amazing how efficient the screen sharing framerate and sound was. However within the last couple of weeks (edit: months), there's been some big issues.

1. Calls end randomly without warning, sometimes with the other user unaware.

Sometimes I check back to Wire and notice that the call ended without any message or popup/warning, no log in the chat either. I often have Wire muted due to screen share sound not always being relevant, so if any sound or "connection beeping" occurred, I wouldn't know.

When this happens, the other party often isn't aware, and continues to message as if the call never ended, thinking I can still see what is on-screen. But this is not every time.

2. Screen sharing fails to connect on my end, only

When I attempt to screen share, the other party immediately cuts out the audio feed, and begins to hears 'connection beeps', which soon ends the call completely. It works if they use screen share on their side. We have both attempted to delete the AppData files, uninstall and reinstall latest version, but that issue appears to remain on my end, not sure why. 

Also, in `--devtools` mode the 'wire' global isn't available so I can't enable debug logging at all using `wire.app.enable_debugging()`

**Comment by harmancasvi** [comment] 2018-04-30 04:41
# Similar issue on version 3.0.2828 with Windows 10
The main issue is not voice related, but is triggered while screen sharing is enabled and suddenly it fails and then the call hangs up.
### Tested scenarios
> **OS:** Windows 10 (1709 build 16299.371]) - on both ends.
>**Wire version:** 3.0.2828 (desktop) - on both ends.
#### Scenarios where the issue reproduces (screen sharing fails):
> + VPN on sharer side and no vpn on the other side.
> + VPN on both sides.
> + No VPN at all on any side an then change of sides while screen sharing in the same call (the viewer becomes sharer).
#### **Scenarios without issue (screen sharing):**
> + No VPN on any side and no change of sides on same call.
> + No VPN on sharer side and no change of sides on same call.

The call stops on sharer side like 10 seconds after screen sharing starts, on the other side it continues the counter and keeps going infinitely.

The VPN used is IPSec w/ PSK on a Mikrotik router with version RouterOS 6.41.2 and corresponding firmware.

Let me know if you have any relevant info or question.

If this issue deserves to be independent, please let me know and I'll create a new one accordingly, I just wrote it here because it seems to me that it could be triggered by the same casue, therefore the issue would end up being the same.

**Comment by gregor** [comment] 2018-06-01 09:40
We have added a call log features option in your account preferences. If you still see these problems please get in touch with our customer support providing them with logs. I am going to close the issue here.

**Closed by gregor** 2018-06-01 09:40 UTC
